define({
  "symbolologyTabLabel": "Ř_Configure Symbology_______ů",
  "facilitiesDescription": "Ř_Facility Layers______ů",
  "demographicsDescription": "Ř_Demographics Layer______ů",
  "settingsTitle": "Ř_Settings___ů",
  "spillLocationLabel": "Ř_Spill Location_____ů",
  "spillLocationButtonLabel": "Ř_Configure Spill Location Settings___________ů",
  "IISettingsLabel": "Ř_Initial Isolation Zone________ů",
  "IIButtonLabel": "Ř_Configure Initial Isolation Settings____________ů",
  "PASettingsLabel": "Ř_Protective Action Zone________ů",
  "PAButtonLabel": "Ř_Configure Protective Action Settings____________ů",
  "downwindSettingsLabel": "Ř_Down Wind Zone_____ů",
  "downwindButtonLabel": "Ř_Configure Down Wind Settings_________ů",
  "fireSettingsLabel": "Ř_Fire Isolation Zone_______ů",
  "fireButtonLabel": "Ř_Configure Fire Isolation Settings___________ů",
  "bleveSettingsLabel": "Ř_BLEVE Isolation Zone_______ů",
  "bleveButtonLabel": "Ř_Configure BLEVE Settings________ů",
  "transparency": "Ř_Transparency_____ů",
  "outline": "Ř_Outline___ů",
  "fill": "Ř_Fill (Color only applies when style set to solid)________________ů",
  "outlineStyle": "Ř_Outline Style_____ů",
  "dash": "Ř_Dash__ů",
  "dashdot": "Ř_Dash Dot___ů",
  "dashdotdot": "Ř_Dash Dot Dot_____ů",
  "dot": "Ř_Dot__ů",
  "longdash": "Ř_Long Dash____ů",
  "longdashdot": "Ř_Long Dash Dot_____ů",
  "null": "Ř_Null__ů",
  "shortdash": "Ř_Short Dash____ů",
  "shortdashdot": "Ř_Short Dash Dot_____ů",
  "shortdashdotdot": "Ř_Short Dash Dot Dot______ů",
  "shortdot": "Ř_Short Dot____ů",
  "solid": "Ř_Solid___ů",
  "fillStyle": "Ř_Fill Style____ů",
  "backward": "Ř_Backward___ů",
  "cross": "Ř_Cross___ů",
  "diagonal": "Ř_Diagonal___ů",
  "forward": "Ř_Forward___ů",
  "horizontal": "Ř_Horizontal____ů",
  "vertical": "Ř_Vertical___ů"
});