define({
  "_widgetLabel": "试_Emergency Response Guide________验",
  "ergMainPageTitle": "试_Based on the Emergency Response Guidebook 2016_______________验",
  "coordInputLabelStart": "试_Spill Location (DD)_______验",
  "coordInputLabel": "试_Spill Location_____验",
  "addPointToolTip": "试_Add Spill Location______验",
  "drawPointToolTip": "试_Click to add spill location_________验",
  "material": "试_Material___验",
  "materialPlaceholder": "试_Start typing to search for a material____________验",
  "table3Message": "试_The material you have selected requires additional information if you are dealing with a large spill.\n\nPlease ensure you have the correct values selected for wind speed and transport container____________________________________________________________验.",
  "table2Message": "试_The material you have selected may produces a large amount of Toxic Inhalation Hazard gases when spilled in water.\n\nYou may want to consider using the following material(s):\n\n_______________________________________________________验",
  "spillSize": "试_Spill Size____验",
  "small": "试_Small___验",
  "large": "试_Large___验",
  "fireLabel": "试_Show Fire Isolation Zone________验",
  "weatherLabel": "试_Current Weather at Spill Location___________验",
  "weatherIntialText": "试_<br />Updated once a spill location has been idenitified__________________验",
  "temperature": "试_Temperature____验",
  "wind": "试_Wind__验",
  "c": "试_C_验",
  "f": "试_F_验",
  "weatherErrorMessage": "试_Weather info not obtained. Update Wind Speed and Time of Spill values manually________________________验",
  "windDirection": "试_Wind Direction (blowing to)_________验",
  "timeOfSpill": "试_Time of Spill_____验",
  "day": "试_Day__验",
  "night": "试_Night___验",
  "windSpeed": "试_Wind Speed____验",
  "low": "试_Low__验",
  "moderate": "试_Moderate___验",
  "high": "试_High__验",
  "transportContainer": "试_Transport Container_______验",
  "rail": "试_Rail tank car_____验",
  "semi": "试_Highway tank truck or trailer__________验",
  "mton": "试_Multiple ton cylinders________验",
  "ston": "试_Multiple small cylinders or single ton cylinder_______________验",
  "ag": "试_Agricultural nurse tank________验",
  "msm": "试_Multiple small cylinders________验",
  "bleveLabel": "试_Show BLEVE Isolation Zone_________验",
  "capacity": "试_Container Capacity (litres)_________验",
  "bleveMessage": "试_For the material you have selected an additional evacuation distance can be shown for BLEVE.\n\nTo enable this, set the Show BLEVE Isolation Zone toggle to on and select the appropiate container capacity______________________________________________________________验.",
  "noPAZoneMessage": "试_There are no Protective Action distances for this material. Only the Initial Isolation and evacuation zones has been calculated_______________________________________验",
  "settingsTitle": "试_Settings___验",
  "spillLocationLabel": "试_Spill Location_____验",
  "spillLocationButtonLabel": "试_Configure Spill Location Settings___________验",
  "IISettingsLabel": "试_Initial Isolation Zone________验",
  "IIButtonLabel": "试_Configure Initial Isolation Settings____________验",
  "PASettingsLabel": "试_Protective Action Zone________验",
  "PAButtonLabel": "试_Configure Protective Action Settings____________验",
  "downwindSettingsLabel": "试_Down Wind Zone_____验",
  "downwindButtonLabel": "试_Configure Down Wind Settings_________验",
  "fireSettingsLabel": "试_Fire Isolation Zone_______验",
  "fireButtonLabel": "试_Configure Fire Isolation Settings___________验",
  "bleveSettingsLabel": "试_BLEVE Isolation Zone_______验",
  "bleveButtonLabel": "试_Configure BLEVE Settings________验",
  "outlineStyle": "试_Outline Style_____验",
  "dash": "试_Dash__验",
  "dashdot": "试_Dash Dot___验",
  "dashdotdot": "试_Dash Dot Dot_____验",
  "dot": "试_Dot__验",
  "longdash": "试_Long Dash____验",
  "longdashdot": "试_Long Dash Dot_____验",
  "null": "试_Null__验",
  "shortdash": "试_Short Dash____验",
  "shortdashdot": "试_Short Dash Dot_____验",
  "shortdashdotdot": "试_Short Dash Dot Dot______验",
  "shortdot": "试_Short Dot____验",
  "solid": "试_Solid___验",
  "fillStyle": "试_Fill Style____验",
  "backward": "试_Backward___验",
  "cross": "试_Cross___验",
  "diagonal": "试_Diagonal___验",
  "forward": "试_Forward___验",
  "horizontal": "试_Horizontal____验",
  "vertical": "试_Vertical___验",
  "resultsTitle": "试_Results___验",
  "publishERGBtn": "试_Publish___验",
  "ERGLayerName": "试_Published ERG Layer Name________验",
  "invalidERGLayerName": "试_Layer name must only contain alpha-numeric characters and underscores______________________验",
  "missingERGLayerName": "试_You must enter a name for the ERG___________验",
  "publishingFailedLayerExists": "试_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________验.",
  "checkService": "试_Check Service: {0}______验",
  "createService": "试_Create Service: {0}_______验",
  "unableToCreate": "试_Unable to create: {0}_______验",
  "addToDefinition": "试_Add to definition: {0}________验",
  "successfullyPublished": "试_Successfully published web layer{0}Manage the web layer__________________验",
  "userRole": "试_Unable to create service because user does not have permissions____________________验",
  "transparency": "试_Transparency_____验",
  "outline": "试_Outline___验",
  "fill": "试_Fill (Color only applies when style set to solid)________________验",
  "createERGBtn": "试_Create Zones_____验",
  "clearERGBtn": "试_Clear___验",
  "labelFormat": "试_Label Format_____验",
  "helpIconTooltip": "试_The threshold between small and large spill sizes are:\nLiquids - 55 gallons (208 liters)\nSolids - 60 pounds (300 kilograms)_______________________________________验",
  "cellWidth": "试_Cell Width (x)_____验",
  "cellHeight": "试_Cell Height (y)______验",
  "invalidNumberMessage": "试_The value entered is not valid__________验",
  "invalidRangeMessage": "试_Value must be greater than 0_________验",
  "gridAngleInvalidRangeMessage": "试_Value must be between -89.9 and 89.9____________验",
  "formatIconTooltip": "试_Format Input_____验",
  "setCoordFormat": "试_Set Coordinate Format String_________验",
  "prefixNumbers": "试_Add '+/-' prefix to positive and negative numbers________________验",
  "cancelBtn": "试_Cancel___验",
  "applyBtn": "试_Apply___验",
  "comfirmInputNotation": "试_Confirm Input Notation________验",
  "notationsMatch": "试_notations match your input please confirm which you would like to use______________________验:",
  "missingLayerNameMessage": "试_You must enter a valid layer name before you can publish__________________验",
  "parseCoordinatesError": "试_Unable to parse coordinates. Please check your input_________________验.",
  "DD": "试_DD__验",
  "DDM": "试_DDM__验",
  "DMS": "试_DMS__验",
  "DDRev": "试_DDRev___验",
  "DDMRev": "试_DDMRev___验",
  "DMSRev": "试_DMSRev___验",
  "USNG": "试_USNG__验",
  "MGRS": "试_MGRS__验",
  "UTM_H": "试_UTM (H)___验",
  "UTM": "试_UTM__验",
  "GARS": "试_GARS__验",
  "GEOREF": "试_GEOREF___验",
  "DDLatLongNotation": "试_Decimal Degrees - Latitude/Longitude____________验",
  "DDLongLatNotation": "试_Decimal Degrees  - Longitude/Latitude____________验",
  "DDMLatLongNotation": "试_Degrees Decimal Minutes - Latitude/Longitude______________验",
  "DDMLongLatNotation": "试_Degrees Decimal Minutes - Longitude/Latitude______________验",
  "DMSLatLongNotation": "试_Degrees Minutes Seconds - Latitude/Longitude______________验",
  "DMSLongLatNotation": "试_Degrees Minutes Seconds - Longitude/Latitude______________验",
  "GARSNotation": "试_GARS__验",
  "GEOREFNotation": "试_GEOREF___验",
  "MGRSNotation": "试_MGRS__验",
  "USNGNotation": "试_USNG__验",
  "UTMBandNotation": "试_UTM - Band Letter______验",
  "UTMHemNotation": "试_UTM - Hemisphere (N/S)________验"
});