define({
  "symbolologyTabLabel": "Š_Configure Symbology_______č",
  "facilitiesDescription": "Š_Facility Layers______č",
  "demographicsDescription": "Š_Demographics Layer______č",
  "settingsTitle": "Š_Settings___č",
  "spillLocationLabel": "Š_Spill Location_____č",
  "spillLocationButtonLabel": "Š_Configure Spill Location Settings___________č",
  "IISettingsLabel": "Š_Initial Isolation Zone________č",
  "IIButtonLabel": "Š_Configure Initial Isolation Settings____________č",
  "PASettingsLabel": "Š_Protective Action Zone________č",
  "PAButtonLabel": "Š_Configure Protective Action Settings____________č",
  "downwindSettingsLabel": "Š_Down Wind Zone_____č",
  "downwindButtonLabel": "Š_Configure Down Wind Settings_________č",
  "fireSettingsLabel": "Š_Fire Isolation Zone_______č",
  "fireButtonLabel": "Š_Configure Fire Isolation Settings___________č",
  "bleveSettingsLabel": "Š_BLEVE Isolation Zone_______č",
  "bleveButtonLabel": "Š_Configure BLEVE Settings________č",
  "transparency": "Š_Transparency_____č",
  "outline": "Š_Outline___č",
  "fill": "Š_Fill (Color only applies when style set to solid)________________č",
  "outlineStyle": "Š_Outline Style_____č",
  "dash": "Š_Dash__č",
  "dashdot": "Š_Dash Dot___č",
  "dashdotdot": "Š_Dash Dot Dot_____č",
  "dot": "Š_Dot__č",
  "longdash": "Š_Long Dash____č",
  "longdashdot": "Š_Long Dash Dot_____č",
  "null": "Š_Null__č",
  "shortdash": "Š_Short Dash____č",
  "shortdashdot": "Š_Short Dash Dot_____č",
  "shortdashdotdot": "Š_Short Dash Dot Dot______č",
  "shortdot": "Š_Short Dot____č",
  "solid": "Š_Solid___č",
  "fillStyle": "Š_Fill Style____č",
  "backward": "Š_Backward___č",
  "cross": "Š_Cross___č",
  "diagonal": "Š_Diagonal___č",
  "forward": "Š_Forward___č",
  "horizontal": "Š_Horizontal____č",
  "vertical": "Š_Vertical___č"
});