define({
  "_widgetLabel": "æ_Emergency Response Guide________Â",
  "ergMainPageTitle": "æ_Based on the Emergency Response Guidebook 2016_______________Â",
  "coordInputLabelStart": "æ_Spill Location (DD)_______Â",
  "coordInputLabel": "æ_Spill Location_____Â",
  "addPointToolTip": "æ_Add Spill Location______Â",
  "drawPointToolTip": "æ_Click to add spill location_________Â",
  "material": "æ_Material___Â",
  "materialPlaceholder": "æ_Start typing to search for a material____________Â",
  "table3Message": "æ_The material you have selected requires additional information if you are dealing with a large spill.\n\nPlease ensure you have the correct values selected for wind speed and transport container____________________________________________________________Â.",
  "table2Message": "æ_The material you have selected may produces a large amount of Toxic Inhalation Hazard gases when spilled in water.\n\nYou may want to consider using the following material(s):\n\n_______________________________________________________Â",
  "spillSize": "æ_Spill Size____Â",
  "small": "æ_Small___Â",
  "large": "æ_Large___Â",
  "fireLabel": "æ_Show Fire Isolation Zone________Â",
  "weatherLabel": "æ_Current Weather at Spill Location___________Â",
  "weatherIntialText": "æ_<br />Updated once a spill location has been idenitified__________________Â",
  "temperature": "æ_Temperature____Â",
  "wind": "æ_Wind__Â",
  "c": "æ_C_Â",
  "f": "æ_F_Â",
  "weatherErrorMessage": "æ_Weather info not obtained. Update Wind Speed and Time of Spill values manually________________________Â",
  "windDirection": "æ_Wind Direction (blowing to)_________Â",
  "timeOfSpill": "æ_Time of Spill_____Â",
  "day": "æ_Day__Â",
  "night": "æ_Night___Â",
  "windSpeed": "æ_Wind Speed____Â",
  "low": "æ_Low__Â",
  "moderate": "æ_Moderate___Â",
  "high": "æ_High__Â",
  "transportContainer": "æ_Transport Container_______Â",
  "rail": "æ_Rail tank car_____Â",
  "semi": "æ_Highway tank truck or trailer__________Â",
  "mton": "æ_Multiple ton cylinders________Â",
  "ston": "æ_Multiple small cylinders or single ton cylinder_______________Â",
  "ag": "æ_Agricultural nurse tank________Â",
  "msm": "æ_Multiple small cylinders________Â",
  "bleveLabel": "æ_Show BLEVE Isolation Zone_________Â",
  "capacity": "æ_Container Capacity (litres)_________Â",
  "bleveMessage": "æ_For the material you have selected an additional evacuation distance can be shown for BLEVE.\n\nTo enable this, set the Show BLEVE Isolation Zone toggle to on and select the appropiate container capacity______________________________________________________________Â.",
  "noPAZoneMessage": "æ_There are no Protective Action distances for this material. Only the Initial Isolation and evacuation zones has been calculated_______________________________________Â",
  "settingsTitle": "æ_Settings___Â",
  "spillLocationLabel": "æ_Spill Location_____Â",
  "spillLocationButtonLabel": "æ_Configure Spill Location Settings___________Â",
  "IISettingsLabel": "æ_Initial Isolation Zone________Â",
  "IIButtonLabel": "æ_Configure Initial Isolation Settings____________Â",
  "PASettingsLabel": "æ_Protective Action Zone________Â",
  "PAButtonLabel": "æ_Configure Protective Action Settings____________Â",
  "downwindSettingsLabel": "æ_Down Wind Zone_____Â",
  "downwindButtonLabel": "æ_Configure Down Wind Settings_________Â",
  "fireSettingsLabel": "æ_Fire Isolation Zone_______Â",
  "fireButtonLabel": "æ_Configure Fire Isolation Settings___________Â",
  "bleveSettingsLabel": "æ_BLEVE Isolation Zone_______Â",
  "bleveButtonLabel": "æ_Configure BLEVE Settings________Â",
  "outlineStyle": "æ_Outline Style_____Â",
  "dash": "æ_Dash__Â",
  "dashdot": "æ_Dash Dot___Â",
  "dashdotdot": "æ_Dash Dot Dot_____Â",
  "dot": "æ_Dot__Â",
  "longdash": "æ_Long Dash____Â",
  "longdashdot": "æ_Long Dash Dot_____Â",
  "null": "æ_Null__Â",
  "shortdash": "æ_Short Dash____Â",
  "shortdashdot": "æ_Short Dash Dot_____Â",
  "shortdashdotdot": "æ_Short Dash Dot Dot______Â",
  "shortdot": "æ_Short Dot____Â",
  "solid": "æ_Solid___Â",
  "fillStyle": "æ_Fill Style____Â",
  "backward": "æ_Backward___Â",
  "cross": "æ_Cross___Â",
  "diagonal": "æ_Diagonal___Â",
  "forward": "æ_Forward___Â",
  "horizontal": "æ_Horizontal____Â",
  "vertical": "æ_Vertical___Â",
  "resultsTitle": "æ_Results___Â",
  "publishERGBtn": "æ_Publish___Â",
  "ERGLayerName": "æ_Published ERG Layer Name________Â",
  "invalidERGLayerName": "æ_Layer name must only contain alpha-numeric characters and underscores______________________Â",
  "missingERGLayerName": "æ_You must enter a name for the ERG___________Â",
  "publishingFailedLayerExists": "æ_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________Â.",
  "checkService": "æ_Check Service: {0}______Â",
  "createService": "æ_Create Service: {0}_______Â",
  "unableToCreate": "æ_Unable to create: {0}_______Â",
  "addToDefinition": "æ_Add to definition: {0}________Â",
  "successfullyPublished": "æ_Successfully published web layer{0}Manage the web layer__________________Â",
  "userRole": "æ_Unable to create service because user does not have permissions____________________Â",
  "transparency": "æ_Transparency_____Â",
  "outline": "æ_Outline___Â",
  "fill": "æ_Fill (Color only applies when style set to solid)________________Â",
  "createERGBtn": "æ_Create Zones_____Â",
  "clearERGBtn": "æ_Clear___Â",
  "labelFormat": "æ_Label Format_____Â",
  "helpIconTooltip": "æ_The threshold between small and large spill sizes are:\nLiquids - 55 gallons (208 liters)\nSolids - 60 pounds (300 kilograms)_______________________________________Â",
  "cellWidth": "æ_Cell Width (x)_____Â",
  "cellHeight": "æ_Cell Height (y)______Â",
  "invalidNumberMessage": "æ_The value entered is not valid__________Â",
  "invalidRangeMessage": "æ_Value must be greater than 0_________Â",
  "gridAngleInvalidRangeMessage": "æ_Value must be between -89.9 and 89.9____________Â",
  "formatIconTooltip": "æ_Format Input_____Â",
  "setCoordFormat": "æ_Set Coordinate Format String_________Â",
  "prefixNumbers": "æ_Add '+/-' prefix to positive and negative numbers________________Â",
  "cancelBtn": "æ_Cancel___Â",
  "applyBtn": "æ_Apply___Â",
  "comfirmInputNotation": "æ_Confirm Input Notation________Â",
  "notationsMatch": "æ_notations match your input please confirm which you would like to use______________________Â:",
  "missingLayerNameMessage": "æ_You must enter a valid layer name before you can publish__________________Â",
  "parseCoordinatesError": "æ_Unable to parse coordinates. Please check your input_________________Â.",
  "DD": "æ_DD__Â",
  "DDM": "æ_DDM__Â",
  "DMS": "æ_DMS__Â",
  "DDRev": "æ_DDRev___Â",
  "DDMRev": "æ_DDMRev___Â",
  "DMSRev": "æ_DMSRev___Â",
  "USNG": "æ_USNG__Â",
  "MGRS": "æ_MGRS__Â",
  "UTM_H": "æ_UTM (H)___Â",
  "UTM": "æ_UTM__Â",
  "GARS": "æ_GARS__Â",
  "GEOREF": "æ_GEOREF___Â",
  "DDLatLongNotation": "æ_Decimal Degrees - Latitude/Longitude____________Â",
  "DDLongLatNotation": "æ_Decimal Degrees  - Longitude/Latitude____________Â",
  "DDMLatLongNotation": "æ_Degrees Decimal Minutes - Latitude/Longitude______________Â",
  "DDMLongLatNotation": "æ_Degrees Decimal Minutes - Longitude/Latitude______________Â",
  "DMSLatLongNotation": "æ_Degrees Minutes Seconds - Latitude/Longitude______________Â",
  "DMSLongLatNotation": "æ_Degrees Minutes Seconds - Longitude/Latitude______________Â",
  "GARSNotation": "æ_GARS__Â",
  "GEOREFNotation": "æ_GEOREF___Â",
  "MGRSNotation": "æ_MGRS__Â",
  "USNGNotation": "æ_USNG__Â",
  "UTMBandNotation": "æ_UTM - Band Letter______Â",
  "UTMHemNotation": "æ_UTM - Hemisphere (N/S)________Â"
});