define({
  "_widgetLabel": "須_Emergency Response Guide________鷗",
  "ergMainPageTitle": "須_Based on the Emergency Response Guidebook 2016_______________鷗",
  "coordInputLabelStart": "須_Spill Location (DD)_______鷗",
  "coordInputLabel": "須_Spill Location_____鷗",
  "addPointToolTip": "須_Add Spill Location______鷗",
  "drawPointToolTip": "須_Click to add spill location_________鷗",
  "material": "須_Material___鷗",
  "materialPlaceholder": "須_Start typing to search for a material____________鷗",
  "table3Message": "須_The material you have selected requires additional information if you are dealing with a large spill.\n\nPlease ensure you have the correct values selected for wind speed and transport container____________________________________________________________鷗.",
  "table2Message": "須_The material you have selected may produces a large amount of Toxic Inhalation Hazard gases when spilled in water.\n\nYou may want to consider using the following material(s):\n\n_______________________________________________________鷗",
  "spillSize": "須_Spill Size____鷗",
  "small": "須_Small___鷗",
  "large": "須_Large___鷗",
  "fireLabel": "須_Show Fire Isolation Zone________鷗",
  "weatherLabel": "須_Current Weather at Spill Location___________鷗",
  "weatherIntialText": "須_<br />Updated once a spill location has been idenitified__________________鷗",
  "temperature": "須_Temperature____鷗",
  "wind": "須_Wind__鷗",
  "c": "須_C_鷗",
  "f": "須_F_鷗",
  "weatherErrorMessage": "須_Weather info not obtained. Update Wind Speed and Time of Spill values manually________________________鷗",
  "windDirection": "須_Wind Direction (blowing to)_________鷗",
  "timeOfSpill": "須_Time of Spill_____鷗",
  "day": "須_Day__鷗",
  "night": "須_Night___鷗",
  "windSpeed": "須_Wind Speed____鷗",
  "low": "須_Low__鷗",
  "moderate": "須_Moderate___鷗",
  "high": "須_High__鷗",
  "transportContainer": "須_Transport Container_______鷗",
  "rail": "須_Rail tank car_____鷗",
  "semi": "須_Highway tank truck or trailer__________鷗",
  "mton": "須_Multiple ton cylinders________鷗",
  "ston": "須_Multiple small cylinders or single ton cylinder_______________鷗",
  "ag": "須_Agricultural nurse tank________鷗",
  "msm": "須_Multiple small cylinders________鷗",
  "bleveLabel": "須_Show BLEVE Isolation Zone_________鷗",
  "capacity": "須_Container Capacity (litres)_________鷗",
  "bleveMessage": "須_For the material you have selected an additional evacuation distance can be shown for BLEVE.\n\nTo enable this, set the Show BLEVE Isolation Zone toggle to on and select the appropiate container capacity______________________________________________________________鷗.",
  "noPAZoneMessage": "須_There are no Protective Action distances for this material. Only the Initial Isolation and evacuation zones has been calculated_______________________________________鷗",
  "settingsTitle": "須_Settings___鷗",
  "spillLocationLabel": "須_Spill Location_____鷗",
  "spillLocationButtonLabel": "須_Configure Spill Location Settings___________鷗",
  "IISettingsLabel": "須_Initial Isolation Zone________鷗",
  "IIButtonLabel": "須_Configure Initial Isolation Settings____________鷗",
  "PASettingsLabel": "須_Protective Action Zone________鷗",
  "PAButtonLabel": "須_Configure Protective Action Settings____________鷗",
  "downwindSettingsLabel": "須_Down Wind Zone_____鷗",
  "downwindButtonLabel": "須_Configure Down Wind Settings_________鷗",
  "fireSettingsLabel": "須_Fire Isolation Zone_______鷗",
  "fireButtonLabel": "須_Configure Fire Isolation Settings___________鷗",
  "bleveSettingsLabel": "須_BLEVE Isolation Zone_______鷗",
  "bleveButtonLabel": "須_Configure BLEVE Settings________鷗",
  "outlineStyle": "須_Outline Style_____鷗",
  "dash": "須_Dash__鷗",
  "dashdot": "須_Dash Dot___鷗",
  "dashdotdot": "須_Dash Dot Dot_____鷗",
  "dot": "須_Dot__鷗",
  "longdash": "須_Long Dash____鷗",
  "longdashdot": "須_Long Dash Dot_____鷗",
  "null": "須_Null__鷗",
  "shortdash": "須_Short Dash____鷗",
  "shortdashdot": "須_Short Dash Dot_____鷗",
  "shortdashdotdot": "須_Short Dash Dot Dot______鷗",
  "shortdot": "須_Short Dot____鷗",
  "solid": "須_Solid___鷗",
  "fillStyle": "須_Fill Style____鷗",
  "backward": "須_Backward___鷗",
  "cross": "須_Cross___鷗",
  "diagonal": "須_Diagonal___鷗",
  "forward": "須_Forward___鷗",
  "horizontal": "須_Horizontal____鷗",
  "vertical": "須_Vertical___鷗",
  "resultsTitle": "須_Results___鷗",
  "publishERGBtn": "須_Publish___鷗",
  "ERGLayerName": "須_Published ERG Layer Name________鷗",
  "invalidERGLayerName": "須_Layer name must only contain alpha-numeric characters and underscores______________________鷗",
  "missingERGLayerName": "須_You must enter a name for the ERG___________鷗",
  "publishingFailedLayerExists": "須_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________鷗.",
  "checkService": "須_Check Service: {0}______鷗",
  "createService": "須_Create Service: {0}_______鷗",
  "unableToCreate": "須_Unable to create: {0}_______鷗",
  "addToDefinition": "須_Add to definition: {0}________鷗",
  "successfullyPublished": "須_Successfully published web layer{0}Manage the web layer__________________鷗",
  "userRole": "須_Unable to create service because user does not have permissions____________________鷗",
  "transparency": "須_Transparency_____鷗",
  "outline": "須_Outline___鷗",
  "fill": "須_Fill (Color only applies when style set to solid)________________鷗",
  "createERGBtn": "須_Create Zones_____鷗",
  "clearERGBtn": "須_Clear___鷗",
  "labelFormat": "須_Label Format_____鷗",
  "helpIconTooltip": "須_The threshold between small and large spill sizes are:\nLiquids - 55 gallons (208 liters)\nSolids - 60 pounds (300 kilograms)_______________________________________鷗",
  "cellWidth": "須_Cell Width (x)_____鷗",
  "cellHeight": "須_Cell Height (y)______鷗",
  "invalidNumberMessage": "須_The value entered is not valid__________鷗",
  "invalidRangeMessage": "須_Value must be greater than 0_________鷗",
  "gridAngleInvalidRangeMessage": "須_Value must be between -89.9 and 89.9____________鷗",
  "formatIconTooltip": "須_Format Input_____鷗",
  "setCoordFormat": "須_Set Coordinate Format String_________鷗",
  "prefixNumbers": "須_Add '+/-' prefix to positive and negative numbers________________鷗",
  "cancelBtn": "須_Cancel___鷗",
  "applyBtn": "須_Apply___鷗",
  "comfirmInputNotation": "須_Confirm Input Notation________鷗",
  "notationsMatch": "須_notations match your input please confirm which you would like to use______________________鷗:",
  "missingLayerNameMessage": "須_You must enter a valid layer name before you can publish__________________鷗",
  "parseCoordinatesError": "須_Unable to parse coordinates. Please check your input_________________鷗.",
  "DD": "須_DD__鷗",
  "DDM": "須_DDM__鷗",
  "DMS": "須_DMS__鷗",
  "DDRev": "須_DDRev___鷗",
  "DDMRev": "須_DDMRev___鷗",
  "DMSRev": "須_DMSRev___鷗",
  "USNG": "須_USNG__鷗",
  "MGRS": "須_MGRS__鷗",
  "UTM_H": "須_UTM (H)___鷗",
  "UTM": "須_UTM__鷗",
  "GARS": "須_GARS__鷗",
  "GEOREF": "須_GEOREF___鷗",
  "DDLatLongNotation": "須_Decimal Degrees - Latitude/Longitude____________鷗",
  "DDLongLatNotation": "須_Decimal Degrees  - Longitude/Latitude____________鷗",
  "DDMLatLongNotation": "須_Degrees Decimal Minutes - Latitude/Longitude______________鷗",
  "DDMLongLatNotation": "須_Degrees Decimal Minutes - Longitude/Latitude______________鷗",
  "DMSLatLongNotation": "須_Degrees Minutes Seconds - Latitude/Longitude______________鷗",
  "DMSLongLatNotation": "須_Degrees Minutes Seconds - Longitude/Latitude______________鷗",
  "GARSNotation": "須_GARS__鷗",
  "GEOREFNotation": "須_GEOREF___鷗",
  "MGRSNotation": "須_MGRS__鷗",
  "USNGNotation": "須_USNG__鷗",
  "UTMBandNotation": "須_UTM - Band Letter______鷗",
  "UTMHemNotation": "須_UTM - Hemisphere (N/S)________鷗"
});