define({
  "symbolologyTabLabel": "ng_Configure Symbology_______ny",
  "facilitiesDescription": "ng_Facility Layers______ny",
  "demographicsDescription": "ng_Demographics Layer______ny",
  "settingsTitle": "ng_Settings___ny",
  "spillLocationLabel": "ng_Spill Location_____ny",
  "spillLocationButtonLabel": "ng_Configure Spill Location Settings___________ny",
  "IISettingsLabel": "ng_Initial Isolation Zone________ny",
  "IIButtonLabel": "ng_Configure Initial Isolation Settings____________ny",
  "PASettingsLabel": "ng_Protective Action Zone________ny",
  "PAButtonLabel": "ng_Configure Protective Action Settings____________ny",
  "downwindSettingsLabel": "ng_Down Wind Zone_____ny",
  "downwindButtonLabel": "ng_Configure Down Wind Settings_________ny",
  "fireSettingsLabel": "ng_Fire Isolation Zone_______ny",
  "fireButtonLabel": "ng_Configure Fire Isolation Settings___________ny",
  "bleveSettingsLabel": "ng_BLEVE Isolation Zone_______ny",
  "bleveButtonLabel": "ng_Configure BLEVE Settings________ny",
  "transparency": "ng_Transparency_____ny",
  "outline": "ng_Outline___ny",
  "fill": "ng_Fill (Color only applies when style set to solid)________________ny",
  "outlineStyle": "ng_Outline Style_____ny",
  "dash": "ng_Dash__ny",
  "dashdot": "ng_Dash Dot___ny",
  "dashdotdot": "ng_Dash Dot Dot_____ny",
  "dot": "ng_Dot__ny",
  "longdash": "ng_Long Dash____ny",
  "longdashdot": "ng_Long Dash Dot_____ny",
  "null": "ng_Null__ny",
  "shortdash": "ng_Short Dash____ny",
  "shortdashdot": "ng_Short Dash Dot_____ny",
  "shortdashdotdot": "ng_Short Dash Dot Dot______ny",
  "shortdot": "ng_Short Dot____ny",
  "solid": "ng_Solid___ny",
  "fillStyle": "ng_Fill Style____ny",
  "backward": "ng_Backward___ny",
  "cross": "ng_Cross___ny",
  "diagonal": "ng_Diagonal___ny",
  "forward": "ng_Forward___ny",
  "horizontal": "ng_Horizontal____ny",
  "vertical": "ng_Vertical___ny"
});