define({
  "_widgetLabel": "ก้_Emergency Response Guide________ษฺ",
  "ergMainPageTitle": "ก้_Based on the Emergency Response Guidebook 2016_______________ษฺ",
  "coordInputLabelStart": "ก้_Spill Location (DD)_______ษฺ",
  "coordInputLabel": "ก้_Spill Location_____ษฺ",
  "addPointToolTip": "ก้_Add Spill Location______ษฺ",
  "drawPointToolTip": "ก้_Click to add spill location_________ษฺ",
  "material": "ก้_Material___ษฺ",
  "materialPlaceholder": "ก้_Start typing to search for a material____________ษฺ",
  "table3Message": "ก้_The material you have selected requires additional information if you are dealing with a large spill.\n\nPlease ensure you have the correct values selected for wind speed and transport container____________________________________________________________ษฺ.",
  "table2Message": "ก้_The material you have selected may produces a large amount of Toxic Inhalation Hazard gases when spilled in water.\n\nYou may want to consider using the following material(s):\n\n_______________________________________________________ษฺ",
  "spillSize": "ก้_Spill Size____ษฺ",
  "small": "ก้_Small___ษฺ",
  "large": "ก้_Large___ษฺ",
  "fireLabel": "ก้_Show Fire Isolation Zone________ษฺ",
  "weatherLabel": "ก้_Current Weather at Spill Location___________ษฺ",
  "weatherIntialText": "ก้_<br />Updated once a spill location has been idenitified__________________ษฺ",
  "temperature": "ก้_Temperature____ษฺ",
  "wind": "ก้_Wind__ษฺ",
  "c": "ก้_C_ษฺ",
  "f": "ก้_F_ษฺ",
  "weatherErrorMessage": "ก้_Weather info not obtained. Update Wind Speed and Time of Spill values manually________________________ษฺ",
  "windDirection": "ก้_Wind Direction (blowing to)_________ษฺ",
  "timeOfSpill": "ก้_Time of Spill_____ษฺ",
  "day": "ก้_Day__ษฺ",
  "night": "ก้_Night___ษฺ",
  "windSpeed": "ก้_Wind Speed____ษฺ",
  "low": "ก้_Low__ษฺ",
  "moderate": "ก้_Moderate___ษฺ",
  "high": "ก้_High__ษฺ",
  "transportContainer": "ก้_Transport Container_______ษฺ",
  "rail": "ก้_Rail tank car_____ษฺ",
  "semi": "ก้_Highway tank truck or trailer__________ษฺ",
  "mton": "ก้_Multiple ton cylinders________ษฺ",
  "ston": "ก้_Multiple small cylinders or single ton cylinder_______________ษฺ",
  "ag": "ก้_Agricultural nurse tank________ษฺ",
  "msm": "ก้_Multiple small cylinders________ษฺ",
  "bleveLabel": "ก้_Show BLEVE Isolation Zone_________ษฺ",
  "capacity": "ก้_Container Capacity (litres)_________ษฺ",
  "bleveMessage": "ก้_For the material you have selected an additional evacuation distance can be shown for BLEVE.\n\nTo enable this, set the Show BLEVE Isolation Zone toggle to on and select the appropiate container capacity______________________________________________________________ษฺ.",
  "noPAZoneMessage": "ก้_There are no Protective Action distances for this material. Only the Initial Isolation and evacuation zones has been calculated_______________________________________ษฺ",
  "settingsTitle": "ก้_Settings___ษฺ",
  "spillLocationLabel": "ก้_Spill Location_____ษฺ",
  "spillLocationButtonLabel": "ก้_Configure Spill Location Settings___________ษฺ",
  "IISettingsLabel": "ก้_Initial Isolation Zone________ษฺ",
  "IIButtonLabel": "ก้_Configure Initial Isolation Settings____________ษฺ",
  "PASettingsLabel": "ก้_Protective Action Zone________ษฺ",
  "PAButtonLabel": "ก้_Configure Protective Action Settings____________ษฺ",
  "downwindSettingsLabel": "ก้_Down Wind Zone_____ษฺ",
  "downwindButtonLabel": "ก้_Configure Down Wind Settings_________ษฺ",
  "fireSettingsLabel": "ก้_Fire Isolation Zone_______ษฺ",
  "fireButtonLabel": "ก้_Configure Fire Isolation Settings___________ษฺ",
  "bleveSettingsLabel": "ก้_BLEVE Isolation Zone_______ษฺ",
  "bleveButtonLabel": "ก้_Configure BLEVE Settings________ษฺ",
  "outlineStyle": "ก้_Outline Style_____ษฺ",
  "dash": "ก้_Dash__ษฺ",
  "dashdot": "ก้_Dash Dot___ษฺ",
  "dashdotdot": "ก้_Dash Dot Dot_____ษฺ",
  "dot": "ก้_Dot__ษฺ",
  "longdash": "ก้_Long Dash____ษฺ",
  "longdashdot": "ก้_Long Dash Dot_____ษฺ",
  "null": "ก้_Null__ษฺ",
  "shortdash": "ก้_Short Dash____ษฺ",
  "shortdashdot": "ก้_Short Dash Dot_____ษฺ",
  "shortdashdotdot": "ก้_Short Dash Dot Dot______ษฺ",
  "shortdot": "ก้_Short Dot____ษฺ",
  "solid": "ก้_Solid___ษฺ",
  "fillStyle": "ก้_Fill Style____ษฺ",
  "backward": "ก้_Backward___ษฺ",
  "cross": "ก้_Cross___ษฺ",
  "diagonal": "ก้_Diagonal___ษฺ",
  "forward": "ก้_Forward___ษฺ",
  "horizontal": "ก้_Horizontal____ษฺ",
  "vertical": "ก้_Vertical___ษฺ",
  "resultsTitle": "ก้_Results___ษฺ",
  "publishERGBtn": "ก้_Publish___ษฺ",
  "ERGLayerName": "ก้_Published ERG Layer Name________ษฺ",
  "invalidERGLayerName": "ก้_Layer name must only contain alpha-numeric characters and underscores______________________ษฺ",
  "missingERGLayerName": "ก้_You must enter a name for the ERG___________ษฺ",
  "publishingFailedLayerExists": "ก้_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________ษฺ.",
  "checkService": "ก้_Check Service: {0}______ษฺ",
  "createService": "ก้_Create Service: {0}_______ษฺ",
  "unableToCreate": "ก้_Unable to create: {0}_______ษฺ",
  "addToDefinition": "ก้_Add to definition: {0}________ษฺ",
  "successfullyPublished": "ก้_Successfully published web layer{0}Manage the web layer__________________ษฺ",
  "userRole": "ก้_Unable to create service because user does not have permissions____________________ษฺ",
  "transparency": "ก้_Transparency_____ษฺ",
  "outline": "ก้_Outline___ษฺ",
  "fill": "ก้_Fill (Color only applies when style set to solid)________________ษฺ",
  "createERGBtn": "ก้_Create Zones_____ษฺ",
  "clearERGBtn": "ก้_Clear___ษฺ",
  "labelFormat": "ก้_Label Format_____ษฺ",
  "helpIconTooltip": "ก้_The threshold between small and large spill sizes are:\nLiquids - 55 gallons (208 liters)\nSolids - 60 pounds (300 kilograms)_______________________________________ษฺ",
  "cellWidth": "ก้_Cell Width (x)_____ษฺ",
  "cellHeight": "ก้_Cell Height (y)______ษฺ",
  "invalidNumberMessage": "ก้_The value entered is not valid__________ษฺ",
  "invalidRangeMessage": "ก้_Value must be greater than 0_________ษฺ",
  "gridAngleInvalidRangeMessage": "ก้_Value must be between -89.9 and 89.9____________ษฺ",
  "formatIconTooltip": "ก้_Format Input_____ษฺ",
  "setCoordFormat": "ก้_Set Coordinate Format String_________ษฺ",
  "prefixNumbers": "ก้_Add '+/-' prefix to positive and negative numbers________________ษฺ",
  "cancelBtn": "ก้_Cancel___ษฺ",
  "applyBtn": "ก้_Apply___ษฺ",
  "comfirmInputNotation": "ก้_Confirm Input Notation________ษฺ",
  "notationsMatch": "ก้_notations match your input please confirm which you would like to use______________________ษฺ:",
  "missingLayerNameMessage": "ก้_You must enter a valid layer name before you can publish__________________ษฺ",
  "parseCoordinatesError": "ก้_Unable to parse coordinates. Please check your input_________________ษฺ.",
  "DD": "ก้_DD__ษฺ",
  "DDM": "ก้_DDM__ษฺ",
  "DMS": "ก้_DMS__ษฺ",
  "DDRev": "ก้_DDRev___ษฺ",
  "DDMRev": "ก้_DDMRev___ษฺ",
  "DMSRev": "ก้_DMSRev___ษฺ",
  "USNG": "ก้_USNG__ษฺ",
  "MGRS": "ก้_MGRS__ษฺ",
  "UTM_H": "ก้_UTM (H)___ษฺ",
  "UTM": "ก้_UTM__ษฺ",
  "GARS": "ก้_GARS__ษฺ",
  "GEOREF": "ก้_GEOREF___ษฺ",
  "DDLatLongNotation": "ก้_Decimal Degrees - Latitude/Longitude____________ษฺ",
  "DDLongLatNotation": "ก้_Decimal Degrees  - Longitude/Latitude____________ษฺ",
  "DDMLatLongNotation": "ก้_Degrees Decimal Minutes - Latitude/Longitude______________ษฺ",
  "DDMLongLatNotation": "ก้_Degrees Decimal Minutes - Longitude/Latitude______________ษฺ",
  "DMSLatLongNotation": "ก้_Degrees Minutes Seconds - Latitude/Longitude______________ษฺ",
  "DMSLongLatNotation": "ก้_Degrees Minutes Seconds - Longitude/Latitude______________ษฺ",
  "GARSNotation": "ก้_GARS__ษฺ",
  "GEOREFNotation": "ก้_GEOREF___ษฺ",
  "MGRSNotation": "ก้_MGRS__ษฺ",
  "USNGNotation": "ก้_USNG__ษฺ",
  "UTMBandNotation": "ก้_UTM - Band Letter______ษฺ",
  "UTMHemNotation": "ก้_UTM - Hemisphere (N/S)________ษฺ"
});