define({
  "_widgetLabel": "ł_Emergency Response Guide________ą",
  "ergMainPageTitle": "ł_Based on the Emergency Response Guidebook 2016_______________ą",
  "coordInputLabelStart": "ł_Spill Location (DD)_______ą",
  "coordInputLabel": "ł_Spill Location_____ą",
  "addPointToolTip": "ł_Add Spill Location______ą",
  "drawPointToolTip": "ł_Click to add spill location_________ą",
  "material": "ł_Material___ą",
  "materialPlaceholder": "ł_Start typing to search for a material____________ą",
  "table3Message": "ł_The material you have selected requires additional information if you are dealing with a large spill.\n\nPlease ensure you have the correct values selected for wind speed and transport container____________________________________________________________ą.",
  "table2Message": "ł_The material you have selected may produces a large amount of Toxic Inhalation Hazard gases when spilled in water.\n\nYou may want to consider using the following material(s):\n\n_______________________________________________________ą",
  "spillSize": "ł_Spill Size____ą",
  "small": "ł_Small___ą",
  "large": "ł_Large___ą",
  "fireLabel": "ł_Show Fire Isolation Zone________ą",
  "weatherLabel": "ł_Current Weather at Spill Location___________ą",
  "weatherIntialText": "ł_<br />Updated once a spill location has been idenitified__________________ą",
  "temperature": "ł_Temperature____ą",
  "wind": "ł_Wind__ą",
  "c": "ł_C_ą",
  "f": "ł_F_ą",
  "weatherErrorMessage": "ł_Weather info not obtained. Update Wind Speed and Time of Spill values manually________________________ą",
  "windDirection": "ł_Wind Direction (blowing to)_________ą",
  "timeOfSpill": "ł_Time of Spill_____ą",
  "day": "ł_Day__ą",
  "night": "ł_Night___ą",
  "windSpeed": "ł_Wind Speed____ą",
  "low": "ł_Low__ą",
  "moderate": "ł_Moderate___ą",
  "high": "ł_High__ą",
  "transportContainer": "ł_Transport Container_______ą",
  "rail": "ł_Rail tank car_____ą",
  "semi": "ł_Highway tank truck or trailer__________ą",
  "mton": "ł_Multiple ton cylinders________ą",
  "ston": "ł_Multiple small cylinders or single ton cylinder_______________ą",
  "ag": "ł_Agricultural nurse tank________ą",
  "msm": "ł_Multiple small cylinders________ą",
  "bleveLabel": "ł_Show BLEVE Isolation Zone_________ą",
  "capacity": "ł_Container Capacity (litres)_________ą",
  "bleveMessage": "ł_For the material you have selected an additional evacuation distance can be shown for BLEVE.\n\nTo enable this, set the Show BLEVE Isolation Zone toggle to on and select the appropiate container capacity______________________________________________________________ą.",
  "noPAZoneMessage": "ł_There are no Protective Action distances for this material. Only the Initial Isolation and evacuation zones has been calculated_______________________________________ą",
  "settingsTitle": "ł_Settings___ą",
  "spillLocationLabel": "ł_Spill Location_____ą",
  "spillLocationButtonLabel": "ł_Configure Spill Location Settings___________ą",
  "IISettingsLabel": "ł_Initial Isolation Zone________ą",
  "IIButtonLabel": "ł_Configure Initial Isolation Settings____________ą",
  "PASettingsLabel": "ł_Protective Action Zone________ą",
  "PAButtonLabel": "ł_Configure Protective Action Settings____________ą",
  "downwindSettingsLabel": "ł_Down Wind Zone_____ą",
  "downwindButtonLabel": "ł_Configure Down Wind Settings_________ą",
  "fireSettingsLabel": "ł_Fire Isolation Zone_______ą",
  "fireButtonLabel": "ł_Configure Fire Isolation Settings___________ą",
  "bleveSettingsLabel": "ł_BLEVE Isolation Zone_______ą",
  "bleveButtonLabel": "ł_Configure BLEVE Settings________ą",
  "outlineStyle": "ł_Outline Style_____ą",
  "dash": "ł_Dash__ą",
  "dashdot": "ł_Dash Dot___ą",
  "dashdotdot": "ł_Dash Dot Dot_____ą",
  "dot": "ł_Dot__ą",
  "longdash": "ł_Long Dash____ą",
  "longdashdot": "ł_Long Dash Dot_____ą",
  "null": "ł_Null__ą",
  "shortdash": "ł_Short Dash____ą",
  "shortdashdot": "ł_Short Dash Dot_____ą",
  "shortdashdotdot": "ł_Short Dash Dot Dot______ą",
  "shortdot": "ł_Short Dot____ą",
  "solid": "ł_Solid___ą",
  "fillStyle": "ł_Fill Style____ą",
  "backward": "ł_Backward___ą",
  "cross": "ł_Cross___ą",
  "diagonal": "ł_Diagonal___ą",
  "forward": "ł_Forward___ą",
  "horizontal": "ł_Horizontal____ą",
  "vertical": "ł_Vertical___ą",
  "resultsTitle": "ł_Results___ą",
  "publishERGBtn": "ł_Publish___ą",
  "ERGLayerName": "ł_Published ERG Layer Name________ą",
  "invalidERGLayerName": "ł_Layer name must only contain alpha-numeric characters and underscores______________________ą",
  "missingERGLayerName": "ł_You must enter a name for the ERG___________ą",
  "publishingFailedLayerExists": "ł_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________ą.",
  "checkService": "ł_Check Service: {0}______ą",
  "createService": "ł_Create Service: {0}_______ą",
  "unableToCreate": "ł_Unable to create: {0}_______ą",
  "addToDefinition": "ł_Add to definition: {0}________ą",
  "successfullyPublished": "ł_Successfully published web layer{0}Manage the web layer__________________ą",
  "userRole": "ł_Unable to create service because user does not have permissions____________________ą",
  "transparency": "ł_Transparency_____ą",
  "outline": "ł_Outline___ą",
  "fill": "ł_Fill (Color only applies when style set to solid)________________ą",
  "createERGBtn": "ł_Create Zones_____ą",
  "clearERGBtn": "ł_Clear___ą",
  "labelFormat": "ł_Label Format_____ą",
  "helpIconTooltip": "ł_The threshold between small and large spill sizes are:\nLiquids - 55 gallons (208 liters)\nSolids - 60 pounds (300 kilograms)_______________________________________ą",
  "cellWidth": "ł_Cell Width (x)_____ą",
  "cellHeight": "ł_Cell Height (y)______ą",
  "invalidNumberMessage": "ł_The value entered is not valid__________ą",
  "invalidRangeMessage": "ł_Value must be greater than 0_________ą",
  "gridAngleInvalidRangeMessage": "ł_Value must be between -89.9 and 89.9____________ą",
  "formatIconTooltip": "ł_Format Input_____ą",
  "setCoordFormat": "ł_Set Coordinate Format String_________ą",
  "prefixNumbers": "ł_Add '+/-' prefix to positive and negative numbers________________ą",
  "cancelBtn": "ł_Cancel___ą",
  "applyBtn": "ł_Apply___ą",
  "comfirmInputNotation": "ł_Confirm Input Notation________ą",
  "notationsMatch": "ł_notations match your input please confirm which you would like to use______________________ą:",
  "missingLayerNameMessage": "ł_You must enter a valid layer name before you can publish__________________ą",
  "parseCoordinatesError": "ł_Unable to parse coordinates. Please check your input_________________ą.",
  "DD": "ł_DD__ą",
  "DDM": "ł_DDM__ą",
  "DMS": "ł_DMS__ą",
  "DDRev": "ł_DDRev___ą",
  "DDMRev": "ł_DDMRev___ą",
  "DMSRev": "ł_DMSRev___ą",
  "USNG": "ł_USNG__ą",
  "MGRS": "ł_MGRS__ą",
  "UTM_H": "ł_UTM (H)___ą",
  "UTM": "ł_UTM__ą",
  "GARS": "ł_GARS__ą",
  "GEOREF": "ł_GEOREF___ą",
  "DDLatLongNotation": "ł_Decimal Degrees - Latitude/Longitude____________ą",
  "DDLongLatNotation": "ł_Decimal Degrees  - Longitude/Latitude____________ą",
  "DDMLatLongNotation": "ł_Degrees Decimal Minutes - Latitude/Longitude______________ą",
  "DDMLongLatNotation": "ł_Degrees Decimal Minutes - Longitude/Latitude______________ą",
  "DMSLatLongNotation": "ł_Degrees Minutes Seconds - Latitude/Longitude______________ą",
  "DMSLongLatNotation": "ł_Degrees Minutes Seconds - Longitude/Latitude______________ą",
  "GARSNotation": "ł_GARS__ą",
  "GEOREFNotation": "ł_GEOREF___ą",
  "MGRSNotation": "ł_MGRS__ą",
  "USNGNotation": "ł_USNG__ą",
  "UTMBandNotation": "ł_UTM - Band Letter______ą",
  "UTMHemNotation": "ł_UTM - Hemisphere (N/S)________ą"
});