define({
  "_widgetLabel": "ng_Emergency Response Guide________ny",
  "ergMainPageTitle": "ng_Based on the Emergency Response Guidebook 2016_______________ny",
  "coordInputLabelStart": "ng_Spill Location (DD)_______ny",
  "coordInputLabel": "ng_Spill Location_____ny",
  "addPointToolTip": "ng_Add Spill Location______ny",
  "drawPointToolTip": "ng_Click to add spill location_________ny",
  "material": "ng_Material___ny",
  "materialPlaceholder": "ng_Start typing to search for a material____________ny",
  "table3Message": "ng_The material you have selected requires additional information if you are dealing with a large spill.\n\nPlease ensure you have the correct values selected for wind speed and transport container____________________________________________________________ny.",
  "table2Message": "ng_The material you have selected may produces a large amount of Toxic Inhalation Hazard gases when spilled in water.\n\nYou may want to consider using the following material(s):\n\n_______________________________________________________ny",
  "spillSize": "ng_Spill Size____ny",
  "small": "ng_Small___ny",
  "large": "ng_Large___ny",
  "fireLabel": "ng_Show Fire Isolation Zone________ny",
  "weatherLabel": "ng_Current Weather at Spill Location___________ny",
  "weatherIntialText": "ng_<br />Updated once a spill location has been idenitified__________________ny",
  "temperature": "ng_Temperature____ny",
  "wind": "ng_Wind__ny",
  "c": "ng_C_ny",
  "f": "ng_F_ny",
  "weatherErrorMessage": "ng_Weather info not obtained. Update Wind Speed and Time of Spill values manually________________________ny",
  "windDirection": "ng_Wind Direction (blowing to)_________ny",
  "timeOfSpill": "ng_Time of Spill_____ny",
  "day": "ng_Day__ny",
  "night": "ng_Night___ny",
  "windSpeed": "ng_Wind Speed____ny",
  "low": "ng_Low__ny",
  "moderate": "ng_Moderate___ny",
  "high": "ng_High__ny",
  "transportContainer": "ng_Transport Container_______ny",
  "rail": "ng_Rail tank car_____ny",
  "semi": "ng_Highway tank truck or trailer__________ny",
  "mton": "ng_Multiple ton cylinders________ny",
  "ston": "ng_Multiple small cylinders or single ton cylinder_______________ny",
  "ag": "ng_Agricultural nurse tank________ny",
  "msm": "ng_Multiple small cylinders________ny",
  "bleveLabel": "ng_Show BLEVE Isolation Zone_________ny",
  "capacity": "ng_Container Capacity (litres)_________ny",
  "bleveMessage": "ng_For the material you have selected an additional evacuation distance can be shown for BLEVE.\n\nTo enable this, set the Show BLEVE Isolation Zone toggle to on and select the appropiate container capacity______________________________________________________________ny.",
  "noPAZoneMessage": "ng_There are no Protective Action distances for this material. Only the Initial Isolation and evacuation zones has been calculated_______________________________________ny",
  "settingsTitle": "ng_Settings___ny",
  "spillLocationLabel": "ng_Spill Location_____ny",
  "spillLocationButtonLabel": "ng_Configure Spill Location Settings___________ny",
  "IISettingsLabel": "ng_Initial Isolation Zone________ny",
  "IIButtonLabel": "ng_Configure Initial Isolation Settings____________ny",
  "PASettingsLabel": "ng_Protective Action Zone________ny",
  "PAButtonLabel": "ng_Configure Protective Action Settings____________ny",
  "downwindSettingsLabel": "ng_Down Wind Zone_____ny",
  "downwindButtonLabel": "ng_Configure Down Wind Settings_________ny",
  "fireSettingsLabel": "ng_Fire Isolation Zone_______ny",
  "fireButtonLabel": "ng_Configure Fire Isolation Settings___________ny",
  "bleveSettingsLabel": "ng_BLEVE Isolation Zone_______ny",
  "bleveButtonLabel": "ng_Configure BLEVE Settings________ny",
  "outlineStyle": "ng_Outline Style_____ny",
  "dash": "ng_Dash__ny",
  "dashdot": "ng_Dash Dot___ny",
  "dashdotdot": "ng_Dash Dot Dot_____ny",
  "dot": "ng_Dot__ny",
  "longdash": "ng_Long Dash____ny",
  "longdashdot": "ng_Long Dash Dot_____ny",
  "null": "ng_Null__ny",
  "shortdash": "ng_Short Dash____ny",
  "shortdashdot": "ng_Short Dash Dot_____ny",
  "shortdashdotdot": "ng_Short Dash Dot Dot______ny",
  "shortdot": "ng_Short Dot____ny",
  "solid": "ng_Solid___ny",
  "fillStyle": "ng_Fill Style____ny",
  "backward": "ng_Backward___ny",
  "cross": "ng_Cross___ny",
  "diagonal": "ng_Diagonal___ny",
  "forward": "ng_Forward___ny",
  "horizontal": "ng_Horizontal____ny",
  "vertical": "ng_Vertical___ny",
  "resultsTitle": "ng_Results___ny",
  "publishERGBtn": "ng_Publish___ny",
  "ERGLayerName": "ng_Published ERG Layer Name________ny",
  "invalidERGLayerName": "ng_Layer name must only contain alpha-numeric characters and underscores______________________ny",
  "missingERGLayerName": "ng_You must enter a name for the ERG___________ny",
  "publishingFailedLayerExists": "ng_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________ny.",
  "checkService": "ng_Check Service: {0}______ny",
  "createService": "ng_Create Service: {0}_______ny",
  "unableToCreate": "ng_Unable to create: {0}_______ny",
  "addToDefinition": "ng_Add to definition: {0}________ny",
  "successfullyPublished": "ng_Successfully published web layer{0}Manage the web layer__________________ny",
  "userRole": "ng_Unable to create service because user does not have permissions____________________ny",
  "transparency": "ng_Transparency_____ny",
  "outline": "ng_Outline___ny",
  "fill": "ng_Fill (Color only applies when style set to solid)________________ny",
  "createERGBtn": "ng_Create Zones_____ny",
  "clearERGBtn": "ng_Clear___ny",
  "labelFormat": "ng_Label Format_____ny",
  "helpIconTooltip": "ng_The threshold between small and large spill sizes are:\nLiquids - 55 gallons (208 liters)\nSolids - 60 pounds (300 kilograms)_______________________________________ny",
  "cellWidth": "ng_Cell Width (x)_____ny",
  "cellHeight": "ng_Cell Height (y)______ny",
  "invalidNumberMessage": "ng_The value entered is not valid__________ny",
  "invalidRangeMessage": "ng_Value must be greater than 0_________ny",
  "gridAngleInvalidRangeMessage": "ng_Value must be between -89.9 and 89.9____________ny",
  "formatIconTooltip": "ng_Format Input_____ny",
  "setCoordFormat": "ng_Set Coordinate Format String_________ny",
  "prefixNumbers": "ng_Add '+/-' prefix to positive and negative numbers________________ny",
  "cancelBtn": "ng_Cancel___ny",
  "applyBtn": "ng_Apply___ny",
  "comfirmInputNotation": "ng_Confirm Input Notation________ny",
  "notationsMatch": "ng_notations match your input please confirm which you would like to use______________________ny:",
  "missingLayerNameMessage": "ng_You must enter a valid layer name before you can publish__________________ny",
  "parseCoordinatesError": "ng_Unable to parse coordinates. Please check your input_________________ny.",
  "DD": "ng_DD__ny",
  "DDM": "ng_DDM__ny",
  "DMS": "ng_DMS__ny",
  "DDRev": "ng_DDRev___ny",
  "DDMRev": "ng_DDMRev___ny",
  "DMSRev": "ng_DMSRev___ny",
  "USNG": "ng_USNG__ny",
  "MGRS": "ng_MGRS__ny",
  "UTM_H": "ng_UTM (H)___ny",
  "UTM": "ng_UTM__ny",
  "GARS": "ng_GARS__ny",
  "GEOREF": "ng_GEOREF___ny",
  "DDLatLongNotation": "ng_Decimal Degrees - Latitude/Longitude____________ny",
  "DDLongLatNotation": "ng_Decimal Degrees  - Longitude/Latitude____________ny",
  "DDMLatLongNotation": "ng_Degrees Decimal Minutes - Latitude/Longitude______________ny",
  "DDMLongLatNotation": "ng_Degrees Decimal Minutes - Longitude/Latitude______________ny",
  "DMSLatLongNotation": "ng_Degrees Minutes Seconds - Latitude/Longitude______________ny",
  "DMSLongLatNotation": "ng_Degrees Minutes Seconds - Longitude/Latitude______________ny",
  "GARSNotation": "ng_GARS__ny",
  "GEOREFNotation": "ng_GEOREF___ny",
  "MGRSNotation": "ng_MGRS__ny",
  "USNGNotation": "ng_USNG__ny",
  "UTMBandNotation": "ng_UTM - Band Letter______ny",
  "UTMHemNotation": "ng_UTM - Hemisphere (N/S)________ny"
});