define({
  "_widgetLabel": "Į_Emergency Response Guide________š",
  "ergMainPageTitle": "Į_Based on the Emergency Response Guidebook 2016_______________š",
  "coordInputLabelStart": "Į_Spill Location (DD)_______š",
  "coordInputLabel": "Į_Spill Location_____š",
  "addPointToolTip": "Į_Add Spill Location______š",
  "drawPointToolTip": "Į_Click to add spill location_________š",
  "material": "Į_Material___š",
  "materialPlaceholder": "Į_Start typing to search for a material____________š",
  "table3Message": "Į_The material you have selected requires additional information if you are dealing with a large spill.\n\nPlease ensure you have the correct values selected for wind speed and transport container____________________________________________________________š.",
  "table2Message": "Į_The material you have selected may produces a large amount of Toxic Inhalation Hazard gases when spilled in water.\n\nYou may want to consider using the following material(s):\n\n_______________________________________________________š",
  "spillSize": "Į_Spill Size____š",
  "small": "Į_Small___š",
  "large": "Į_Large___š",
  "fireLabel": "Į_Show Fire Isolation Zone________š",
  "weatherLabel": "Į_Current Weather at Spill Location___________š",
  "weatherIntialText": "Į_<br />Updated once a spill location has been idenitified__________________š",
  "temperature": "Į_Temperature____š",
  "wind": "Į_Wind__š",
  "c": "Į_C_š",
  "f": "Į_F_š",
  "weatherErrorMessage": "Į_Weather info not obtained. Update Wind Speed and Time of Spill values manually________________________š",
  "windDirection": "Į_Wind Direction (blowing to)_________š",
  "timeOfSpill": "Į_Time of Spill_____š",
  "day": "Į_Day__š",
  "night": "Į_Night___š",
  "windSpeed": "Į_Wind Speed____š",
  "low": "Į_Low__š",
  "moderate": "Į_Moderate___š",
  "high": "Į_High__š",
  "transportContainer": "Į_Transport Container_______š",
  "rail": "Į_Rail tank car_____š",
  "semi": "Į_Highway tank truck or trailer__________š",
  "mton": "Į_Multiple ton cylinders________š",
  "ston": "Į_Multiple small cylinders or single ton cylinder_______________š",
  "ag": "Į_Agricultural nurse tank________š",
  "msm": "Į_Multiple small cylinders________š",
  "bleveLabel": "Į_Show BLEVE Isolation Zone_________š",
  "capacity": "Į_Container Capacity (litres)_________š",
  "bleveMessage": "Į_For the material you have selected an additional evacuation distance can be shown for BLEVE.\n\nTo enable this, set the Show BLEVE Isolation Zone toggle to on and select the appropiate container capacity______________________________________________________________š.",
  "noPAZoneMessage": "Į_There are no Protective Action distances for this material. Only the Initial Isolation and evacuation zones has been calculated_______________________________________š",
  "settingsTitle": "Į_Settings___š",
  "spillLocationLabel": "Į_Spill Location_____š",
  "spillLocationButtonLabel": "Į_Configure Spill Location Settings___________š",
  "IISettingsLabel": "Į_Initial Isolation Zone________š",
  "IIButtonLabel": "Į_Configure Initial Isolation Settings____________š",
  "PASettingsLabel": "Į_Protective Action Zone________š",
  "PAButtonLabel": "Į_Configure Protective Action Settings____________š",
  "downwindSettingsLabel": "Į_Down Wind Zone_____š",
  "downwindButtonLabel": "Į_Configure Down Wind Settings_________š",
  "fireSettingsLabel": "Į_Fire Isolation Zone_______š",
  "fireButtonLabel": "Į_Configure Fire Isolation Settings___________š",
  "bleveSettingsLabel": "Į_BLEVE Isolation Zone_______š",
  "bleveButtonLabel": "Į_Configure BLEVE Settings________š",
  "outlineStyle": "Į_Outline Style_____š",
  "dash": "Į_Dash__š",
  "dashdot": "Į_Dash Dot___š",
  "dashdotdot": "Į_Dash Dot Dot_____š",
  "dot": "Į_Dot__š",
  "longdash": "Į_Long Dash____š",
  "longdashdot": "Į_Long Dash Dot_____š",
  "null": "Į_Null__š",
  "shortdash": "Į_Short Dash____š",
  "shortdashdot": "Į_Short Dash Dot_____š",
  "shortdashdotdot": "Į_Short Dash Dot Dot______š",
  "shortdot": "Į_Short Dot____š",
  "solid": "Į_Solid___š",
  "fillStyle": "Į_Fill Style____š",
  "backward": "Į_Backward___š",
  "cross": "Į_Cross___š",
  "diagonal": "Į_Diagonal___š",
  "forward": "Į_Forward___š",
  "horizontal": "Į_Horizontal____š",
  "vertical": "Į_Vertical___š",
  "resultsTitle": "Į_Results___š",
  "publishERGBtn": "Į_Publish___š",
  "ERGLayerName": "Į_Published ERG Layer Name________š",
  "invalidERGLayerName": "Į_Layer name must only contain alpha-numeric characters and underscores______________________š",
  "missingERGLayerName": "Į_You must enter a name for the ERG___________š",
  "publishingFailedLayerExists": "Į_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________š.",
  "checkService": "Į_Check Service: {0}______š",
  "createService": "Į_Create Service: {0}_______š",
  "unableToCreate": "Į_Unable to create: {0}_______š",
  "addToDefinition": "Į_Add to definition: {0}________š",
  "successfullyPublished": "Į_Successfully published web layer{0}Manage the web layer__________________š",
  "userRole": "Į_Unable to create service because user does not have permissions____________________š",
  "transparency": "Į_Transparency_____š",
  "outline": "Į_Outline___š",
  "fill": "Į_Fill (Color only applies when style set to solid)________________š",
  "createERGBtn": "Į_Create Zones_____š",
  "clearERGBtn": "Į_Clear___š",
  "labelFormat": "Į_Label Format_____š",
  "helpIconTooltip": "Į_The threshold between small and large spill sizes are:\nLiquids - 55 gallons (208 liters)\nSolids - 60 pounds (300 kilograms)_______________________________________š",
  "cellWidth": "Į_Cell Width (x)_____š",
  "cellHeight": "Į_Cell Height (y)______š",
  "invalidNumberMessage": "Į_The value entered is not valid__________š",
  "invalidRangeMessage": "Į_Value must be greater than 0_________š",
  "gridAngleInvalidRangeMessage": "Į_Value must be between -89.9 and 89.9____________š",
  "formatIconTooltip": "Į_Format Input_____š",
  "setCoordFormat": "Į_Set Coordinate Format String_________š",
  "prefixNumbers": "Į_Add '+/-' prefix to positive and negative numbers________________š",
  "cancelBtn": "Į_Cancel___š",
  "applyBtn": "Į_Apply___š",
  "comfirmInputNotation": "Į_Confirm Input Notation________š",
  "notationsMatch": "Į_notations match your input please confirm which you would like to use______________________š:",
  "missingLayerNameMessage": "Į_You must enter a valid layer name before you can publish__________________š",
  "parseCoordinatesError": "Į_Unable to parse coordinates. Please check your input_________________š.",
  "DD": "Į_DD__š",
  "DDM": "Į_DDM__š",
  "DMS": "Į_DMS__š",
  "DDRev": "Į_DDRev___š",
  "DDMRev": "Į_DDMRev___š",
  "DMSRev": "Į_DMSRev___š",
  "USNG": "Į_USNG__š",
  "MGRS": "Į_MGRS__š",
  "UTM_H": "Į_UTM (H)___š",
  "UTM": "Į_UTM__š",
  "GARS": "Į_GARS__š",
  "GEOREF": "Į_GEOREF___š",
  "DDLatLongNotation": "Į_Decimal Degrees - Latitude/Longitude____________š",
  "DDLongLatNotation": "Į_Decimal Degrees  - Longitude/Latitude____________š",
  "DDMLatLongNotation": "Į_Degrees Decimal Minutes - Latitude/Longitude______________š",
  "DDMLongLatNotation": "Į_Degrees Decimal Minutes - Longitude/Latitude______________š",
  "DMSLatLongNotation": "Į_Degrees Minutes Seconds - Latitude/Longitude______________š",
  "DMSLongLatNotation": "Į_Degrees Minutes Seconds - Longitude/Latitude______________š",
  "GARSNotation": "Į_GARS__š",
  "GEOREFNotation": "Į_GEOREF___š",
  "MGRSNotation": "Į_MGRS__š",
  "USNGNotation": "Į_USNG__š",
  "UTMBandNotation": "Į_UTM - Band Letter______š",
  "UTMHemNotation": "Į_UTM - Hemisphere (N/S)________š"
});