define({
  "_widgetLabel": "Ж_Emergency Response Guide________Я",
  "ergMainPageTitle": "Ж_Based on the Emergency Response Guidebook 2016_______________Я",
  "coordInputLabelStart": "Ж_Spill Location (DD)_______Я",
  "coordInputLabel": "Ж_Spill Location_____Я",
  "addPointToolTip": "Ж_Add Spill Location______Я",
  "drawPointToolTip": "Ж_Click to add spill location_________Я",
  "material": "Ж_Material___Я",
  "materialPlaceholder": "Ж_Start typing to search for a material____________Я",
  "table3Message": "Ж_The material you have selected requires additional information if you are dealing with a large spill.\n\nPlease ensure you have the correct values selected for wind speed and transport container____________________________________________________________Я.",
  "table2Message": "Ж_The material you have selected may produces a large amount of Toxic Inhalation Hazard gases when spilled in water.\n\nYou may want to consider using the following material(s):\n\n_______________________________________________________Я",
  "spillSize": "Ж_Spill Size____Я",
  "small": "Ж_Small___Я",
  "large": "Ж_Large___Я",
  "fireLabel": "Ж_Show Fire Isolation Zone________Я",
  "weatherLabel": "Ж_Current Weather at Spill Location___________Я",
  "weatherIntialText": "Ж_<br />Updated once a spill location has been idenitified__________________Я",
  "temperature": "Ж_Temperature____Я",
  "wind": "Ж_Wind__Я",
  "c": "Ж_C_Я",
  "f": "Ж_F_Я",
  "weatherErrorMessage": "Ж_Weather info not obtained. Update Wind Speed and Time of Spill values manually________________________Я",
  "windDirection": "Ж_Wind Direction (blowing to)_________Я",
  "timeOfSpill": "Ж_Time of Spill_____Я",
  "day": "Ж_Day__Я",
  "night": "Ж_Night___Я",
  "windSpeed": "Ж_Wind Speed____Я",
  "low": "Ж_Low__Я",
  "moderate": "Ж_Moderate___Я",
  "high": "Ж_High__Я",
  "transportContainer": "Ж_Transport Container_______Я",
  "rail": "Ж_Rail tank car_____Я",
  "semi": "Ж_Highway tank truck or trailer__________Я",
  "mton": "Ж_Multiple ton cylinders________Я",
  "ston": "Ж_Multiple small cylinders or single ton cylinder_______________Я",
  "ag": "Ж_Agricultural nurse tank________Я",
  "msm": "Ж_Multiple small cylinders________Я",
  "bleveLabel": "Ж_Show BLEVE Isolation Zone_________Я",
  "capacity": "Ж_Container Capacity (litres)_________Я",
  "bleveMessage": "Ж_For the material you have selected an additional evacuation distance can be shown for BLEVE.\n\nTo enable this, set the Show BLEVE Isolation Zone toggle to on and select the appropiate container capacity______________________________________________________________Я.",
  "noPAZoneMessage": "Ж_There are no Protective Action distances for this material. Only the Initial Isolation and evacuation zones has been calculated_______________________________________Я",
  "settingsTitle": "Ж_Settings___Я",
  "spillLocationLabel": "Ж_Spill Location_____Я",
  "spillLocationButtonLabel": "Ж_Configure Spill Location Settings___________Я",
  "IISettingsLabel": "Ж_Initial Isolation Zone________Я",
  "IIButtonLabel": "Ж_Configure Initial Isolation Settings____________Я",
  "PASettingsLabel": "Ж_Protective Action Zone________Я",
  "PAButtonLabel": "Ж_Configure Protective Action Settings____________Я",
  "downwindSettingsLabel": "Ж_Down Wind Zone_____Я",
  "downwindButtonLabel": "Ж_Configure Down Wind Settings_________Я",
  "fireSettingsLabel": "Ж_Fire Isolation Zone_______Я",
  "fireButtonLabel": "Ж_Configure Fire Isolation Settings___________Я",
  "bleveSettingsLabel": "Ж_BLEVE Isolation Zone_______Я",
  "bleveButtonLabel": "Ж_Configure BLEVE Settings________Я",
  "outlineStyle": "Ж_Outline Style_____Я",
  "dash": "Ж_Dash__Я",
  "dashdot": "Ж_Dash Dot___Я",
  "dashdotdot": "Ж_Dash Dot Dot_____Я",
  "dot": "Ж_Dot__Я",
  "longdash": "Ж_Long Dash____Я",
  "longdashdot": "Ж_Long Dash Dot_____Я",
  "null": "Ж_Null__Я",
  "shortdash": "Ж_Short Dash____Я",
  "shortdashdot": "Ж_Short Dash Dot_____Я",
  "shortdashdotdot": "Ж_Short Dash Dot Dot______Я",
  "shortdot": "Ж_Short Dot____Я",
  "solid": "Ж_Solid___Я",
  "fillStyle": "Ж_Fill Style____Я",
  "backward": "Ж_Backward___Я",
  "cross": "Ж_Cross___Я",
  "diagonal": "Ж_Diagonal___Я",
  "forward": "Ж_Forward___Я",
  "horizontal": "Ж_Horizontal____Я",
  "vertical": "Ж_Vertical___Я",
  "resultsTitle": "Ж_Results___Я",
  "publishERGBtn": "Ж_Publish___Я",
  "ERGLayerName": "Ж_Published ERG Layer Name________Я",
  "invalidERGLayerName": "Ж_Layer name must only contain alpha-numeric characters and underscores______________________Я",
  "missingERGLayerName": "Ж_You must enter a name for the ERG___________Я",
  "publishingFailedLayerExists": "Ж_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________Я.",
  "checkService": "Ж_Check Service: {0}______Я",
  "createService": "Ж_Create Service: {0}_______Я",
  "unableToCreate": "Ж_Unable to create: {0}_______Я",
  "addToDefinition": "Ж_Add to definition: {0}________Я",
  "successfullyPublished": "Ж_Successfully published web layer{0}Manage the web layer__________________Я",
  "userRole": "Ж_Unable to create service because user does not have permissions____________________Я",
  "transparency": "Ж_Transparency_____Я",
  "outline": "Ж_Outline___Я",
  "fill": "Ж_Fill (Color only applies when style set to solid)________________Я",
  "createERGBtn": "Ж_Create Zones_____Я",
  "clearERGBtn": "Ж_Clear___Я",
  "labelFormat": "Ж_Label Format_____Я",
  "helpIconTooltip": "Ж_The threshold between small and large spill sizes are:\nLiquids - 55 gallons (208 liters)\nSolids - 60 pounds (300 kilograms)_______________________________________Я",
  "cellWidth": "Ж_Cell Width (x)_____Я",
  "cellHeight": "Ж_Cell Height (y)______Я",
  "invalidNumberMessage": "Ж_The value entered is not valid__________Я",
  "invalidRangeMessage": "Ж_Value must be greater than 0_________Я",
  "gridAngleInvalidRangeMessage": "Ж_Value must be between -89.9 and 89.9____________Я",
  "formatIconTooltip": "Ж_Format Input_____Я",
  "setCoordFormat": "Ж_Set Coordinate Format String_________Я",
  "prefixNumbers": "Ж_Add '+/-' prefix to positive and negative numbers________________Я",
  "cancelBtn": "Ж_Cancel___Я",
  "applyBtn": "Ж_Apply___Я",
  "comfirmInputNotation": "Ж_Confirm Input Notation________Я",
  "notationsMatch": "Ж_notations match your input please confirm which you would like to use______________________Я:",
  "missingLayerNameMessage": "Ж_You must enter a valid layer name before you can publish__________________Я",
  "parseCoordinatesError": "Ж_Unable to parse coordinates. Please check your input_________________Я.",
  "DD": "Ж_DD__Я",
  "DDM": "Ж_DDM__Я",
  "DMS": "Ж_DMS__Я",
  "DDRev": "Ж_DDRev___Я",
  "DDMRev": "Ж_DDMRev___Я",
  "DMSRev": "Ж_DMSRev___Я",
  "USNG": "Ж_USNG__Я",
  "MGRS": "Ж_MGRS__Я",
  "UTM_H": "Ж_UTM (H)___Я",
  "UTM": "Ж_UTM__Я",
  "GARS": "Ж_GARS__Я",
  "GEOREF": "Ж_GEOREF___Я",
  "DDLatLongNotation": "Ж_Decimal Degrees - Latitude/Longitude____________Я",
  "DDLongLatNotation": "Ж_Decimal Degrees  - Longitude/Latitude____________Я",
  "DDMLatLongNotation": "Ж_Degrees Decimal Minutes - Latitude/Longitude______________Я",
  "DDMLongLatNotation": "Ж_Degrees Decimal Minutes - Longitude/Latitude______________Я",
  "DMSLatLongNotation": "Ж_Degrees Minutes Seconds - Latitude/Longitude______________Я",
  "DMSLongLatNotation": "Ж_Degrees Minutes Seconds - Longitude/Latitude______________Я",
  "GARSNotation": "Ж_GARS__Я",
  "GEOREFNotation": "Ж_GEOREF___Я",
  "MGRSNotation": "Ж_MGRS__Я",
  "USNGNotation": "Ж_USNG__Я",
  "UTMBandNotation": "Ж_UTM - Band Letter______Я",
  "UTMHemNotation": "Ж_UTM - Hemisphere (N/S)________Я"
});