define({
  "_widgetLabel": "आ_Emergency Response Guide________ज",
  "ergMainPageTitle": "आ_Based on the Emergency Response Guidebook 2016_______________ज",
  "coordInputLabelStart": "आ_Spill Location (DD)_______ज",
  "coordInputLabel": "आ_Spill Location_____ज",
  "addPointToolTip": "आ_Add Spill Location______ज",
  "drawPointToolTip": "आ_Click to add spill location_________ज",
  "material": "आ_Material___ज",
  "materialPlaceholder": "आ_Start typing to search for a material____________ज",
  "table3Message": "आ_The material you have selected requires additional information if you are dealing with a large spill.\n\nPlease ensure you have the correct values selected for wind speed and transport container____________________________________________________________ज.",
  "table2Message": "आ_The material you have selected may produces a large amount of Toxic Inhalation Hazard gases when spilled in water.\n\nYou may want to consider using the following material(s):\n\n_______________________________________________________ज",
  "spillSize": "आ_Spill Size____ज",
  "small": "आ_Small___ज",
  "large": "आ_Large___ज",
  "fireLabel": "आ_Show Fire Isolation Zone________ज",
  "weatherLabel": "आ_Current Weather at Spill Location___________ज",
  "weatherIntialText": "आ_<br />Updated once a spill location has been idenitified__________________ज",
  "temperature": "आ_Temperature____ज",
  "wind": "आ_Wind__ज",
  "c": "आ_C_ज",
  "f": "आ_F_ज",
  "weatherErrorMessage": "आ_Weather info not obtained. Update Wind Speed and Time of Spill values manually________________________ज",
  "windDirection": "आ_Wind Direction (blowing to)_________ज",
  "timeOfSpill": "आ_Time of Spill_____ज",
  "day": "आ_Day__ज",
  "night": "आ_Night___ज",
  "windSpeed": "आ_Wind Speed____ज",
  "low": "आ_Low__ज",
  "moderate": "आ_Moderate___ज",
  "high": "आ_High__ज",
  "transportContainer": "आ_Transport Container_______ज",
  "rail": "आ_Rail tank car_____ज",
  "semi": "आ_Highway tank truck or trailer__________ज",
  "mton": "आ_Multiple ton cylinders________ज",
  "ston": "आ_Multiple small cylinders or single ton cylinder_______________ज",
  "ag": "आ_Agricultural nurse tank________ज",
  "msm": "आ_Multiple small cylinders________ज",
  "bleveLabel": "आ_Show BLEVE Isolation Zone_________ज",
  "capacity": "आ_Container Capacity (litres)_________ज",
  "bleveMessage": "आ_For the material you have selected an additional evacuation distance can be shown for BLEVE.\n\nTo enable this, set the Show BLEVE Isolation Zone toggle to on and select the appropiate container capacity______________________________________________________________ज.",
  "noPAZoneMessage": "आ_There are no Protective Action distances for this material. Only the Initial Isolation and evacuation zones has been calculated_______________________________________ज",
  "settingsTitle": "आ_Settings___ज",
  "spillLocationLabel": "आ_Spill Location_____ज",
  "spillLocationButtonLabel": "आ_Configure Spill Location Settings___________ज",
  "IISettingsLabel": "आ_Initial Isolation Zone________ज",
  "IIButtonLabel": "आ_Configure Initial Isolation Settings____________ज",
  "PASettingsLabel": "आ_Protective Action Zone________ज",
  "PAButtonLabel": "आ_Configure Protective Action Settings____________ज",
  "downwindSettingsLabel": "आ_Down Wind Zone_____ज",
  "downwindButtonLabel": "आ_Configure Down Wind Settings_________ज",
  "fireSettingsLabel": "आ_Fire Isolation Zone_______ज",
  "fireButtonLabel": "आ_Configure Fire Isolation Settings___________ज",
  "bleveSettingsLabel": "आ_BLEVE Isolation Zone_______ज",
  "bleveButtonLabel": "आ_Configure BLEVE Settings________ज",
  "outlineStyle": "आ_Outline Style_____ज",
  "dash": "आ_Dash__ज",
  "dashdot": "आ_Dash Dot___ज",
  "dashdotdot": "आ_Dash Dot Dot_____ज",
  "dot": "आ_Dot__ज",
  "longdash": "आ_Long Dash____ज",
  "longdashdot": "आ_Long Dash Dot_____ज",
  "null": "आ_Null__ज",
  "shortdash": "आ_Short Dash____ज",
  "shortdashdot": "आ_Short Dash Dot_____ज",
  "shortdashdotdot": "आ_Short Dash Dot Dot______ज",
  "shortdot": "आ_Short Dot____ज",
  "solid": "आ_Solid___ज",
  "fillStyle": "आ_Fill Style____ज",
  "backward": "आ_Backward___ज",
  "cross": "आ_Cross___ज",
  "diagonal": "आ_Diagonal___ज",
  "forward": "आ_Forward___ज",
  "horizontal": "आ_Horizontal____ज",
  "vertical": "आ_Vertical___ज",
  "resultsTitle": "आ_Results___ज",
  "publishERGBtn": "आ_Publish___ज",
  "ERGLayerName": "आ_Published ERG Layer Name________ज",
  "invalidERGLayerName": "आ_Layer name must only contain alpha-numeric characters and underscores______________________ज",
  "missingERGLayerName": "आ_You must enter a name for the ERG___________ज",
  "publishingFailedLayerExists": "आ_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________ज.",
  "checkService": "आ_Check Service: {0}______ज",
  "createService": "आ_Create Service: {0}_______ज",
  "unableToCreate": "आ_Unable to create: {0}_______ज",
  "addToDefinition": "आ_Add to definition: {0}________ज",
  "successfullyPublished": "आ_Successfully published web layer{0}Manage the web layer__________________ज",
  "userRole": "आ_Unable to create service because user does not have permissions____________________ज",
  "transparency": "आ_Transparency_____ज",
  "outline": "आ_Outline___ज",
  "fill": "आ_Fill (Color only applies when style set to solid)________________ज",
  "createERGBtn": "आ_Create Zones_____ज",
  "clearERGBtn": "आ_Clear___ज",
  "labelFormat": "आ_Label Format_____ज",
  "helpIconTooltip": "आ_The threshold between small and large spill sizes are:\nLiquids - 55 gallons (208 liters)\nSolids - 60 pounds (300 kilograms)_______________________________________ज",
  "cellWidth": "आ_Cell Width (x)_____ज",
  "cellHeight": "आ_Cell Height (y)______ज",
  "invalidNumberMessage": "आ_The value entered is not valid__________ज",
  "invalidRangeMessage": "आ_Value must be greater than 0_________ज",
  "gridAngleInvalidRangeMessage": "आ_Value must be between -89.9 and 89.9____________ज",
  "formatIconTooltip": "आ_Format Input_____ज",
  "setCoordFormat": "आ_Set Coordinate Format String_________ज",
  "prefixNumbers": "आ_Add '+/-' prefix to positive and negative numbers________________ज",
  "cancelBtn": "आ_Cancel___ज",
  "applyBtn": "आ_Apply___ज",
  "comfirmInputNotation": "आ_Confirm Input Notation________ज",
  "notationsMatch": "आ_notations match your input please confirm which you would like to use______________________ज:",
  "missingLayerNameMessage": "आ_You must enter a valid layer name before you can publish__________________ज",
  "parseCoordinatesError": "आ_Unable to parse coordinates. Please check your input_________________ज.",
  "DD": "आ_DD__ज",
  "DDM": "आ_DDM__ज",
  "DMS": "आ_DMS__ज",
  "DDRev": "आ_DDRev___ज",
  "DDMRev": "आ_DDMRev___ज",
  "DMSRev": "आ_DMSRev___ज",
  "USNG": "आ_USNG__ज",
  "MGRS": "आ_MGRS__ज",
  "UTM_H": "आ_UTM (H)___ज",
  "UTM": "आ_UTM__ज",
  "GARS": "आ_GARS__ज",
  "GEOREF": "आ_GEOREF___ज",
  "DDLatLongNotation": "आ_Decimal Degrees - Latitude/Longitude____________ज",
  "DDLongLatNotation": "आ_Decimal Degrees  - Longitude/Latitude____________ज",
  "DDMLatLongNotation": "आ_Degrees Decimal Minutes - Latitude/Longitude______________ज",
  "DDMLongLatNotation": "आ_Degrees Decimal Minutes - Longitude/Latitude______________ज",
  "DMSLatLongNotation": "आ_Degrees Minutes Seconds - Latitude/Longitude______________ज",
  "DMSLongLatNotation": "आ_Degrees Minutes Seconds - Longitude/Latitude______________ज",
  "GARSNotation": "आ_GARS__ज",
  "GEOREFNotation": "आ_GEOREF___ज",
  "MGRSNotation": "आ_MGRS__ज",
  "USNGNotation": "आ_USNG__ज",
  "UTMBandNotation": "आ_UTM - Band Letter______ज",
  "UTMHemNotation": "आ_UTM - Hemisphere (N/S)________ज"
});