define({
  "symbolologyTabLabel": "á_Configure Symbology_______Ó",
  "facilitiesDescription": "á_Facility Layers______Ó",
  "demographicsDescription": "á_Demographics Layer______Ó",
  "settingsTitle": "á_Settings___Ó",
  "spillLocationLabel": "á_Spill Location_____Ó",
  "spillLocationButtonLabel": "á_Configure Spill Location Settings___________Ó",
  "IISettingsLabel": "á_Initial Isolation Zone________Ó",
  "IIButtonLabel": "á_Configure Initial Isolation Settings____________Ó",
  "PASettingsLabel": "á_Protective Action Zone________Ó",
  "PAButtonLabel": "á_Configure Protective Action Settings____________Ó",
  "downwindSettingsLabel": "á_Down Wind Zone_____Ó",
  "downwindButtonLabel": "á_Configure Down Wind Settings_________Ó",
  "fireSettingsLabel": "á_Fire Isolation Zone_______Ó",
  "fireButtonLabel": "á_Configure Fire Isolation Settings___________Ó",
  "bleveSettingsLabel": "á_BLEVE Isolation Zone_______Ó",
  "bleveButtonLabel": "á_Configure BLEVE Settings________Ó",
  "transparency": "á_Transparency_____Ó",
  "outline": "á_Outline___Ó",
  "fill": "á_Fill (Color only applies when style set to solid)________________Ó",
  "outlineStyle": "á_Outline Style_____Ó",
  "dash": "á_Dash__Ó",
  "dashdot": "á_Dash Dot___Ó",
  "dashdotdot": "á_Dash Dot Dot_____Ó",
  "dot": "á_Dot__Ó",
  "longdash": "á_Long Dash____Ó",
  "longdashdot": "á_Long Dash Dot_____Ó",
  "null": "á_Null__Ó",
  "shortdash": "á_Short Dash____Ó",
  "shortdashdot": "á_Short Dash Dot_____Ó",
  "shortdashdotdot": "á_Short Dash Dot Dot______Ó",
  "shortdot": "á_Short Dot____Ó",
  "solid": "á_Solid___Ó",
  "fillStyle": "á_Fill Style____Ó",
  "backward": "á_Backward___Ó",
  "cross": "á_Cross___Ó",
  "diagonal": "á_Diagonal___Ó",
  "forward": "á_Forward___Ó",
  "horizontal": "á_Horizontal____Ó",
  "vertical": "á_Vertical___Ó"
});