define({
  "symbolologyTabLabel": "ก้_Configure Symbology_______ษฺ",
  "facilitiesDescription": "ก้_Facility Layers______ษฺ",
  "demographicsDescription": "ก้_Demographics Layer______ษฺ",
  "settingsTitle": "ก้_Settings___ษฺ",
  "spillLocationLabel": "ก้_Spill Location_____ษฺ",
  "spillLocationButtonLabel": "ก้_Configure Spill Location Settings___________ษฺ",
  "IISettingsLabel": "ก้_Initial Isolation Zone________ษฺ",
  "IIButtonLabel": "ก้_Configure Initial Isolation Settings____________ษฺ",
  "PASettingsLabel": "ก้_Protective Action Zone________ษฺ",
  "PAButtonLabel": "ก้_Configure Protective Action Settings____________ษฺ",
  "downwindSettingsLabel": "ก้_Down Wind Zone_____ษฺ",
  "downwindButtonLabel": "ก้_Configure Down Wind Settings_________ษฺ",
  "fireSettingsLabel": "ก้_Fire Isolation Zone_______ษฺ",
  "fireButtonLabel": "ก้_Configure Fire Isolation Settings___________ษฺ",
  "bleveSettingsLabel": "ก้_BLEVE Isolation Zone_______ษฺ",
  "bleveButtonLabel": "ก้_Configure BLEVE Settings________ษฺ",
  "transparency": "ก้_Transparency_____ษฺ",
  "outline": "ก้_Outline___ษฺ",
  "fill": "ก้_Fill (Color only applies when style set to solid)________________ษฺ",
  "outlineStyle": "ก้_Outline Style_____ษฺ",
  "dash": "ก้_Dash__ษฺ",
  "dashdot": "ก้_Dash Dot___ษฺ",
  "dashdotdot": "ก้_Dash Dot Dot_____ษฺ",
  "dot": "ก้_Dot__ษฺ",
  "longdash": "ก้_Long Dash____ษฺ",
  "longdashdot": "ก้_Long Dash Dot_____ษฺ",
  "null": "ก้_Null__ษฺ",
  "shortdash": "ก้_Short Dash____ษฺ",
  "shortdashdot": "ก้_Short Dash Dot_____ษฺ",
  "shortdashdotdot": "ก้_Short Dash Dot Dot______ษฺ",
  "shortdot": "ก้_Short Dot____ษฺ",
  "solid": "ก้_Solid___ษฺ",
  "fillStyle": "ก้_Fill Style____ษฺ",
  "backward": "ก้_Backward___ษฺ",
  "cross": "ก้_Cross___ษฺ",
  "diagonal": "ก้_Diagonal___ษฺ",
  "forward": "ก้_Forward___ษฺ",
  "horizontal": "ก้_Horizontal____ษฺ",
  "vertical": "ก้_Vertical___ษฺ"
});