define({
  "symbolologyTabLabel": "כן_Configure Symbology_______ש",
  "facilitiesDescription": "כן_Facility Layers______ש",
  "demographicsDescription": "כן_Demographics Layer______ש",
  "settingsTitle": "כן_Settings___ש",
  "spillLocationLabel": "כן_Spill Location_____ש",
  "spillLocationButtonLabel": "כן_Configure Spill Location Settings___________ש",
  "IISettingsLabel": "כן_Initial Isolation Zone________ש",
  "IIButtonLabel": "כן_Configure Initial Isolation Settings____________ש",
  "PASettingsLabel": "כן_Protective Action Zone________ש",
  "PAButtonLabel": "כן_Configure Protective Action Settings____________ש",
  "downwindSettingsLabel": "כן_Down Wind Zone_____ש",
  "downwindButtonLabel": "כן_Configure Down Wind Settings_________ש",
  "fireSettingsLabel": "כן_Fire Isolation Zone_______ש",
  "fireButtonLabel": "כן_Configure Fire Isolation Settings___________ש",
  "bleveSettingsLabel": "כן_BLEVE Isolation Zone_______ש",
  "bleveButtonLabel": "כן_Configure BLEVE Settings________ש",
  "transparency": "כן_Transparency_____ש",
  "outline": "כן_Outline___ש",
  "fill": "כן_Fill (Color only applies when style set to solid)________________ש",
  "outlineStyle": "כן_Outline Style_____ש",
  "dash": "כן_Dash__ש",
  "dashdot": "כן_Dash Dot___ש",
  "dashdotdot": "כן_Dash Dot Dot_____ש",
  "dot": "כן_Dot__ש",
  "longdash": "כן_Long Dash____ש",
  "longdashdot": "כן_Long Dash Dot_____ש",
  "null": "כן_Null__ש",
  "shortdash": "כן_Short Dash____ש",
  "shortdashdot": "כן_Short Dash Dot_____ש",
  "shortdashdotdot": "כן_Short Dash Dot Dot______ש",
  "shortdot": "כן_Short Dot____ש",
  "solid": "כן_Solid___ש",
  "fillStyle": "כן_Fill Style____ש",
  "backward": "כן_Backward___ש",
  "cross": "כן_Cross___ש",
  "diagonal": "כן_Diagonal___ש",
  "forward": "כן_Forward___ש",
  "horizontal": "כן_Horizontal____ש",
  "vertical": "כן_Vertical___ש"
});