define({
  "symbolologyTabLabel": "Ĳ_Configure Symbology_______ä",
  "facilitiesDescription": "Ĳ_Facility Layers______ä",
  "demographicsDescription": "Ĳ_Demographics Layer______ä",
  "settingsTitle": "Ĳ_Settings___ä",
  "spillLocationLabel": "Ĳ_Spill Location_____ä",
  "spillLocationButtonLabel": "Ĳ_Configure Spill Location Settings___________ä",
  "IISettingsLabel": "Ĳ_Initial Isolation Zone________ä",
  "IIButtonLabel": "Ĳ_Configure Initial Isolation Settings____________ä",
  "PASettingsLabel": "Ĳ_Protective Action Zone________ä",
  "PAButtonLabel": "Ĳ_Configure Protective Action Settings____________ä",
  "downwindSettingsLabel": "Ĳ_Down Wind Zone_____ä",
  "downwindButtonLabel": "Ĳ_Configure Down Wind Settings_________ä",
  "fireSettingsLabel": "Ĳ_Fire Isolation Zone_______ä",
  "fireButtonLabel": "Ĳ_Configure Fire Isolation Settings___________ä",
  "bleveSettingsLabel": "Ĳ_BLEVE Isolation Zone_______ä",
  "bleveButtonLabel": "Ĳ_Configure BLEVE Settings________ä",
  "transparency": "Ĳ_Transparency_____ä",
  "outline": "Ĳ_Outline___ä",
  "fill": "Ĳ_Fill (Color only applies when style set to solid)________________ä",
  "outlineStyle": "Ĳ_Outline Style_____ä",
  "dash": "Ĳ_Dash__ä",
  "dashdot": "Ĳ_Dash Dot___ä",
  "dashdotdot": "Ĳ_Dash Dot Dot_____ä",
  "dot": "Ĳ_Dot__ä",
  "longdash": "Ĳ_Long Dash____ä",
  "longdashdot": "Ĳ_Long Dash Dot_____ä",
  "null": "Ĳ_Null__ä",
  "shortdash": "Ĳ_Short Dash____ä",
  "shortdashdot": "Ĳ_Short Dash Dot_____ä",
  "shortdashdotdot": "Ĳ_Short Dash Dot Dot______ä",
  "shortdot": "Ĳ_Short Dot____ä",
  "solid": "Ĳ_Solid___ä",
  "fillStyle": "Ĳ_Fill Style____ä",
  "backward": "Ĳ_Backward___ä",
  "cross": "Ĳ_Cross___ä",
  "diagonal": "Ĳ_Diagonal___ä",
  "forward": "Ĳ_Forward___ä",
  "horizontal": "Ĳ_Horizontal____ä",
  "vertical": "Ĳ_Vertical___ä"
});