define({
  "symbolologyTabLabel": "ø_Configure Symbology_______å",
  "facilitiesDescription": "ø_Facility Layers______å",
  "demographicsDescription": "ø_Demographics Layer______å",
  "settingsTitle": "ø_Settings___å",
  "spillLocationLabel": "ø_Spill Location_____å",
  "spillLocationButtonLabel": "ø_Configure Spill Location Settings___________å",
  "IISettingsLabel": "ø_Initial Isolation Zone________å",
  "IIButtonLabel": "ø_Configure Initial Isolation Settings____________å",
  "PASettingsLabel": "ø_Protective Action Zone________å",
  "PAButtonLabel": "ø_Configure Protective Action Settings____________å",
  "downwindSettingsLabel": "ø_Down Wind Zone_____å",
  "downwindButtonLabel": "ø_Configure Down Wind Settings_________å",
  "fireSettingsLabel": "ø_Fire Isolation Zone_______å",
  "fireButtonLabel": "ø_Configure Fire Isolation Settings___________å",
  "bleveSettingsLabel": "ø_BLEVE Isolation Zone_______å",
  "bleveButtonLabel": "ø_Configure BLEVE Settings________å",
  "transparency": "ø_Transparency_____å",
  "outline": "ø_Outline___å",
  "fill": "ø_Fill (Color only applies when style set to solid)________________å",
  "outlineStyle": "ø_Outline Style_____å",
  "dash": "ø_Dash__å",
  "dashdot": "ø_Dash Dot___å",
  "dashdotdot": "ø_Dash Dot Dot_____å",
  "dot": "ø_Dot__å",
  "longdash": "ø_Long Dash____å",
  "longdashdot": "ø_Long Dash Dot_____å",
  "null": "ø_Null__å",
  "shortdash": "ø_Short Dash____å",
  "shortdashdot": "ø_Short Dash Dot_____å",
  "shortdashdotdot": "ø_Short Dash Dot Dot______å",
  "shortdot": "ø_Short Dot____å",
  "solid": "ø_Solid___å",
  "fillStyle": "ø_Fill Style____å",
  "backward": "ø_Backward___å",
  "cross": "ø_Cross___å",
  "diagonal": "ø_Diagonal___å",
  "forward": "ø_Forward___å",
  "horizontal": "ø_Horizontal____å",
  "vertical": "ø_Vertical___å"
});