define({
  "symbolologyTabLabel": "Å_Configure Symbology_______ö",
  "facilitiesDescription": "Å_Facility Layers______ö",
  "demographicsDescription": "Å_Demographics Layer______ö",
  "settingsTitle": "Å_Settings___ö",
  "spillLocationLabel": "Å_Spill Location_____ö",
  "spillLocationButtonLabel": "Å_Configure Spill Location Settings___________ö",
  "IISettingsLabel": "Å_Initial Isolation Zone________ö",
  "IIButtonLabel": "Å_Configure Initial Isolation Settings____________ö",
  "PASettingsLabel": "Å_Protective Action Zone________ö",
  "PAButtonLabel": "Å_Configure Protective Action Settings____________ö",
  "downwindSettingsLabel": "Å_Down Wind Zone_____ö",
  "downwindButtonLabel": "Å_Configure Down Wind Settings_________ö",
  "fireSettingsLabel": "Å_Fire Isolation Zone_______ö",
  "fireButtonLabel": "Å_Configure Fire Isolation Settings___________ö",
  "bleveSettingsLabel": "Å_BLEVE Isolation Zone_______ö",
  "bleveButtonLabel": "Å_Configure BLEVE Settings________ö",
  "transparency": "Å_Transparency_____ö",
  "outline": "Å_Outline___ö",
  "fill": "Å_Fill (Color only applies when style set to solid)________________ö",
  "outlineStyle": "Å_Outline Style_____ö",
  "dash": "Å_Dash__ö",
  "dashdot": "Å_Dash Dot___ö",
  "dashdotdot": "Å_Dash Dot Dot_____ö",
  "dot": "Å_Dot__ö",
  "longdash": "Å_Long Dash____ö",
  "longdashdot": "Å_Long Dash Dot_____ö",
  "null": "Å_Null__ö",
  "shortdash": "Å_Short Dash____ö",
  "shortdashdot": "Å_Short Dash Dot_____ö",
  "shortdashdotdot": "Å_Short Dash Dot Dot______ö",
  "shortdot": "Å_Short Dot____ö",
  "solid": "Å_Solid___ö",
  "fillStyle": "Å_Fill Style____ö",
  "backward": "Å_Backward___ö",
  "cross": "Å_Cross___ö",
  "diagonal": "Å_Diagonal___ö",
  "forward": "Å_Forward___ö",
  "horizontal": "Å_Horizontal____ö",
  "vertical": "Å_Vertical___ö"
});