define({
  "symbolologyTabLabel": "Ж_Configure Symbology_______Я",
  "facilitiesDescription": "Ж_Facility Layers______Я",
  "demographicsDescription": "Ж_Demographics Layer______Я",
  "settingsTitle": "Ж_Settings___Я",
  "spillLocationLabel": "Ж_Spill Location_____Я",
  "spillLocationButtonLabel": "Ж_Configure Spill Location Settings___________Я",
  "IISettingsLabel": "Ж_Initial Isolation Zone________Я",
  "IIButtonLabel": "Ж_Configure Initial Isolation Settings____________Я",
  "PASettingsLabel": "Ж_Protective Action Zone________Я",
  "PAButtonLabel": "Ж_Configure Protective Action Settings____________Я",
  "downwindSettingsLabel": "Ж_Down Wind Zone_____Я",
  "downwindButtonLabel": "Ж_Configure Down Wind Settings_________Я",
  "fireSettingsLabel": "Ж_Fire Isolation Zone_______Я",
  "fireButtonLabel": "Ж_Configure Fire Isolation Settings___________Я",
  "bleveSettingsLabel": "Ж_BLEVE Isolation Zone_______Я",
  "bleveButtonLabel": "Ж_Configure BLEVE Settings________Я",
  "transparency": "Ж_Transparency_____Я",
  "outline": "Ж_Outline___Я",
  "fill": "Ж_Fill (Color only applies when style set to solid)________________Я",
  "outlineStyle": "Ж_Outline Style_____Я",
  "dash": "Ж_Dash__Я",
  "dashdot": "Ж_Dash Dot___Я",
  "dashdotdot": "Ж_Dash Dot Dot_____Я",
  "dot": "Ж_Dot__Я",
  "longdash": "Ж_Long Dash____Я",
  "longdashdot": "Ж_Long Dash Dot_____Я",
  "null": "Ж_Null__Я",
  "shortdash": "Ж_Short Dash____Я",
  "shortdashdot": "Ж_Short Dash Dot_____Я",
  "shortdashdotdot": "Ж_Short Dash Dot Dot______Я",
  "shortdot": "Ж_Short Dot____Я",
  "solid": "Ж_Solid___Я",
  "fillStyle": "Ж_Fill Style____Я",
  "backward": "Ж_Backward___Я",
  "cross": "Ж_Cross___Я",
  "diagonal": "Ж_Diagonal___Я",
  "forward": "Ж_Forward___Я",
  "horizontal": "Ж_Horizontal____Я",
  "vertical": "Ж_Vertical___Я"
});