define({
  "_widgetLabel": "ı_Emergency Response Guide________İ",
  "ergMainPageTitle": "ı_Based on the Emergency Response Guidebook 2016_______________İ",
  "coordInputLabelStart": "ı_Spill Location (DD)_______İ",
  "coordInputLabel": "ı_Spill Location_____İ",
  "addPointToolTip": "ı_Add Spill Location______İ",
  "drawPointToolTip": "ı_Click to add spill location_________İ",
  "material": "ı_Material___İ",
  "materialPlaceholder": "ı_Start typing to search for a material____________İ",
  "table3Message": "ı_The material you have selected requires additional information if you are dealing with a large spill.\n\nPlease ensure you have the correct values selected for wind speed and transport container____________________________________________________________İ.",
  "table2Message": "ı_The material you have selected may produces a large amount of Toxic Inhalation Hazard gases when spilled in water.\n\nYou may want to consider using the following material(s):\n\n_______________________________________________________İ",
  "spillSize": "ı_Spill Size____İ",
  "small": "ı_Small___İ",
  "large": "ı_Large___İ",
  "fireLabel": "ı_Show Fire Isolation Zone________İ",
  "weatherLabel": "ı_Current Weather at Spill Location___________İ",
  "weatherIntialText": "ı_<br />Updated once a spill location has been idenitified__________________İ",
  "temperature": "ı_Temperature____İ",
  "wind": "ı_Wind__İ",
  "c": "ı_C_İ",
  "f": "ı_F_İ",
  "weatherErrorMessage": "ı_Weather info not obtained. Update Wind Speed and Time of Spill values manually________________________İ",
  "windDirection": "ı_Wind Direction (blowing to)_________İ",
  "timeOfSpill": "ı_Time of Spill_____İ",
  "day": "ı_Day__İ",
  "night": "ı_Night___İ",
  "windSpeed": "ı_Wind Speed____İ",
  "low": "ı_Low__İ",
  "moderate": "ı_Moderate___İ",
  "high": "ı_High__İ",
  "transportContainer": "ı_Transport Container_______İ",
  "rail": "ı_Rail tank car_____İ",
  "semi": "ı_Highway tank truck or trailer__________İ",
  "mton": "ı_Multiple ton cylinders________İ",
  "ston": "ı_Multiple small cylinders or single ton cylinder_______________İ",
  "ag": "ı_Agricultural nurse tank________İ",
  "msm": "ı_Multiple small cylinders________İ",
  "bleveLabel": "ı_Show BLEVE Isolation Zone_________İ",
  "capacity": "ı_Container Capacity (litres)_________İ",
  "bleveMessage": "ı_For the material you have selected an additional evacuation distance can be shown for BLEVE.\n\nTo enable this, set the Show BLEVE Isolation Zone toggle to on and select the appropiate container capacity______________________________________________________________İ.",
  "noPAZoneMessage": "ı_There are no Protective Action distances for this material. Only the Initial Isolation and evacuation zones has been calculated_______________________________________İ",
  "settingsTitle": "ı_Settings___İ",
  "spillLocationLabel": "ı_Spill Location_____İ",
  "spillLocationButtonLabel": "ı_Configure Spill Location Settings___________İ",
  "IISettingsLabel": "ı_Initial Isolation Zone________İ",
  "IIButtonLabel": "ı_Configure Initial Isolation Settings____________İ",
  "PASettingsLabel": "ı_Protective Action Zone________İ",
  "PAButtonLabel": "ı_Configure Protective Action Settings____________İ",
  "downwindSettingsLabel": "ı_Down Wind Zone_____İ",
  "downwindButtonLabel": "ı_Configure Down Wind Settings_________İ",
  "fireSettingsLabel": "ı_Fire Isolation Zone_______İ",
  "fireButtonLabel": "ı_Configure Fire Isolation Settings___________İ",
  "bleveSettingsLabel": "ı_BLEVE Isolation Zone_______İ",
  "bleveButtonLabel": "ı_Configure BLEVE Settings________İ",
  "outlineStyle": "ı_Outline Style_____İ",
  "dash": "ı_Dash__İ",
  "dashdot": "ı_Dash Dot___İ",
  "dashdotdot": "ı_Dash Dot Dot_____İ",
  "dot": "ı_Dot__İ",
  "longdash": "ı_Long Dash____İ",
  "longdashdot": "ı_Long Dash Dot_____İ",
  "null": "ı_Null__İ",
  "shortdash": "ı_Short Dash____İ",
  "shortdashdot": "ı_Short Dash Dot_____İ",
  "shortdashdotdot": "ı_Short Dash Dot Dot______İ",
  "shortdot": "ı_Short Dot____İ",
  "solid": "ı_Solid___İ",
  "fillStyle": "ı_Fill Style____İ",
  "backward": "ı_Backward___İ",
  "cross": "ı_Cross___İ",
  "diagonal": "ı_Diagonal___İ",
  "forward": "ı_Forward___İ",
  "horizontal": "ı_Horizontal____İ",
  "vertical": "ı_Vertical___İ",
  "resultsTitle": "ı_Results___İ",
  "publishERGBtn": "ı_Publish___İ",
  "ERGLayerName": "ı_Published ERG Layer Name________İ",
  "invalidERGLayerName": "ı_Layer name must only contain alpha-numeric characters and underscores______________________İ",
  "missingERGLayerName": "ı_You must enter a name for the ERG___________İ",
  "publishingFailedLayerExists": "ı_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________İ.",
  "checkService": "ı_Check Service: {0}______İ",
  "createService": "ı_Create Service: {0}_______İ",
  "unableToCreate": "ı_Unable to create: {0}_______İ",
  "addToDefinition": "ı_Add to definition: {0}________İ",
  "successfullyPublished": "ı_Successfully published web layer{0}Manage the web layer__________________İ",
  "userRole": "ı_Unable to create service because user does not have permissions____________________İ",
  "transparency": "ı_Transparency_____İ",
  "outline": "ı_Outline___İ",
  "fill": "ı_Fill (Color only applies when style set to solid)________________İ",
  "createERGBtn": "ı_Create Zones_____İ",
  "clearERGBtn": "ı_Clear___İ",
  "labelFormat": "ı_Label Format_____İ",
  "helpIconTooltip": "ı_The threshold between small and large spill sizes are:\nLiquids - 55 gallons (208 liters)\nSolids - 60 pounds (300 kilograms)_______________________________________İ",
  "cellWidth": "ı_Cell Width (x)_____İ",
  "cellHeight": "ı_Cell Height (y)______İ",
  "invalidNumberMessage": "ı_The value entered is not valid__________İ",
  "invalidRangeMessage": "ı_Value must be greater than 0_________İ",
  "gridAngleInvalidRangeMessage": "ı_Value must be between -89.9 and 89.9____________İ",
  "formatIconTooltip": "ı_Format Input_____İ",
  "setCoordFormat": "ı_Set Coordinate Format String_________İ",
  "prefixNumbers": "ı_Add '+/-' prefix to positive and negative numbers________________İ",
  "cancelBtn": "ı_Cancel___İ",
  "applyBtn": "ı_Apply___İ",
  "comfirmInputNotation": "ı_Confirm Input Notation________İ",
  "notationsMatch": "ı_notations match your input please confirm which you would like to use______________________İ:",
  "missingLayerNameMessage": "ı_You must enter a valid layer name before you can publish__________________İ",
  "parseCoordinatesError": "ı_Unable to parse coordinates. Please check your input_________________İ.",
  "DD": "ı_DD__İ",
  "DDM": "ı_DDM__İ",
  "DMS": "ı_DMS__İ",
  "DDRev": "ı_DDRev___İ",
  "DDMRev": "ı_DDMRev___İ",
  "DMSRev": "ı_DMSRev___İ",
  "USNG": "ı_USNG__İ",
  "MGRS": "ı_MGRS__İ",
  "UTM_H": "ı_UTM (H)___İ",
  "UTM": "ı_UTM__İ",
  "GARS": "ı_GARS__İ",
  "GEOREF": "ı_GEOREF___İ",
  "DDLatLongNotation": "ı_Decimal Degrees - Latitude/Longitude____________İ",
  "DDLongLatNotation": "ı_Decimal Degrees  - Longitude/Latitude____________İ",
  "DDMLatLongNotation": "ı_Degrees Decimal Minutes - Latitude/Longitude______________İ",
  "DDMLongLatNotation": "ı_Degrees Decimal Minutes - Longitude/Latitude______________İ",
  "DMSLatLongNotation": "ı_Degrees Minutes Seconds - Latitude/Longitude______________İ",
  "DMSLongLatNotation": "ı_Degrees Minutes Seconds - Longitude/Latitude______________İ",
  "GARSNotation": "ı_GARS__İ",
  "GEOREFNotation": "ı_GEOREF___İ",
  "MGRSNotation": "ı_MGRS__İ",
  "USNGNotation": "ı_USNG__İ",
  "UTMBandNotation": "ı_UTM - Band Letter______İ",
  "UTMHemNotation": "ı_UTM - Hemisphere (N/S)________İ"
});