define({
  "_widgetLabel": "כן_Emergency Response Guide________ש",
  "ergMainPageTitle": "כן_Based on the Emergency Response Guidebook 2016_______________ש",
  "coordInputLabelStart": "כן_Spill Location (DD)_______ש",
  "coordInputLabel": "כן_Spill Location_____ש",
  "addPointToolTip": "כן_Add Spill Location______ש",
  "drawPointToolTip": "כן_Click to add spill location_________ש",
  "material": "כן_Material___ש",
  "materialPlaceholder": "כן_Start typing to search for a material____________ש",
  "table3Message": "כן_The material you have selected requires additional information if you are dealing with a large spill.\n\nPlease ensure you have the correct values selected for wind speed and transport container____________________________________________________________ש.",
  "table2Message": "כן_The material you have selected may produces a large amount of Toxic Inhalation Hazard gases when spilled in water.\n\nYou may want to consider using the following material(s):\n\n_______________________________________________________ש",
  "spillSize": "כן_Spill Size____ש",
  "small": "כן_Small___ש",
  "large": "כן_Large___ש",
  "fireLabel": "כן_Show Fire Isolation Zone________ש",
  "weatherLabel": "כן_Current Weather at Spill Location___________ש",
  "weatherIntialText": "כן_<br />Updated once a spill location has been idenitified__________________ש",
  "temperature": "כן_Temperature____ש",
  "wind": "כן_Wind__ש",
  "c": "כן_C_ש",
  "f": "כן_F_ש",
  "weatherErrorMessage": "כן_Weather info not obtained. Update Wind Speed and Time of Spill values manually________________________ש",
  "windDirection": "כן_Wind Direction (blowing to)_________ש",
  "timeOfSpill": "כן_Time of Spill_____ש",
  "day": "כן_Day__ש",
  "night": "כן_Night___ש",
  "windSpeed": "כן_Wind Speed____ש",
  "low": "כן_Low__ש",
  "moderate": "כן_Moderate___ש",
  "high": "כן_High__ש",
  "transportContainer": "כן_Transport Container_______ש",
  "rail": "כן_Rail tank car_____ש",
  "semi": "כן_Highway tank truck or trailer__________ש",
  "mton": "כן_Multiple ton cylinders________ש",
  "ston": "כן_Multiple small cylinders or single ton cylinder_______________ש",
  "ag": "כן_Agricultural nurse tank________ש",
  "msm": "כן_Multiple small cylinders________ש",
  "bleveLabel": "כן_Show BLEVE Isolation Zone_________ש",
  "capacity": "כן_Container Capacity (litres)_________ש",
  "bleveMessage": "כן_For the material you have selected an additional evacuation distance can be shown for BLEVE.\n\nTo enable this, set the Show BLEVE Isolation Zone toggle to on and select the appropiate container capacity______________________________________________________________ש.",
  "noPAZoneMessage": "כן_There are no Protective Action distances for this material. Only the Initial Isolation and evacuation zones has been calculated_______________________________________ש",
  "settingsTitle": "כן_Settings___ש",
  "spillLocationLabel": "כן_Spill Location_____ש",
  "spillLocationButtonLabel": "כן_Configure Spill Location Settings___________ש",
  "IISettingsLabel": "כן_Initial Isolation Zone________ש",
  "IIButtonLabel": "כן_Configure Initial Isolation Settings____________ש",
  "PASettingsLabel": "כן_Protective Action Zone________ש",
  "PAButtonLabel": "כן_Configure Protective Action Settings____________ש",
  "downwindSettingsLabel": "כן_Down Wind Zone_____ש",
  "downwindButtonLabel": "כן_Configure Down Wind Settings_________ש",
  "fireSettingsLabel": "כן_Fire Isolation Zone_______ש",
  "fireButtonLabel": "כן_Configure Fire Isolation Settings___________ש",
  "bleveSettingsLabel": "כן_BLEVE Isolation Zone_______ש",
  "bleveButtonLabel": "כן_Configure BLEVE Settings________ש",
  "outlineStyle": "כן_Outline Style_____ש",
  "dash": "כן_Dash__ש",
  "dashdot": "כן_Dash Dot___ש",
  "dashdotdot": "כן_Dash Dot Dot_____ש",
  "dot": "כן_Dot__ש",
  "longdash": "כן_Long Dash____ש",
  "longdashdot": "כן_Long Dash Dot_____ש",
  "null": "כן_Null__ש",
  "shortdash": "כן_Short Dash____ש",
  "shortdashdot": "כן_Short Dash Dot_____ש",
  "shortdashdotdot": "כן_Short Dash Dot Dot______ש",
  "shortdot": "כן_Short Dot____ש",
  "solid": "כן_Solid___ש",
  "fillStyle": "כן_Fill Style____ש",
  "backward": "כן_Backward___ש",
  "cross": "כן_Cross___ש",
  "diagonal": "כן_Diagonal___ש",
  "forward": "כן_Forward___ש",
  "horizontal": "כן_Horizontal____ש",
  "vertical": "כן_Vertical___ש",
  "resultsTitle": "כן_Results___ש",
  "publishERGBtn": "כן_Publish___ש",
  "ERGLayerName": "כן_Published ERG Layer Name________ש",
  "invalidERGLayerName": "כן_Layer name must only contain alpha-numeric characters and underscores______________________ש",
  "missingERGLayerName": "כן_You must enter a name for the ERG___________ש",
  "publishingFailedLayerExists": "כן_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________ש.",
  "checkService": "כן_Check Service: {0}______ש",
  "createService": "כן_Create Service: {0}_______ש",
  "unableToCreate": "כן_Unable to create: {0}_______ש",
  "addToDefinition": "כן_Add to definition: {0}________ש",
  "successfullyPublished": "כן_Successfully published web layer{0}Manage the web layer__________________ש",
  "userRole": "כן_Unable to create service because user does not have permissions____________________ש",
  "transparency": "כן_Transparency_____ש",
  "outline": "כן_Outline___ש",
  "fill": "כן_Fill (Color only applies when style set to solid)________________ש",
  "createERGBtn": "כן_Create Zones_____ש",
  "clearERGBtn": "כן_Clear___ש",
  "labelFormat": "כן_Label Format_____ש",
  "helpIconTooltip": "כן_The threshold between small and large spill sizes are:\nLiquids - 55 gallons (208 liters)\nSolids - 60 pounds (300 kilograms)_______________________________________ש",
  "cellWidth": "כן_Cell Width (x)_____ש",
  "cellHeight": "כן_Cell Height (y)______ש",
  "invalidNumberMessage": "כן_The value entered is not valid__________ש",
  "invalidRangeMessage": "כן_Value must be greater than 0_________ש",
  "gridAngleInvalidRangeMessage": "כן_Value must be between -89.9 and 89.9____________ש",
  "formatIconTooltip": "כן_Format Input_____ש",
  "setCoordFormat": "כן_Set Coordinate Format String_________ש",
  "prefixNumbers": "כן_Add '+/-' prefix to positive and negative numbers________________ש",
  "cancelBtn": "כן_Cancel___ש",
  "applyBtn": "כן_Apply___ש",
  "comfirmInputNotation": "כן_Confirm Input Notation________ש",
  "notationsMatch": "כן_notations match your input please confirm which you would like to use______________________ש:",
  "missingLayerNameMessage": "כן_You must enter a valid layer name before you can publish__________________ש",
  "parseCoordinatesError": "כן_Unable to parse coordinates. Please check your input_________________ש.",
  "DD": "כן_DD__ש",
  "DDM": "כן_DDM__ש",
  "DMS": "כן_DMS__ש",
  "DDRev": "כן_DDRev___ש",
  "DDMRev": "כן_DDMRev___ש",
  "DMSRev": "כן_DMSRev___ש",
  "USNG": "כן_USNG__ש",
  "MGRS": "כן_MGRS__ש",
  "UTM_H": "כן_UTM (H)___ש",
  "UTM": "כן_UTM__ש",
  "GARS": "כן_GARS__ש",
  "GEOREF": "כן_GEOREF___ש",
  "DDLatLongNotation": "כן_Decimal Degrees - Latitude/Longitude____________ש",
  "DDLongLatNotation": "כן_Decimal Degrees  - Longitude/Latitude____________ש",
  "DDMLatLongNotation": "כן_Degrees Decimal Minutes - Latitude/Longitude______________ש",
  "DDMLongLatNotation": "כן_Degrees Decimal Minutes - Longitude/Latitude______________ש",
  "DMSLatLongNotation": "כן_Degrees Minutes Seconds - Latitude/Longitude______________ש",
  "DMSLongLatNotation": "כן_Degrees Minutes Seconds - Longitude/Latitude______________ש",
  "GARSNotation": "כן_GARS__ש",
  "GEOREFNotation": "כן_GEOREF___ש",
  "MGRSNotation": "כן_MGRS__ש",
  "USNGNotation": "כן_USNG__ש",
  "UTMBandNotation": "כן_UTM - Band Letter______ש",
  "UTMHemNotation": "כן_UTM - Hemisphere (N/S)________ש"
});