define({
  "symbolologyTabLabel": "Ă_Configure Symbology_______ș",
  "facilitiesDescription": "Ă_Facility Layers______ș",
  "demographicsDescription": "Ă_Demographics Layer______ș",
  "settingsTitle": "Ă_Settings___ș",
  "spillLocationLabel": "Ă_Spill Location_____ș",
  "spillLocationButtonLabel": "Ă_Configure Spill Location Settings___________ș",
  "IISettingsLabel": "Ă_Initial Isolation Zone________ș",
  "IIButtonLabel": "Ă_Configure Initial Isolation Settings____________ș",
  "PASettingsLabel": "Ă_Protective Action Zone________ș",
  "PAButtonLabel": "Ă_Configure Protective Action Settings____________ș",
  "downwindSettingsLabel": "Ă_Down Wind Zone_____ș",
  "downwindButtonLabel": "Ă_Configure Down Wind Settings_________ș",
  "fireSettingsLabel": "Ă_Fire Isolation Zone_______ș",
  "fireButtonLabel": "Ă_Configure Fire Isolation Settings___________ș",
  "bleveSettingsLabel": "Ă_BLEVE Isolation Zone_______ș",
  "bleveButtonLabel": "Ă_Configure BLEVE Settings________ș",
  "transparency": "Ă_Transparency_____ș",
  "outline": "Ă_Outline___ș",
  "fill": "Ă_Fill (Color only applies when style set to solid)________________ș",
  "outlineStyle": "Ă_Outline Style_____ș",
  "dash": "Ă_Dash__ș",
  "dashdot": "Ă_Dash Dot___ș",
  "dashdotdot": "Ă_Dash Dot Dot_____ș",
  "dot": "Ă_Dot__ș",
  "longdash": "Ă_Long Dash____ș",
  "longdashdot": "Ă_Long Dash Dot_____ș",
  "null": "Ă_Null__ș",
  "shortdash": "Ă_Short Dash____ș",
  "shortdashdot": "Ă_Short Dash Dot_____ș",
  "shortdashdotdot": "Ă_Short Dash Dot Dot______ș",
  "shortdot": "Ă_Short Dot____ș",
  "solid": "Ă_Solid___ș",
  "fillStyle": "Ă_Fill Style____ș",
  "backward": "Ă_Backward___ș",
  "cross": "Ă_Cross___ș",
  "diagonal": "Ă_Diagonal___ș",
  "forward": "Ă_Forward___ș",
  "horizontal": "Ă_Horizontal____ș",
  "vertical": "Ă_Vertical___ș"
});