define({
  "symbolologyTabLabel": "ł_Configure Symbology_______ą",
  "facilitiesDescription": "ł_Facility Layers______ą",
  "demographicsDescription": "ł_Demographics Layer______ą",
  "settingsTitle": "ł_Settings___ą",
  "spillLocationLabel": "ł_Spill Location_____ą",
  "spillLocationButtonLabel": "ł_Configure Spill Location Settings___________ą",
  "IISettingsLabel": "ł_Initial Isolation Zone________ą",
  "IIButtonLabel": "ł_Configure Initial Isolation Settings____________ą",
  "PASettingsLabel": "ł_Protective Action Zone________ą",
  "PAButtonLabel": "ł_Configure Protective Action Settings____________ą",
  "downwindSettingsLabel": "ł_Down Wind Zone_____ą",
  "downwindButtonLabel": "ł_Configure Down Wind Settings_________ą",
  "fireSettingsLabel": "ł_Fire Isolation Zone_______ą",
  "fireButtonLabel": "ł_Configure Fire Isolation Settings___________ą",
  "bleveSettingsLabel": "ł_BLEVE Isolation Zone_______ą",
  "bleveButtonLabel": "ł_Configure BLEVE Settings________ą",
  "transparency": "ł_Transparency_____ą",
  "outline": "ł_Outline___ą",
  "fill": "ł_Fill (Color only applies when style set to solid)________________ą",
  "outlineStyle": "ł_Outline Style_____ą",
  "dash": "ł_Dash__ą",
  "dashdot": "ł_Dash Dot___ą",
  "dashdotdot": "ł_Dash Dot Dot_____ą",
  "dot": "ł_Dot__ą",
  "longdash": "ł_Long Dash____ą",
  "longdashdot": "ł_Long Dash Dot_____ą",
  "null": "ł_Null__ą",
  "shortdash": "ł_Short Dash____ą",
  "shortdashdot": "ł_Short Dash Dot_____ą",
  "shortdashdotdot": "ł_Short Dash Dot Dot______ą",
  "shortdot": "ł_Short Dot____ą",
  "solid": "ł_Solid___ą",
  "fillStyle": "ł_Fill Style____ą",
  "backward": "ł_Backward___ą",
  "cross": "ł_Cross___ą",
  "diagonal": "ł_Diagonal___ą",
  "forward": "ł_Forward___ą",
  "horizontal": "ł_Horizontal____ą",
  "vertical": "ł_Vertical___ą"
});