define({
  "symbolologyTabLabel": "試_Configure Symbology_______驗",
  "facilitiesDescription": "試_Facility Layers______驗",
  "demographicsDescription": "試_Demographics Layer______驗",
  "settingsTitle": "試_Settings___驗",
  "spillLocationLabel": "試_Spill Location_____驗",
  "spillLocationButtonLabel": "試_Configure Spill Location Settings___________驗",
  "IISettingsLabel": "試_Initial Isolation Zone________驗",
  "IIButtonLabel": "試_Configure Initial Isolation Settings____________驗",
  "PASettingsLabel": "試_Protective Action Zone________驗",
  "PAButtonLabel": "試_Configure Protective Action Settings____________驗",
  "downwindSettingsLabel": "試_Down Wind Zone_____驗",
  "downwindButtonLabel": "試_Configure Down Wind Settings_________驗",
  "fireSettingsLabel": "試_Fire Isolation Zone_______驗",
  "fireButtonLabel": "試_Configure Fire Isolation Settings___________驗",
  "bleveSettingsLabel": "試_BLEVE Isolation Zone_______驗",
  "bleveButtonLabel": "試_Configure BLEVE Settings________驗",
  "transparency": "試_Transparency_____驗",
  "outline": "試_Outline___驗",
  "fill": "試_Fill (Color only applies when style set to solid)________________驗",
  "outlineStyle": "試_Outline Style_____驗",
  "dash": "試_Dash__驗",
  "dashdot": "試_Dash Dot___驗",
  "dashdotdot": "試_Dash Dot Dot_____驗",
  "dot": "試_Dot__驗",
  "longdash": "試_Long Dash____驗",
  "longdashdot": "試_Long Dash Dot_____驗",
  "null": "試_Null__驗",
  "shortdash": "試_Short Dash____驗",
  "shortdashdot": "試_Short Dash Dot_____驗",
  "shortdashdotdot": "試_Short Dash Dot Dot______驗",
  "shortdot": "試_Short Dot____驗",
  "solid": "試_Solid___驗",
  "fillStyle": "試_Fill Style____驗",
  "backward": "試_Backward___驗",
  "cross": "試_Cross___驗",
  "diagonal": "試_Diagonal___驗",
  "forward": "試_Forward___驗",
  "horizontal": "試_Horizontal____驗",
  "vertical": "試_Vertical___驗"
});