define({
  "_widgetLabel": "한_Emergency Response Guide________빠",
  "ergMainPageTitle": "한_Based on the Emergency Response Guidebook 2016_______________빠",
  "coordInputLabelStart": "한_Spill Location (DD)_______빠",
  "coordInputLabel": "한_Spill Location_____빠",
  "addPointToolTip": "한_Add Spill Location______빠",
  "drawPointToolTip": "한_Click to add spill location_________빠",
  "material": "한_Material___빠",
  "materialPlaceholder": "한_Start typing to search for a material____________빠",
  "table3Message": "한_The material you have selected requires additional information if you are dealing with a large spill.\n\nPlease ensure you have the correct values selected for wind speed and transport container____________________________________________________________빠.",
  "table2Message": "한_The material you have selected may produces a large amount of Toxic Inhalation Hazard gases when spilled in water.\n\nYou may want to consider using the following material(s):\n\n_______________________________________________________빠",
  "spillSize": "한_Spill Size____빠",
  "small": "한_Small___빠",
  "large": "한_Large___빠",
  "fireLabel": "한_Show Fire Isolation Zone________빠",
  "weatherLabel": "한_Current Weather at Spill Location___________빠",
  "weatherIntialText": "한_<br />Updated once a spill location has been idenitified__________________빠",
  "temperature": "한_Temperature____빠",
  "wind": "한_Wind__빠",
  "c": "한_C_빠",
  "f": "한_F_빠",
  "weatherErrorMessage": "한_Weather info not obtained. Update Wind Speed and Time of Spill values manually________________________빠",
  "windDirection": "한_Wind Direction (blowing to)_________빠",
  "timeOfSpill": "한_Time of Spill_____빠",
  "day": "한_Day__빠",
  "night": "한_Night___빠",
  "windSpeed": "한_Wind Speed____빠",
  "low": "한_Low__빠",
  "moderate": "한_Moderate___빠",
  "high": "한_High__빠",
  "transportContainer": "한_Transport Container_______빠",
  "rail": "한_Rail tank car_____빠",
  "semi": "한_Highway tank truck or trailer__________빠",
  "mton": "한_Multiple ton cylinders________빠",
  "ston": "한_Multiple small cylinders or single ton cylinder_______________빠",
  "ag": "한_Agricultural nurse tank________빠",
  "msm": "한_Multiple small cylinders________빠",
  "bleveLabel": "한_Show BLEVE Isolation Zone_________빠",
  "capacity": "한_Container Capacity (litres)_________빠",
  "bleveMessage": "한_For the material you have selected an additional evacuation distance can be shown for BLEVE.\n\nTo enable this, set the Show BLEVE Isolation Zone toggle to on and select the appropiate container capacity______________________________________________________________빠.",
  "noPAZoneMessage": "한_There are no Protective Action distances for this material. Only the Initial Isolation and evacuation zones has been calculated_______________________________________빠",
  "settingsTitle": "한_Settings___빠",
  "spillLocationLabel": "한_Spill Location_____빠",
  "spillLocationButtonLabel": "한_Configure Spill Location Settings___________빠",
  "IISettingsLabel": "한_Initial Isolation Zone________빠",
  "IIButtonLabel": "한_Configure Initial Isolation Settings____________빠",
  "PASettingsLabel": "한_Protective Action Zone________빠",
  "PAButtonLabel": "한_Configure Protective Action Settings____________빠",
  "downwindSettingsLabel": "한_Down Wind Zone_____빠",
  "downwindButtonLabel": "한_Configure Down Wind Settings_________빠",
  "fireSettingsLabel": "한_Fire Isolation Zone_______빠",
  "fireButtonLabel": "한_Configure Fire Isolation Settings___________빠",
  "bleveSettingsLabel": "한_BLEVE Isolation Zone_______빠",
  "bleveButtonLabel": "한_Configure BLEVE Settings________빠",
  "outlineStyle": "한_Outline Style_____빠",
  "dash": "한_Dash__빠",
  "dashdot": "한_Dash Dot___빠",
  "dashdotdot": "한_Dash Dot Dot_____빠",
  "dot": "한_Dot__빠",
  "longdash": "한_Long Dash____빠",
  "longdashdot": "한_Long Dash Dot_____빠",
  "null": "한_Null__빠",
  "shortdash": "한_Short Dash____빠",
  "shortdashdot": "한_Short Dash Dot_____빠",
  "shortdashdotdot": "한_Short Dash Dot Dot______빠",
  "shortdot": "한_Short Dot____빠",
  "solid": "한_Solid___빠",
  "fillStyle": "한_Fill Style____빠",
  "backward": "한_Backward___빠",
  "cross": "한_Cross___빠",
  "diagonal": "한_Diagonal___빠",
  "forward": "한_Forward___빠",
  "horizontal": "한_Horizontal____빠",
  "vertical": "한_Vertical___빠",
  "resultsTitle": "한_Results___빠",
  "publishERGBtn": "한_Publish___빠",
  "ERGLayerName": "한_Published ERG Layer Name________빠",
  "invalidERGLayerName": "한_Layer name must only contain alpha-numeric characters and underscores______________________빠",
  "missingERGLayerName": "한_You must enter a name for the ERG___________빠",
  "publishingFailedLayerExists": "한_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________빠.",
  "checkService": "한_Check Service: {0}______빠",
  "createService": "한_Create Service: {0}_______빠",
  "unableToCreate": "한_Unable to create: {0}_______빠",
  "addToDefinition": "한_Add to definition: {0}________빠",
  "successfullyPublished": "한_Successfully published web layer{0}Manage the web layer__________________빠",
  "userRole": "한_Unable to create service because user does not have permissions____________________빠",
  "transparency": "한_Transparency_____빠",
  "outline": "한_Outline___빠",
  "fill": "한_Fill (Color only applies when style set to solid)________________빠",
  "createERGBtn": "한_Create Zones_____빠",
  "clearERGBtn": "한_Clear___빠",
  "labelFormat": "한_Label Format_____빠",
  "helpIconTooltip": "한_The threshold between small and large spill sizes are:\nLiquids - 55 gallons (208 liters)\nSolids - 60 pounds (300 kilograms)_______________________________________빠",
  "cellWidth": "한_Cell Width (x)_____빠",
  "cellHeight": "한_Cell Height (y)______빠",
  "invalidNumberMessage": "한_The value entered is not valid__________빠",
  "invalidRangeMessage": "한_Value must be greater than 0_________빠",
  "gridAngleInvalidRangeMessage": "한_Value must be between -89.9 and 89.9____________빠",
  "formatIconTooltip": "한_Format Input_____빠",
  "setCoordFormat": "한_Set Coordinate Format String_________빠",
  "prefixNumbers": "한_Add '+/-' prefix to positive and negative numbers________________빠",
  "cancelBtn": "한_Cancel___빠",
  "applyBtn": "한_Apply___빠",
  "comfirmInputNotation": "한_Confirm Input Notation________빠",
  "notationsMatch": "한_notations match your input please confirm which you would like to use______________________빠:",
  "missingLayerNameMessage": "한_You must enter a valid layer name before you can publish__________________빠",
  "parseCoordinatesError": "한_Unable to parse coordinates. Please check your input_________________빠.",
  "DD": "한_DD__빠",
  "DDM": "한_DDM__빠",
  "DMS": "한_DMS__빠",
  "DDRev": "한_DDRev___빠",
  "DDMRev": "한_DDMRev___빠",
  "DMSRev": "한_DMSRev___빠",
  "USNG": "한_USNG__빠",
  "MGRS": "한_MGRS__빠",
  "UTM_H": "한_UTM (H)___빠",
  "UTM": "한_UTM__빠",
  "GARS": "한_GARS__빠",
  "GEOREF": "한_GEOREF___빠",
  "DDLatLongNotation": "한_Decimal Degrees - Latitude/Longitude____________빠",
  "DDLongLatNotation": "한_Decimal Degrees  - Longitude/Latitude____________빠",
  "DDMLatLongNotation": "한_Degrees Decimal Minutes - Latitude/Longitude______________빠",
  "DDMLongLatNotation": "한_Degrees Decimal Minutes - Longitude/Latitude______________빠",
  "DMSLatLongNotation": "한_Degrees Minutes Seconds - Latitude/Longitude______________빠",
  "DMSLongLatNotation": "한_Degrees Minutes Seconds - Longitude/Latitude______________빠",
  "GARSNotation": "한_GARS__빠",
  "GEOREFNotation": "한_GEOREF___빠",
  "MGRSNotation": "한_MGRS__빠",
  "USNGNotation": "한_USNG__빠",
  "UTMBandNotation": "한_UTM - Band Letter______빠",
  "UTMHemNotation": "한_UTM - Hemisphere (N/S)________빠"
});