define({
  "_widgetLabel": "Ĳ_Emergency Response Guide________ä",
  "ergMainPageTitle": "Ĳ_Based on the Emergency Response Guidebook 2016_______________ä",
  "coordInputLabelStart": "Ĳ_Spill Location (DD)_______ä",
  "coordInputLabel": "Ĳ_Spill Location_____ä",
  "addPointToolTip": "Ĳ_Add Spill Location______ä",
  "drawPointToolTip": "Ĳ_Click to add spill location_________ä",
  "material": "Ĳ_Material___ä",
  "materialPlaceholder": "Ĳ_Start typing to search for a material____________ä",
  "table3Message": "Ĳ_The material you have selected requires additional information if you are dealing with a large spill.\n\nPlease ensure you have the correct values selected for wind speed and transport container____________________________________________________________ä.",
  "table2Message": "Ĳ_The material you have selected may produces a large amount of Toxic Inhalation Hazard gases when spilled in water.\n\nYou may want to consider using the following material(s):\n\n_______________________________________________________ä",
  "spillSize": "Ĳ_Spill Size____ä",
  "small": "Ĳ_Small___ä",
  "large": "Ĳ_Large___ä",
  "fireLabel": "Ĳ_Show Fire Isolation Zone________ä",
  "weatherLabel": "Ĳ_Current Weather at Spill Location___________ä",
  "weatherIntialText": "Ĳ_<br />Updated once a spill location has been idenitified__________________ä",
  "temperature": "Ĳ_Temperature____ä",
  "wind": "Ĳ_Wind__ä",
  "c": "Ĳ_C_ä",
  "f": "Ĳ_F_ä",
  "weatherErrorMessage": "Ĳ_Weather info not obtained. Update Wind Speed and Time of Spill values manually________________________ä",
  "windDirection": "Ĳ_Wind Direction (blowing to)_________ä",
  "timeOfSpill": "Ĳ_Time of Spill_____ä",
  "day": "Ĳ_Day__ä",
  "night": "Ĳ_Night___ä",
  "windSpeed": "Ĳ_Wind Speed____ä",
  "low": "Ĳ_Low__ä",
  "moderate": "Ĳ_Moderate___ä",
  "high": "Ĳ_High__ä",
  "transportContainer": "Ĳ_Transport Container_______ä",
  "rail": "Ĳ_Rail tank car_____ä",
  "semi": "Ĳ_Highway tank truck or trailer__________ä",
  "mton": "Ĳ_Multiple ton cylinders________ä",
  "ston": "Ĳ_Multiple small cylinders or single ton cylinder_______________ä",
  "ag": "Ĳ_Agricultural nurse tank________ä",
  "msm": "Ĳ_Multiple small cylinders________ä",
  "bleveLabel": "Ĳ_Show BLEVE Isolation Zone_________ä",
  "capacity": "Ĳ_Container Capacity (litres)_________ä",
  "bleveMessage": "Ĳ_For the material you have selected an additional evacuation distance can be shown for BLEVE.\n\nTo enable this, set the Show BLEVE Isolation Zone toggle to on and select the appropiate container capacity______________________________________________________________ä.",
  "noPAZoneMessage": "Ĳ_There are no Protective Action distances for this material. Only the Initial Isolation and evacuation zones has been calculated_______________________________________ä",
  "settingsTitle": "Ĳ_Settings___ä",
  "spillLocationLabel": "Ĳ_Spill Location_____ä",
  "spillLocationButtonLabel": "Ĳ_Configure Spill Location Settings___________ä",
  "IISettingsLabel": "Ĳ_Initial Isolation Zone________ä",
  "IIButtonLabel": "Ĳ_Configure Initial Isolation Settings____________ä",
  "PASettingsLabel": "Ĳ_Protective Action Zone________ä",
  "PAButtonLabel": "Ĳ_Configure Protective Action Settings____________ä",
  "downwindSettingsLabel": "Ĳ_Down Wind Zone_____ä",
  "downwindButtonLabel": "Ĳ_Configure Down Wind Settings_________ä",
  "fireSettingsLabel": "Ĳ_Fire Isolation Zone_______ä",
  "fireButtonLabel": "Ĳ_Configure Fire Isolation Settings___________ä",
  "bleveSettingsLabel": "Ĳ_BLEVE Isolation Zone_______ä",
  "bleveButtonLabel": "Ĳ_Configure BLEVE Settings________ä",
  "outlineStyle": "Ĳ_Outline Style_____ä",
  "dash": "Ĳ_Dash__ä",
  "dashdot": "Ĳ_Dash Dot___ä",
  "dashdotdot": "Ĳ_Dash Dot Dot_____ä",
  "dot": "Ĳ_Dot__ä",
  "longdash": "Ĳ_Long Dash____ä",
  "longdashdot": "Ĳ_Long Dash Dot_____ä",
  "null": "Ĳ_Null__ä",
  "shortdash": "Ĳ_Short Dash____ä",
  "shortdashdot": "Ĳ_Short Dash Dot_____ä",
  "shortdashdotdot": "Ĳ_Short Dash Dot Dot______ä",
  "shortdot": "Ĳ_Short Dot____ä",
  "solid": "Ĳ_Solid___ä",
  "fillStyle": "Ĳ_Fill Style____ä",
  "backward": "Ĳ_Backward___ä",
  "cross": "Ĳ_Cross___ä",
  "diagonal": "Ĳ_Diagonal___ä",
  "forward": "Ĳ_Forward___ä",
  "horizontal": "Ĳ_Horizontal____ä",
  "vertical": "Ĳ_Vertical___ä",
  "resultsTitle": "Ĳ_Results___ä",
  "publishERGBtn": "Ĳ_Publish___ä",
  "ERGLayerName": "Ĳ_Published ERG Layer Name________ä",
  "invalidERGLayerName": "Ĳ_Layer name must only contain alpha-numeric characters and underscores______________________ä",
  "missingERGLayerName": "Ĳ_You must enter a name for the ERG___________ä",
  "publishingFailedLayerExists": "Ĳ_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________ä.",
  "checkService": "Ĳ_Check Service: {0}______ä",
  "createService": "Ĳ_Create Service: {0}_______ä",
  "unableToCreate": "Ĳ_Unable to create: {0}_______ä",
  "addToDefinition": "Ĳ_Add to definition: {0}________ä",
  "successfullyPublished": "Ĳ_Successfully published web layer{0}Manage the web layer__________________ä",
  "userRole": "Ĳ_Unable to create service because user does not have permissions____________________ä",
  "transparency": "Ĳ_Transparency_____ä",
  "outline": "Ĳ_Outline___ä",
  "fill": "Ĳ_Fill (Color only applies when style set to solid)________________ä",
  "createERGBtn": "Ĳ_Create Zones_____ä",
  "clearERGBtn": "Ĳ_Clear___ä",
  "labelFormat": "Ĳ_Label Format_____ä",
  "helpIconTooltip": "Ĳ_The threshold between small and large spill sizes are:\nLiquids - 55 gallons (208 liters)\nSolids - 60 pounds (300 kilograms)_______________________________________ä",
  "cellWidth": "Ĳ_Cell Width (x)_____ä",
  "cellHeight": "Ĳ_Cell Height (y)______ä",
  "invalidNumberMessage": "Ĳ_The value entered is not valid__________ä",
  "invalidRangeMessage": "Ĳ_Value must be greater than 0_________ä",
  "gridAngleInvalidRangeMessage": "Ĳ_Value must be between -89.9 and 89.9____________ä",
  "formatIconTooltip": "Ĳ_Format Input_____ä",
  "setCoordFormat": "Ĳ_Set Coordinate Format String_________ä",
  "prefixNumbers": "Ĳ_Add '+/-' prefix to positive and negative numbers________________ä",
  "cancelBtn": "Ĳ_Cancel___ä",
  "applyBtn": "Ĳ_Apply___ä",
  "comfirmInputNotation": "Ĳ_Confirm Input Notation________ä",
  "notationsMatch": "Ĳ_notations match your input please confirm which you would like to use______________________ä:",
  "missingLayerNameMessage": "Ĳ_You must enter a valid layer name before you can publish__________________ä",
  "parseCoordinatesError": "Ĳ_Unable to parse coordinates. Please check your input_________________ä.",
  "DD": "Ĳ_DD__ä",
  "DDM": "Ĳ_DDM__ä",
  "DMS": "Ĳ_DMS__ä",
  "DDRev": "Ĳ_DDRev___ä",
  "DDMRev": "Ĳ_DDMRev___ä",
  "DMSRev": "Ĳ_DMSRev___ä",
  "USNG": "Ĳ_USNG__ä",
  "MGRS": "Ĳ_MGRS__ä",
  "UTM_H": "Ĳ_UTM (H)___ä",
  "UTM": "Ĳ_UTM__ä",
  "GARS": "Ĳ_GARS__ä",
  "GEOREF": "Ĳ_GEOREF___ä",
  "DDLatLongNotation": "Ĳ_Decimal Degrees - Latitude/Longitude____________ä",
  "DDLongLatNotation": "Ĳ_Decimal Degrees  - Longitude/Latitude____________ä",
  "DDMLatLongNotation": "Ĳ_Degrees Decimal Minutes - Latitude/Longitude______________ä",
  "DDMLongLatNotation": "Ĳ_Degrees Decimal Minutes - Longitude/Latitude______________ä",
  "DMSLatLongNotation": "Ĳ_Degrees Minutes Seconds - Latitude/Longitude______________ä",
  "DMSLongLatNotation": "Ĳ_Degrees Minutes Seconds - Longitude/Latitude______________ä",
  "GARSNotation": "Ĳ_GARS__ä",
  "GEOREFNotation": "Ĳ_GEOREF___ä",
  "MGRSNotation": "Ĳ_MGRS__ä",
  "USNGNotation": "Ĳ_USNG__ä",
  "UTMBandNotation": "Ĳ_UTM - Band Letter______ä",
  "UTMHemNotation": "Ĳ_UTM - Hemisphere (N/S)________ä"
});