define({
  "symbolologyTabLabel": "Đ_Configure Symbology_______ớ",
  "facilitiesDescription": "Đ_Facility Layers______ớ",
  "demographicsDescription": "Đ_Demographics Layer______ớ",
  "settingsTitle": "Đ_Settings___ớ",
  "spillLocationLabel": "Đ_Spill Location_____ớ",
  "spillLocationButtonLabel": "Đ_Configure Spill Location Settings___________ớ",
  "IISettingsLabel": "Đ_Initial Isolation Zone________ớ",
  "IIButtonLabel": "Đ_Configure Initial Isolation Settings____________ớ",
  "PASettingsLabel": "Đ_Protective Action Zone________ớ",
  "PAButtonLabel": "Đ_Configure Protective Action Settings____________ớ",
  "downwindSettingsLabel": "Đ_Down Wind Zone_____ớ",
  "downwindButtonLabel": "Đ_Configure Down Wind Settings_________ớ",
  "fireSettingsLabel": "Đ_Fire Isolation Zone_______ớ",
  "fireButtonLabel": "Đ_Configure Fire Isolation Settings___________ớ",
  "bleveSettingsLabel": "Đ_BLEVE Isolation Zone_______ớ",
  "bleveButtonLabel": "Đ_Configure BLEVE Settings________ớ",
  "transparency": "Đ_Transparency_____ớ",
  "outline": "Đ_Outline___ớ",
  "fill": "Đ_Fill (Color only applies when style set to solid)________________ớ",
  "outlineStyle": "Đ_Outline Style_____ớ",
  "dash": "Đ_Dash__ớ",
  "dashdot": "Đ_Dash Dot___ớ",
  "dashdotdot": "Đ_Dash Dot Dot_____ớ",
  "dot": "Đ_Dot__ớ",
  "longdash": "Đ_Long Dash____ớ",
  "longdashdot": "Đ_Long Dash Dot_____ớ",
  "null": "Đ_Null__ớ",
  "shortdash": "Đ_Short Dash____ớ",
  "shortdashdot": "Đ_Short Dash Dot_____ớ",
  "shortdashdotdot": "Đ_Short Dash Dot Dot______ớ",
  "shortdot": "Đ_Short Dot____ớ",
  "solid": "Đ_Solid___ớ",
  "fillStyle": "Đ_Fill Style____ớ",
  "backward": "Đ_Backward___ớ",
  "cross": "Đ_Cross___ớ",
  "diagonal": "Đ_Diagonal___ớ",
  "forward": "Đ_Forward___ớ",
  "horizontal": "Đ_Horizontal____ớ",
  "vertical": "Đ_Vertical___ớ"
});