define({
  "symbolologyTabLabel": "ã_Configure Symbology_______Ç",
  "facilitiesDescription": "ã_Facility Layers______Ç",
  "demographicsDescription": "ã_Demographics Layer______Ç",
  "settingsTitle": "ã_Settings___Ç",
  "spillLocationLabel": "ã_Spill Location_____Ç",
  "spillLocationButtonLabel": "ã_Configure Spill Location Settings___________Ç",
  "IISettingsLabel": "ã_Initial Isolation Zone________Ç",
  "IIButtonLabel": "ã_Configure Initial Isolation Settings____________Ç",
  "PASettingsLabel": "ã_Protective Action Zone________Ç",
  "PAButtonLabel": "ã_Configure Protective Action Settings____________Ç",
  "downwindSettingsLabel": "ã_Down Wind Zone_____Ç",
  "downwindButtonLabel": "ã_Configure Down Wind Settings_________Ç",
  "fireSettingsLabel": "ã_Fire Isolation Zone_______Ç",
  "fireButtonLabel": "ã_Configure Fire Isolation Settings___________Ç",
  "bleveSettingsLabel": "ã_BLEVE Isolation Zone_______Ç",
  "bleveButtonLabel": "ã_Configure BLEVE Settings________Ç",
  "transparency": "ã_Transparency_____Ç",
  "outline": "ã_Outline___Ç",
  "fill": "ã_Fill (Color only applies when style set to solid)________________Ç",
  "outlineStyle": "ã_Outline Style_____Ç",
  "dash": "ã_Dash__Ç",
  "dashdot": "ã_Dash Dot___Ç",
  "dashdotdot": "ã_Dash Dot Dot_____Ç",
  "dot": "ã_Dot__Ç",
  "longdash": "ã_Long Dash____Ç",
  "longdashdot": "ã_Long Dash Dot_____Ç",
  "null": "ã_Null__Ç",
  "shortdash": "ã_Short Dash____Ç",
  "shortdashdot": "ã_Short Dash Dot_____Ç",
  "shortdashdotdot": "ã_Short Dash Dot Dot______Ç",
  "shortdot": "ã_Short Dot____Ç",
  "solid": "ã_Solid___Ç",
  "fillStyle": "ã_Fill Style____Ç",
  "backward": "ã_Backward___Ç",
  "cross": "ã_Cross___Ç",
  "diagonal": "ã_Diagonal___Ç",
  "forward": "ã_Forward___Ç",
  "horizontal": "ã_Horizontal____Ç",
  "vertical": "ã_Vertical___Ç"
});