define({
  "symbolologyTabLabel": "بيت_Configure Symbology_______لاحقة",
  "facilitiesDescription": "بيت_Facility Layers______لاحقة",
  "demographicsDescription": "بيت_Demographics Layer______لاحقة",
  "settingsTitle": "بيت_Settings___لاحقة",
  "spillLocationLabel": "بيت_Spill Location_____لاحقة",
  "spillLocationButtonLabel": "بيت_Configure Spill Location Settings___________لاحقة",
  "IISettingsLabel": "بيت_Initial Isolation Zone________لاحقة",
  "IIButtonLabel": "بيت_Configure Initial Isolation Settings____________لاحقة",
  "PASettingsLabel": "بيت_Protective Action Zone________لاحقة",
  "PAButtonLabel": "بيت_Configure Protective Action Settings____________لاحقة",
  "downwindSettingsLabel": "بيت_Down Wind Zone_____لاحقة",
  "downwindButtonLabel": "بيت_Configure Down Wind Settings_________لاحقة",
  "fireSettingsLabel": "بيت_Fire Isolation Zone_______لاحقة",
  "fireButtonLabel": "بيت_Configure Fire Isolation Settings___________لاحقة",
  "bleveSettingsLabel": "بيت_BLEVE Isolation Zone_______لاحقة",
  "bleveButtonLabel": "بيت_Configure BLEVE Settings________لاحقة",
  "transparency": "بيت_Transparency_____لاحقة",
  "outline": "بيت_Outline___لاحقة",
  "fill": "بيت_Fill (Color only applies when style set to solid)________________لاحقة",
  "outlineStyle": "بيت_Outline Style_____لاحقة",
  "dash": "بيت_Dash__لاحقة",
  "dashdot": "بيت_Dash Dot___لاحقة",
  "dashdotdot": "بيت_Dash Dot Dot_____لاحقة",
  "dot": "بيت_Dot__لاحقة",
  "longdash": "بيت_Long Dash____لاحقة",
  "longdashdot": "بيت_Long Dash Dot_____لاحقة",
  "null": "بيت_Null__لاحقة",
  "shortdash": "بيت_Short Dash____لاحقة",
  "shortdashdot": "بيت_Short Dash Dot_____لاحقة",
  "shortdashdotdot": "بيت_Short Dash Dot Dot______لاحقة",
  "shortdot": "بيت_Short Dot____لاحقة",
  "solid": "بيت_Solid___لاحقة",
  "fillStyle": "بيت_Fill Style____لاحقة",
  "backward": "بيت_Backward___لاحقة",
  "cross": "بيت_Cross___لاحقة",
  "diagonal": "بيت_Diagonal___لاحقة",
  "forward": "بيت_Forward___لاحقة",
  "horizontal": "بيت_Horizontal____لاحقة",
  "vertical": "بيت_Vertical___لاحقة"
});