define({
  "symbolologyTabLabel": "Į_Configure Symbology_______š",
  "facilitiesDescription": "Į_Facility Layers______š",
  "demographicsDescription": "Į_Demographics Layer______š",
  "settingsTitle": "Į_Settings___š",
  "spillLocationLabel": "Į_Spill Location_____š",
  "spillLocationButtonLabel": "Į_Configure Spill Location Settings___________š",
  "IISettingsLabel": "Į_Initial Isolation Zone________š",
  "IIButtonLabel": "Į_Configure Initial Isolation Settings____________š",
  "PASettingsLabel": "Į_Protective Action Zone________š",
  "PAButtonLabel": "Į_Configure Protective Action Settings____________š",
  "downwindSettingsLabel": "Į_Down Wind Zone_____š",
  "downwindButtonLabel": "Į_Configure Down Wind Settings_________š",
  "fireSettingsLabel": "Į_Fire Isolation Zone_______š",
  "fireButtonLabel": "Į_Configure Fire Isolation Settings___________š",
  "bleveSettingsLabel": "Į_BLEVE Isolation Zone_______š",
  "bleveButtonLabel": "Į_Configure BLEVE Settings________š",
  "transparency": "Į_Transparency_____š",
  "outline": "Į_Outline___š",
  "fill": "Į_Fill (Color only applies when style set to solid)________________š",
  "outlineStyle": "Į_Outline Style_____š",
  "dash": "Į_Dash__š",
  "dashdot": "Į_Dash Dot___š",
  "dashdotdot": "Į_Dash Dot Dot_____š",
  "dot": "Į_Dot__š",
  "longdash": "Į_Long Dash____š",
  "longdashdot": "Į_Long Dash Dot_____š",
  "null": "Į_Null__š",
  "shortdash": "Į_Short Dash____š",
  "shortdashdot": "Į_Short Dash Dot_____š",
  "shortdashdotdot": "Į_Short Dash Dot Dot______š",
  "shortdot": "Į_Short Dot____š",
  "solid": "Į_Solid___š",
  "fillStyle": "Į_Fill Style____š",
  "backward": "Į_Backward___š",
  "cross": "Į_Cross___š",
  "diagonal": "Į_Diagonal___š",
  "forward": "Į_Forward___š",
  "horizontal": "Į_Horizontal____š",
  "vertical": "Į_Vertical___š"
});