define({
  "symbolologyTabLabel": "ı_Configure Symbology_______İ",
  "facilitiesDescription": "ı_Facility Layers______İ",
  "demographicsDescription": "ı_Demographics Layer______İ",
  "settingsTitle": "ı_Settings___İ",
  "spillLocationLabel": "ı_Spill Location_____İ",
  "spillLocationButtonLabel": "ı_Configure Spill Location Settings___________İ",
  "IISettingsLabel": "ı_Initial Isolation Zone________İ",
  "IIButtonLabel": "ı_Configure Initial Isolation Settings____________İ",
  "PASettingsLabel": "ı_Protective Action Zone________İ",
  "PAButtonLabel": "ı_Configure Protective Action Settings____________İ",
  "downwindSettingsLabel": "ı_Down Wind Zone_____İ",
  "downwindButtonLabel": "ı_Configure Down Wind Settings_________İ",
  "fireSettingsLabel": "ı_Fire Isolation Zone_______İ",
  "fireButtonLabel": "ı_Configure Fire Isolation Settings___________İ",
  "bleveSettingsLabel": "ı_BLEVE Isolation Zone_______İ",
  "bleveButtonLabel": "ı_Configure BLEVE Settings________İ",
  "transparency": "ı_Transparency_____İ",
  "outline": "ı_Outline___İ",
  "fill": "ı_Fill (Color only applies when style set to solid)________________İ",
  "outlineStyle": "ı_Outline Style_____İ",
  "dash": "ı_Dash__İ",
  "dashdot": "ı_Dash Dot___İ",
  "dashdotdot": "ı_Dash Dot Dot_____İ",
  "dot": "ı_Dot__İ",
  "longdash": "ı_Long Dash____İ",
  "longdashdot": "ı_Long Dash Dot_____İ",
  "null": "ı_Null__İ",
  "shortdash": "ı_Short Dash____İ",
  "shortdashdot": "ı_Short Dash Dot_____İ",
  "shortdashdotdot": "ı_Short Dash Dot Dot______İ",
  "shortdot": "ı_Short Dot____İ",
  "solid": "ı_Solid___İ",
  "fillStyle": "ı_Fill Style____İ",
  "backward": "ı_Backward___İ",
  "cross": "ı_Cross___İ",
  "diagonal": "ı_Diagonal___İ",
  "forward": "ı_Forward___İ",
  "horizontal": "ı_Horizontal____İ",
  "vertical": "ı_Vertical___İ"
});