define({
  "symbolologyTabLabel": "ķ_Configure Symbology_______ū",
  "facilitiesDescription": "ķ_Facility Layers______ū",
  "demographicsDescription": "ķ_Demographics Layer______ū",
  "settingsTitle": "ķ_Settings___ū",
  "spillLocationLabel": "ķ_Spill Location_____ū",
  "spillLocationButtonLabel": "ķ_Configure Spill Location Settings___________ū",
  "IISettingsLabel": "ķ_Initial Isolation Zone________ū",
  "IIButtonLabel": "ķ_Configure Initial Isolation Settings____________ū",
  "PASettingsLabel": "ķ_Protective Action Zone________ū",
  "PAButtonLabel": "ķ_Configure Protective Action Settings____________ū",
  "downwindSettingsLabel": "ķ_Down Wind Zone_____ū",
  "downwindButtonLabel": "ķ_Configure Down Wind Settings_________ū",
  "fireSettingsLabel": "ķ_Fire Isolation Zone_______ū",
  "fireButtonLabel": "ķ_Configure Fire Isolation Settings___________ū",
  "bleveSettingsLabel": "ķ_BLEVE Isolation Zone_______ū",
  "bleveButtonLabel": "ķ_Configure BLEVE Settings________ū",
  "transparency": "ķ_Transparency_____ū",
  "outline": "ķ_Outline___ū",
  "fill": "ķ_Fill (Color only applies when style set to solid)________________ū",
  "outlineStyle": "ķ_Outline Style_____ū",
  "dash": "ķ_Dash__ū",
  "dashdot": "ķ_Dash Dot___ū",
  "dashdotdot": "ķ_Dash Dot Dot_____ū",
  "dot": "ķ_Dot__ū",
  "longdash": "ķ_Long Dash____ū",
  "longdashdot": "ķ_Long Dash Dot_____ū",
  "null": "ķ_Null__ū",
  "shortdash": "ķ_Short Dash____ū",
  "shortdashdot": "ķ_Short Dash Dot_____ū",
  "shortdashdotdot": "ķ_Short Dash Dot Dot______ū",
  "shortdot": "ķ_Short Dot____ū",
  "solid": "ķ_Solid___ū",
  "fillStyle": "ķ_Fill Style____ū",
  "backward": "ķ_Backward___ū",
  "cross": "ķ_Cross___ū",
  "diagonal": "ķ_Diagonal___ū",
  "forward": "ķ_Forward___ū",
  "horizontal": "ķ_Horizontal____ū",
  "vertical": "ķ_Vertical___ū"
});