define({
  "_widgetLabel": "Đ_Emergency Response Guide________ớ",
  "ergMainPageTitle": "Đ_Based on the Emergency Response Guidebook 2016_______________ớ",
  "coordInputLabelStart": "Đ_Spill Location (DD)_______ớ",
  "coordInputLabel": "Đ_Spill Location_____ớ",
  "addPointToolTip": "Đ_Add Spill Location______ớ",
  "drawPointToolTip": "Đ_Click to add spill location_________ớ",
  "material": "Đ_Material___ớ",
  "materialPlaceholder": "Đ_Start typing to search for a material____________ớ",
  "table3Message": "Đ_The material you have selected requires additional information if you are dealing with a large spill.\n\nPlease ensure you have the correct values selected for wind speed and transport container____________________________________________________________ớ.",
  "table2Message": "Đ_The material you have selected may produces a large amount of Toxic Inhalation Hazard gases when spilled in water.\n\nYou may want to consider using the following material(s):\n\n_______________________________________________________ớ",
  "spillSize": "Đ_Spill Size____ớ",
  "small": "Đ_Small___ớ",
  "large": "Đ_Large___ớ",
  "fireLabel": "Đ_Show Fire Isolation Zone________ớ",
  "weatherLabel": "Đ_Current Weather at Spill Location___________ớ",
  "weatherIntialText": "Đ_<br />Updated once a spill location has been idenitified__________________ớ",
  "temperature": "Đ_Temperature____ớ",
  "wind": "Đ_Wind__ớ",
  "c": "Đ_C_ớ",
  "f": "Đ_F_ớ",
  "weatherErrorMessage": "Đ_Weather info not obtained. Update Wind Speed and Time of Spill values manually________________________ớ",
  "windDirection": "Đ_Wind Direction (blowing to)_________ớ",
  "timeOfSpill": "Đ_Time of Spill_____ớ",
  "day": "Đ_Day__ớ",
  "night": "Đ_Night___ớ",
  "windSpeed": "Đ_Wind Speed____ớ",
  "low": "Đ_Low__ớ",
  "moderate": "Đ_Moderate___ớ",
  "high": "Đ_High__ớ",
  "transportContainer": "Đ_Transport Container_______ớ",
  "rail": "Đ_Rail tank car_____ớ",
  "semi": "Đ_Highway tank truck or trailer__________ớ",
  "mton": "Đ_Multiple ton cylinders________ớ",
  "ston": "Đ_Multiple small cylinders or single ton cylinder_______________ớ",
  "ag": "Đ_Agricultural nurse tank________ớ",
  "msm": "Đ_Multiple small cylinders________ớ",
  "bleveLabel": "Đ_Show BLEVE Isolation Zone_________ớ",
  "capacity": "Đ_Container Capacity (litres)_________ớ",
  "bleveMessage": "Đ_For the material you have selected an additional evacuation distance can be shown for BLEVE.\n\nTo enable this, set the Show BLEVE Isolation Zone toggle to on and select the appropiate container capacity______________________________________________________________ớ.",
  "noPAZoneMessage": "Đ_There are no Protective Action distances for this material. Only the Initial Isolation and evacuation zones has been calculated_______________________________________ớ",
  "settingsTitle": "Đ_Settings___ớ",
  "spillLocationLabel": "Đ_Spill Location_____ớ",
  "spillLocationButtonLabel": "Đ_Configure Spill Location Settings___________ớ",
  "IISettingsLabel": "Đ_Initial Isolation Zone________ớ",
  "IIButtonLabel": "Đ_Configure Initial Isolation Settings____________ớ",
  "PASettingsLabel": "Đ_Protective Action Zone________ớ",
  "PAButtonLabel": "Đ_Configure Protective Action Settings____________ớ",
  "downwindSettingsLabel": "Đ_Down Wind Zone_____ớ",
  "downwindButtonLabel": "Đ_Configure Down Wind Settings_________ớ",
  "fireSettingsLabel": "Đ_Fire Isolation Zone_______ớ",
  "fireButtonLabel": "Đ_Configure Fire Isolation Settings___________ớ",
  "bleveSettingsLabel": "Đ_BLEVE Isolation Zone_______ớ",
  "bleveButtonLabel": "Đ_Configure BLEVE Settings________ớ",
  "outlineStyle": "Đ_Outline Style_____ớ",
  "dash": "Đ_Dash__ớ",
  "dashdot": "Đ_Dash Dot___ớ",
  "dashdotdot": "Đ_Dash Dot Dot_____ớ",
  "dot": "Đ_Dot__ớ",
  "longdash": "Đ_Long Dash____ớ",
  "longdashdot": "Đ_Long Dash Dot_____ớ",
  "null": "Đ_Null__ớ",
  "shortdash": "Đ_Short Dash____ớ",
  "shortdashdot": "Đ_Short Dash Dot_____ớ",
  "shortdashdotdot": "Đ_Short Dash Dot Dot______ớ",
  "shortdot": "Đ_Short Dot____ớ",
  "solid": "Đ_Solid___ớ",
  "fillStyle": "Đ_Fill Style____ớ",
  "backward": "Đ_Backward___ớ",
  "cross": "Đ_Cross___ớ",
  "diagonal": "Đ_Diagonal___ớ",
  "forward": "Đ_Forward___ớ",
  "horizontal": "Đ_Horizontal____ớ",
  "vertical": "Đ_Vertical___ớ",
  "resultsTitle": "Đ_Results___ớ",
  "publishERGBtn": "Đ_Publish___ớ",
  "ERGLayerName": "Đ_Published ERG Layer Name________ớ",
  "invalidERGLayerName": "Đ_Layer name must only contain alpha-numeric characters and underscores______________________ớ",
  "missingERGLayerName": "Đ_You must enter a name for the ERG___________ớ",
  "publishingFailedLayerExists": "Đ_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________ớ.",
  "checkService": "Đ_Check Service: {0}______ớ",
  "createService": "Đ_Create Service: {0}_______ớ",
  "unableToCreate": "Đ_Unable to create: {0}_______ớ",
  "addToDefinition": "Đ_Add to definition: {0}________ớ",
  "successfullyPublished": "Đ_Successfully published web layer{0}Manage the web layer__________________ớ",
  "userRole": "Đ_Unable to create service because user does not have permissions____________________ớ",
  "transparency": "Đ_Transparency_____ớ",
  "outline": "Đ_Outline___ớ",
  "fill": "Đ_Fill (Color only applies when style set to solid)________________ớ",
  "createERGBtn": "Đ_Create Zones_____ớ",
  "clearERGBtn": "Đ_Clear___ớ",
  "labelFormat": "Đ_Label Format_____ớ",
  "helpIconTooltip": "Đ_The threshold between small and large spill sizes are:\nLiquids - 55 gallons (208 liters)\nSolids - 60 pounds (300 kilograms)_______________________________________ớ",
  "cellWidth": "Đ_Cell Width (x)_____ớ",
  "cellHeight": "Đ_Cell Height (y)______ớ",
  "invalidNumberMessage": "Đ_The value entered is not valid__________ớ",
  "invalidRangeMessage": "Đ_Value must be greater than 0_________ớ",
  "gridAngleInvalidRangeMessage": "Đ_Value must be between -89.9 and 89.9____________ớ",
  "formatIconTooltip": "Đ_Format Input_____ớ",
  "setCoordFormat": "Đ_Set Coordinate Format String_________ớ",
  "prefixNumbers": "Đ_Add '+/-' prefix to positive and negative numbers________________ớ",
  "cancelBtn": "Đ_Cancel___ớ",
  "applyBtn": "Đ_Apply___ớ",
  "comfirmInputNotation": "Đ_Confirm Input Notation________ớ",
  "notationsMatch": "Đ_notations match your input please confirm which you would like to use______________________ớ:",
  "missingLayerNameMessage": "Đ_You must enter a valid layer name before you can publish__________________ớ",
  "parseCoordinatesError": "Đ_Unable to parse coordinates. Please check your input_________________ớ.",
  "DD": "Đ_DD__ớ",
  "DDM": "Đ_DDM__ớ",
  "DMS": "Đ_DMS__ớ",
  "DDRev": "Đ_DDRev___ớ",
  "DDMRev": "Đ_DDMRev___ớ",
  "DMSRev": "Đ_DMSRev___ớ",
  "USNG": "Đ_USNG__ớ",
  "MGRS": "Đ_MGRS__ớ",
  "UTM_H": "Đ_UTM (H)___ớ",
  "UTM": "Đ_UTM__ớ",
  "GARS": "Đ_GARS__ớ",
  "GEOREF": "Đ_GEOREF___ớ",
  "DDLatLongNotation": "Đ_Decimal Degrees - Latitude/Longitude____________ớ",
  "DDLongLatNotation": "Đ_Decimal Degrees  - Longitude/Latitude____________ớ",
  "DDMLatLongNotation": "Đ_Degrees Decimal Minutes - Latitude/Longitude______________ớ",
  "DDMLongLatNotation": "Đ_Degrees Decimal Minutes - Longitude/Latitude______________ớ",
  "DMSLatLongNotation": "Đ_Degrees Minutes Seconds - Latitude/Longitude______________ớ",
  "DMSLongLatNotation": "Đ_Degrees Minutes Seconds - Longitude/Latitude______________ớ",
  "GARSNotation": "Đ_GARS__ớ",
  "GEOREFNotation": "Đ_GEOREF___ớ",
  "MGRSNotation": "Đ_MGRS__ớ",
  "USNGNotation": "Đ_USNG__ớ",
  "UTMBandNotation": "Đ_UTM - Band Letter______ớ",
  "UTMHemNotation": "Đ_UTM - Hemisphere (N/S)________ớ"
});