define({
  "_widgetLabel": "ã_Emergency Response Guide________Ç",
  "ergMainPageTitle": "ã_Based on the Emergency Response Guidebook 2016_______________Ç",
  "coordInputLabelStart": "ã_Spill Location (DD)_______Ç",
  "coordInputLabel": "ã_Spill Location_____Ç",
  "addPointToolTip": "ã_Add Spill Location______Ç",
  "drawPointToolTip": "ã_Click to add spill location_________Ç",
  "material": "ã_Material___Ç",
  "materialPlaceholder": "ã_Start typing to search for a material____________Ç",
  "table3Message": "ã_The material you have selected requires additional information if you are dealing with a large spill.\n\nPlease ensure you have the correct values selected for wind speed and transport container____________________________________________________________Ç.",
  "table2Message": "ã_The material you have selected may produces a large amount of Toxic Inhalation Hazard gases when spilled in water.\n\nYou may want to consider using the following material(s):\n\n_______________________________________________________Ç",
  "spillSize": "ã_Spill Size____Ç",
  "small": "ã_Small___Ç",
  "large": "ã_Large___Ç",
  "fireLabel": "ã_Show Fire Isolation Zone________Ç",
  "weatherLabel": "ã_Current Weather at Spill Location___________Ç",
  "weatherIntialText": "ã_<br />Updated once a spill location has been idenitified__________________Ç",
  "temperature": "ã_Temperature____Ç",
  "wind": "ã_Wind__Ç",
  "c": "ã_C_Ç",
  "f": "ã_F_Ç",
  "weatherErrorMessage": "ã_Weather info not obtained. Update Wind Speed and Time of Spill values manually________________________Ç",
  "windDirection": "ã_Wind Direction (blowing to)_________Ç",
  "timeOfSpill": "ã_Time of Spill_____Ç",
  "day": "ã_Day__Ç",
  "night": "ã_Night___Ç",
  "windSpeed": "ã_Wind Speed____Ç",
  "low": "ã_Low__Ç",
  "moderate": "ã_Moderate___Ç",
  "high": "ã_High__Ç",
  "transportContainer": "ã_Transport Container_______Ç",
  "rail": "ã_Rail tank car_____Ç",
  "semi": "ã_Highway tank truck or trailer__________Ç",
  "mton": "ã_Multiple ton cylinders________Ç",
  "ston": "ã_Multiple small cylinders or single ton cylinder_______________Ç",
  "ag": "ã_Agricultural nurse tank________Ç",
  "msm": "ã_Multiple small cylinders________Ç",
  "bleveLabel": "ã_Show BLEVE Isolation Zone_________Ç",
  "capacity": "ã_Container Capacity (litres)_________Ç",
  "bleveMessage": "ã_For the material you have selected an additional evacuation distance can be shown for BLEVE.\n\nTo enable this, set the Show BLEVE Isolation Zone toggle to on and select the appropiate container capacity______________________________________________________________Ç.",
  "noPAZoneMessage": "ã_There are no Protective Action distances for this material. Only the Initial Isolation and evacuation zones has been calculated_______________________________________Ç",
  "settingsTitle": "ã_Settings___Ç",
  "spillLocationLabel": "ã_Spill Location_____Ç",
  "spillLocationButtonLabel": "ã_Configure Spill Location Settings___________Ç",
  "IISettingsLabel": "ã_Initial Isolation Zone________Ç",
  "IIButtonLabel": "ã_Configure Initial Isolation Settings____________Ç",
  "PASettingsLabel": "ã_Protective Action Zone________Ç",
  "PAButtonLabel": "ã_Configure Protective Action Settings____________Ç",
  "downwindSettingsLabel": "ã_Down Wind Zone_____Ç",
  "downwindButtonLabel": "ã_Configure Down Wind Settings_________Ç",
  "fireSettingsLabel": "ã_Fire Isolation Zone_______Ç",
  "fireButtonLabel": "ã_Configure Fire Isolation Settings___________Ç",
  "bleveSettingsLabel": "ã_BLEVE Isolation Zone_______Ç",
  "bleveButtonLabel": "ã_Configure BLEVE Settings________Ç",
  "outlineStyle": "ã_Outline Style_____Ç",
  "dash": "ã_Dash__Ç",
  "dashdot": "ã_Dash Dot___Ç",
  "dashdotdot": "ã_Dash Dot Dot_____Ç",
  "dot": "ã_Dot__Ç",
  "longdash": "ã_Long Dash____Ç",
  "longdashdot": "ã_Long Dash Dot_____Ç",
  "null": "ã_Null__Ç",
  "shortdash": "ã_Short Dash____Ç",
  "shortdashdot": "ã_Short Dash Dot_____Ç",
  "shortdashdotdot": "ã_Short Dash Dot Dot______Ç",
  "shortdot": "ã_Short Dot____Ç",
  "solid": "ã_Solid___Ç",
  "fillStyle": "ã_Fill Style____Ç",
  "backward": "ã_Backward___Ç",
  "cross": "ã_Cross___Ç",
  "diagonal": "ã_Diagonal___Ç",
  "forward": "ã_Forward___Ç",
  "horizontal": "ã_Horizontal____Ç",
  "vertical": "ã_Vertical___Ç",
  "resultsTitle": "ã_Results___Ç",
  "publishERGBtn": "ã_Publish___Ç",
  "ERGLayerName": "ã_Published ERG Layer Name________Ç",
  "invalidERGLayerName": "ã_Layer name must only contain alpha-numeric characters and underscores______________________Ç",
  "missingERGLayerName": "ã_You must enter a name for the ERG___________Ç",
  "publishingFailedLayerExists": "ã_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________Ç.",
  "checkService": "ã_Check Service: {0}______Ç",
  "createService": "ã_Create Service: {0}_______Ç",
  "unableToCreate": "ã_Unable to create: {0}_______Ç",
  "addToDefinition": "ã_Add to definition: {0}________Ç",
  "successfullyPublished": "ã_Successfully published web layer{0}Manage the web layer__________________Ç",
  "userRole": "ã_Unable to create service because user does not have permissions____________________Ç",
  "transparency": "ã_Transparency_____Ç",
  "outline": "ã_Outline___Ç",
  "fill": "ã_Fill (Color only applies when style set to solid)________________Ç",
  "createERGBtn": "ã_Create Zones_____Ç",
  "clearERGBtn": "ã_Clear___Ç",
  "labelFormat": "ã_Label Format_____Ç",
  "helpIconTooltip": "ã_The threshold between small and large spill sizes are:\nLiquids - 55 gallons (208 liters)\nSolids - 60 pounds (300 kilograms)_______________________________________Ç",
  "cellWidth": "ã_Cell Width (x)_____Ç",
  "cellHeight": "ã_Cell Height (y)______Ç",
  "invalidNumberMessage": "ã_The value entered is not valid__________Ç",
  "invalidRangeMessage": "ã_Value must be greater than 0_________Ç",
  "gridAngleInvalidRangeMessage": "ã_Value must be between -89.9 and 89.9____________Ç",
  "formatIconTooltip": "ã_Format Input_____Ç",
  "setCoordFormat": "ã_Set Coordinate Format String_________Ç",
  "prefixNumbers": "ã_Add '+/-' prefix to positive and negative numbers________________Ç",
  "cancelBtn": "ã_Cancel___Ç",
  "applyBtn": "ã_Apply___Ç",
  "comfirmInputNotation": "ã_Confirm Input Notation________Ç",
  "notationsMatch": "ã_notations match your input please confirm which you would like to use______________________Ç:",
  "missingLayerNameMessage": "ã_You must enter a valid layer name before you can publish__________________Ç",
  "parseCoordinatesError": "ã_Unable to parse coordinates. Please check your input_________________Ç.",
  "DD": "ã_DD__Ç",
  "DDM": "ã_DDM__Ç",
  "DMS": "ã_DMS__Ç",
  "DDRev": "ã_DDRev___Ç",
  "DDMRev": "ã_DDMRev___Ç",
  "DMSRev": "ã_DMSRev___Ç",
  "USNG": "ã_USNG__Ç",
  "MGRS": "ã_MGRS__Ç",
  "UTM_H": "ã_UTM (H)___Ç",
  "UTM": "ã_UTM__Ç",
  "GARS": "ã_GARS__Ç",
  "GEOREF": "ã_GEOREF___Ç",
  "DDLatLongNotation": "ã_Decimal Degrees - Latitude/Longitude____________Ç",
  "DDLongLatNotation": "ã_Decimal Degrees  - Longitude/Latitude____________Ç",
  "DDMLatLongNotation": "ã_Degrees Decimal Minutes - Latitude/Longitude______________Ç",
  "DDMLongLatNotation": "ã_Degrees Decimal Minutes - Longitude/Latitude______________Ç",
  "DMSLatLongNotation": "ã_Degrees Minutes Seconds - Latitude/Longitude______________Ç",
  "DMSLongLatNotation": "ã_Degrees Minutes Seconds - Longitude/Latitude______________Ç",
  "GARSNotation": "ã_GARS__Ç",
  "GEOREFNotation": "ã_GEOREF___Ç",
  "MGRSNotation": "ã_MGRS__Ç",
  "USNGNotation": "ã_USNG__Ç",
  "UTMBandNotation": "ã_UTM - Band Letter______Ç",
  "UTMHemNotation": "ã_UTM - Hemisphere (N/S)________Ç"
});