define({
  "symbolologyTabLabel": "æ_Configure Symbology_______Â",
  "facilitiesDescription": "æ_Facility Layers______Â",
  "demographicsDescription": "æ_Demographics Layer______Â",
  "settingsTitle": "æ_Settings___Â",
  "spillLocationLabel": "æ_Spill Location_____Â",
  "spillLocationButtonLabel": "æ_Configure Spill Location Settings___________Â",
  "IISettingsLabel": "æ_Initial Isolation Zone________Â",
  "IIButtonLabel": "æ_Configure Initial Isolation Settings____________Â",
  "PASettingsLabel": "æ_Protective Action Zone________Â",
  "PAButtonLabel": "æ_Configure Protective Action Settings____________Â",
  "downwindSettingsLabel": "æ_Down Wind Zone_____Â",
  "downwindButtonLabel": "æ_Configure Down Wind Settings_________Â",
  "fireSettingsLabel": "æ_Fire Isolation Zone_______Â",
  "fireButtonLabel": "æ_Configure Fire Isolation Settings___________Â",
  "bleveSettingsLabel": "æ_BLEVE Isolation Zone_______Â",
  "bleveButtonLabel": "æ_Configure BLEVE Settings________Â",
  "transparency": "æ_Transparency_____Â",
  "outline": "æ_Outline___Â",
  "fill": "æ_Fill (Color only applies when style set to solid)________________Â",
  "outlineStyle": "æ_Outline Style_____Â",
  "dash": "æ_Dash__Â",
  "dashdot": "æ_Dash Dot___Â",
  "dashdotdot": "æ_Dash Dot Dot_____Â",
  "dot": "æ_Dot__Â",
  "longdash": "æ_Long Dash____Â",
  "longdashdot": "æ_Long Dash Dot_____Â",
  "null": "æ_Null__Â",
  "shortdash": "æ_Short Dash____Â",
  "shortdashdot": "æ_Short Dash Dot_____Â",
  "shortdashdotdot": "æ_Short Dash Dot Dot______Â",
  "shortdot": "æ_Short Dot____Â",
  "solid": "æ_Solid___Â",
  "fillStyle": "æ_Fill Style____Â",
  "backward": "æ_Backward___Â",
  "cross": "æ_Cross___Â",
  "diagonal": "æ_Diagonal___Â",
  "forward": "æ_Forward___Â",
  "horizontal": "æ_Horizontal____Â",
  "vertical": "æ_Vertical___Â"
});