define({
  "_widgetLabel": "å_Emergency Response Guide________ø",
  "ergMainPageTitle": "å_Based on the Emergency Response Guidebook 2016_______________ø",
  "coordInputLabelStart": "å_Spill Location (DD)_______ø",
  "coordInputLabel": "å_Spill Location_____ø",
  "addPointToolTip": "å_Add Spill Location______ø",
  "drawPointToolTip": "å_Click to add spill location_________ø",
  "material": "å_Material___ø",
  "materialPlaceholder": "å_Start typing to search for a material____________ø",
  "table3Message": "å_The material you have selected requires additional information if you are dealing with a large spill.\n\nPlease ensure you have the correct values selected for wind speed and transport container____________________________________________________________ø.",
  "table2Message": "å_The material you have selected may produces a large amount of Toxic Inhalation Hazard gases when spilled in water.\n\nYou may want to consider using the following material(s):\n\n_______________________________________________________ø",
  "spillSize": "å_Spill Size____ø",
  "small": "å_Small___ø",
  "large": "å_Large___ø",
  "fireLabel": "å_Show Fire Isolation Zone________ø",
  "weatherLabel": "å_Current Weather at Spill Location___________ø",
  "weatherIntialText": "å_<br />Updated once a spill location has been idenitified__________________ø",
  "temperature": "å_Temperature____ø",
  "wind": "å_Wind__ø",
  "c": "å_C_ø",
  "f": "å_F_ø",
  "weatherErrorMessage": "å_Weather info not obtained. Update Wind Speed and Time of Spill values manually________________________ø",
  "windDirection": "å_Wind Direction (blowing to)_________ø",
  "timeOfSpill": "å_Time of Spill_____ø",
  "day": "å_Day__ø",
  "night": "å_Night___ø",
  "windSpeed": "å_Wind Speed____ø",
  "low": "å_Low__ø",
  "moderate": "å_Moderate___ø",
  "high": "å_High__ø",
  "transportContainer": "å_Transport Container_______ø",
  "rail": "å_Rail tank car_____ø",
  "semi": "å_Highway tank truck or trailer__________ø",
  "mton": "å_Multiple ton cylinders________ø",
  "ston": "å_Multiple small cylinders or single ton cylinder_______________ø",
  "ag": "å_Agricultural nurse tank________ø",
  "msm": "å_Multiple small cylinders________ø",
  "bleveLabel": "å_Show BLEVE Isolation Zone_________ø",
  "capacity": "å_Container Capacity (litres)_________ø",
  "bleveMessage": "å_For the material you have selected an additional evacuation distance can be shown for BLEVE.\n\nTo enable this, set the Show BLEVE Isolation Zone toggle to on and select the appropiate container capacity______________________________________________________________ø.",
  "noPAZoneMessage": "å_There are no Protective Action distances for this material. Only the Initial Isolation and evacuation zones has been calculated_______________________________________ø",
  "settingsTitle": "å_Settings___ø",
  "spillLocationLabel": "å_Spill Location_____ø",
  "spillLocationButtonLabel": "å_Configure Spill Location Settings___________ø",
  "IISettingsLabel": "å_Initial Isolation Zone________ø",
  "IIButtonLabel": "å_Configure Initial Isolation Settings____________ø",
  "PASettingsLabel": "å_Protective Action Zone________ø",
  "PAButtonLabel": "å_Configure Protective Action Settings____________ø",
  "downwindSettingsLabel": "å_Down Wind Zone_____ø",
  "downwindButtonLabel": "å_Configure Down Wind Settings_________ø",
  "fireSettingsLabel": "å_Fire Isolation Zone_______ø",
  "fireButtonLabel": "å_Configure Fire Isolation Settings___________ø",
  "bleveSettingsLabel": "å_BLEVE Isolation Zone_______ø",
  "bleveButtonLabel": "å_Configure BLEVE Settings________ø",
  "outlineStyle": "å_Outline Style_____ø",
  "dash": "å_Dash__ø",
  "dashdot": "å_Dash Dot___ø",
  "dashdotdot": "å_Dash Dot Dot_____ø",
  "dot": "å_Dot__ø",
  "longdash": "å_Long Dash____ø",
  "longdashdot": "å_Long Dash Dot_____ø",
  "null": "å_Null__ø",
  "shortdash": "å_Short Dash____ø",
  "shortdashdot": "å_Short Dash Dot_____ø",
  "shortdashdotdot": "å_Short Dash Dot Dot______ø",
  "shortdot": "å_Short Dot____ø",
  "solid": "å_Solid___ø",
  "fillStyle": "å_Fill Style____ø",
  "backward": "å_Backward___ø",
  "cross": "å_Cross___ø",
  "diagonal": "å_Diagonal___ø",
  "forward": "å_Forward___ø",
  "horizontal": "å_Horizontal____ø",
  "vertical": "å_Vertical___ø",
  "resultsTitle": "å_Results___ø",
  "publishERGBtn": "å_Publish___ø",
  "ERGLayerName": "å_Published ERG Layer Name________ø",
  "invalidERGLayerName": "å_Layer name must only contain alpha-numeric characters and underscores______________________ø",
  "missingERGLayerName": "å_You must enter a name for the ERG___________ø",
  "publishingFailedLayerExists": "å_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________ø.",
  "checkService": "å_Check Service: {0}______ø",
  "createService": "å_Create Service: {0}_______ø",
  "unableToCreate": "å_Unable to create: {0}_______ø",
  "addToDefinition": "å_Add to definition: {0}________ø",
  "successfullyPublished": "å_Successfully published web layer{0}Manage the web layer__________________ø",
  "userRole": "å_Unable to create service because user does not have permissions____________________ø",
  "transparency": "å_Transparency_____ø",
  "outline": "å_Outline___ø",
  "fill": "å_Fill (Color only applies when style set to solid)________________ø",
  "createERGBtn": "å_Create Zones_____ø",
  "clearERGBtn": "å_Clear___ø",
  "labelFormat": "å_Label Format_____ø",
  "helpIconTooltip": "å_The threshold between small and large spill sizes are:\nLiquids - 55 gallons (208 liters)\nSolids - 60 pounds (300 kilograms)_______________________________________ø",
  "cellWidth": "å_Cell Width (x)_____ø",
  "cellHeight": "å_Cell Height (y)______ø",
  "invalidNumberMessage": "å_The value entered is not valid__________ø",
  "invalidRangeMessage": "å_Value must be greater than 0_________ø",
  "gridAngleInvalidRangeMessage": "å_Value must be between -89.9 and 89.9____________ø",
  "formatIconTooltip": "å_Format Input_____ø",
  "setCoordFormat": "å_Set Coordinate Format String_________ø",
  "prefixNumbers": "å_Add '+/-' prefix to positive and negative numbers________________ø",
  "cancelBtn": "å_Cancel___ø",
  "applyBtn": "å_Apply___ø",
  "comfirmInputNotation": "å_Confirm Input Notation________ø",
  "notationsMatch": "å_notations match your input please confirm which you would like to use______________________ø:",
  "missingLayerNameMessage": "å_You must enter a valid layer name before you can publish__________________ø",
  "parseCoordinatesError": "å_Unable to parse coordinates. Please check your input_________________ø.",
  "DD": "å_DD__ø",
  "DDM": "å_DDM__ø",
  "DMS": "å_DMS__ø",
  "DDRev": "å_DDRev___ø",
  "DDMRev": "å_DDMRev___ø",
  "DMSRev": "å_DMSRev___ø",
  "USNG": "å_USNG__ø",
  "MGRS": "å_MGRS__ø",
  "UTM_H": "å_UTM (H)___ø",
  "UTM": "å_UTM__ø",
  "GARS": "å_GARS__ø",
  "GEOREF": "å_GEOREF___ø",
  "DDLatLongNotation": "å_Decimal Degrees - Latitude/Longitude____________ø",
  "DDLongLatNotation": "å_Decimal Degrees  - Longitude/Latitude____________ø",
  "DDMLatLongNotation": "å_Degrees Decimal Minutes - Latitude/Longitude______________ø",
  "DDMLongLatNotation": "å_Degrees Decimal Minutes - Longitude/Latitude______________ø",
  "DMSLatLongNotation": "å_Degrees Minutes Seconds - Latitude/Longitude______________ø",
  "DMSLongLatNotation": "å_Degrees Minutes Seconds - Longitude/Latitude______________ø",
  "GARSNotation": "å_GARS__ø",
  "GEOREFNotation": "å_GEOREF___ø",
  "MGRSNotation": "å_MGRS__ø",
  "USNGNotation": "å_USNG__ø",
  "UTMBandNotation": "å_UTM - Band Letter______ø",
  "UTMHemNotation": "å_UTM - Hemisphere (N/S)________ø"
});