define({
  "_widgetLabel": "Ř_Emergency Response Guide________ů",
  "ergMainPageTitle": "Ř_Based on the Emergency Response Guidebook 2016_______________ů",
  "coordInputLabelStart": "Ř_Spill Location (DD)_______ů",
  "coordInputLabel": "Ř_Spill Location_____ů",
  "addPointToolTip": "Ř_Add Spill Location______ů",
  "drawPointToolTip": "Ř_Click to add spill location_________ů",
  "material": "Ř_Material___ů",
  "materialPlaceholder": "Ř_Start typing to search for a material____________ů",
  "table3Message": "Ř_The material you have selected requires additional information if you are dealing with a large spill.\n\nPlease ensure you have the correct values selected for wind speed and transport container____________________________________________________________ů.",
  "table2Message": "Ř_The material you have selected may produces a large amount of Toxic Inhalation Hazard gases when spilled in water.\n\nYou may want to consider using the following material(s):\n\n_______________________________________________________ů",
  "spillSize": "Ř_Spill Size____ů",
  "small": "Ř_Small___ů",
  "large": "Ř_Large___ů",
  "fireLabel": "Ř_Show Fire Isolation Zone________ů",
  "weatherLabel": "Ř_Current Weather at Spill Location___________ů",
  "weatherIntialText": "Ř_<br />Updated once a spill location has been idenitified__________________ů",
  "temperature": "Ř_Temperature____ů",
  "wind": "Ř_Wind__ů",
  "c": "Ř_C_ů",
  "f": "Ř_F_ů",
  "weatherErrorMessage": "Ř_Weather info not obtained. Update Wind Speed and Time of Spill values manually________________________ů",
  "windDirection": "Ř_Wind Direction (blowing to)_________ů",
  "timeOfSpill": "Ř_Time of Spill_____ů",
  "day": "Ř_Day__ů",
  "night": "Ř_Night___ů",
  "windSpeed": "Ř_Wind Speed____ů",
  "low": "Ř_Low__ů",
  "moderate": "Ř_Moderate___ů",
  "high": "Ř_High__ů",
  "transportContainer": "Ř_Transport Container_______ů",
  "rail": "Ř_Rail tank car_____ů",
  "semi": "Ř_Highway tank truck or trailer__________ů",
  "mton": "Ř_Multiple ton cylinders________ů",
  "ston": "Ř_Multiple small cylinders or single ton cylinder_______________ů",
  "ag": "Ř_Agricultural nurse tank________ů",
  "msm": "Ř_Multiple small cylinders________ů",
  "bleveLabel": "Ř_Show BLEVE Isolation Zone_________ů",
  "capacity": "Ř_Container Capacity (litres)_________ů",
  "bleveMessage": "Ř_For the material you have selected an additional evacuation distance can be shown for BLEVE.\n\nTo enable this, set the Show BLEVE Isolation Zone toggle to on and select the appropiate container capacity______________________________________________________________ů.",
  "noPAZoneMessage": "Ř_There are no Protective Action distances for this material. Only the Initial Isolation and evacuation zones has been calculated_______________________________________ů",
  "settingsTitle": "Ř_Settings___ů",
  "spillLocationLabel": "Ř_Spill Location_____ů",
  "spillLocationButtonLabel": "Ř_Configure Spill Location Settings___________ů",
  "IISettingsLabel": "Ř_Initial Isolation Zone________ů",
  "IIButtonLabel": "Ř_Configure Initial Isolation Settings____________ů",
  "PASettingsLabel": "Ř_Protective Action Zone________ů",
  "PAButtonLabel": "Ř_Configure Protective Action Settings____________ů",
  "downwindSettingsLabel": "Ř_Down Wind Zone_____ů",
  "downwindButtonLabel": "Ř_Configure Down Wind Settings_________ů",
  "fireSettingsLabel": "Ř_Fire Isolation Zone_______ů",
  "fireButtonLabel": "Ř_Configure Fire Isolation Settings___________ů",
  "bleveSettingsLabel": "Ř_BLEVE Isolation Zone_______ů",
  "bleveButtonLabel": "Ř_Configure BLEVE Settings________ů",
  "outlineStyle": "Ř_Outline Style_____ů",
  "dash": "Ř_Dash__ů",
  "dashdot": "Ř_Dash Dot___ů",
  "dashdotdot": "Ř_Dash Dot Dot_____ů",
  "dot": "Ř_Dot__ů",
  "longdash": "Ř_Long Dash____ů",
  "longdashdot": "Ř_Long Dash Dot_____ů",
  "null": "Ř_Null__ů",
  "shortdash": "Ř_Short Dash____ů",
  "shortdashdot": "Ř_Short Dash Dot_____ů",
  "shortdashdotdot": "Ř_Short Dash Dot Dot______ů",
  "shortdot": "Ř_Short Dot____ů",
  "solid": "Ř_Solid___ů",
  "fillStyle": "Ř_Fill Style____ů",
  "backward": "Ř_Backward___ů",
  "cross": "Ř_Cross___ů",
  "diagonal": "Ř_Diagonal___ů",
  "forward": "Ř_Forward___ů",
  "horizontal": "Ř_Horizontal____ů",
  "vertical": "Ř_Vertical___ů",
  "resultsTitle": "Ř_Results___ů",
  "publishERGBtn": "Ř_Publish___ů",
  "ERGLayerName": "Ř_Published ERG Layer Name________ů",
  "invalidERGLayerName": "Ř_Layer name must only contain alpha-numeric characters and underscores______________________ů",
  "missingERGLayerName": "Ř_You must enter a name for the ERG___________ů",
  "publishingFailedLayerExists": "Ř_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________ů.",
  "checkService": "Ř_Check Service: {0}______ů",
  "createService": "Ř_Create Service: {0}_______ů",
  "unableToCreate": "Ř_Unable to create: {0}_______ů",
  "addToDefinition": "Ř_Add to definition: {0}________ů",
  "successfullyPublished": "Ř_Successfully published web layer{0}Manage the web layer__________________ů",
  "userRole": "Ř_Unable to create service because user does not have permissions____________________ů",
  "transparency": "Ř_Transparency_____ů",
  "outline": "Ř_Outline___ů",
  "fill": "Ř_Fill (Color only applies when style set to solid)________________ů",
  "createERGBtn": "Ř_Create Zones_____ů",
  "clearERGBtn": "Ř_Clear___ů",
  "labelFormat": "Ř_Label Format_____ů",
  "helpIconTooltip": "Ř_The threshold between small and large spill sizes are:\nLiquids - 55 gallons (208 liters)\nSolids - 60 pounds (300 kilograms)_______________________________________ů",
  "cellWidth": "Ř_Cell Width (x)_____ů",
  "cellHeight": "Ř_Cell Height (y)______ů",
  "invalidNumberMessage": "Ř_The value entered is not valid__________ů",
  "invalidRangeMessage": "Ř_Value must be greater than 0_________ů",
  "gridAngleInvalidRangeMessage": "Ř_Value must be between -89.9 and 89.9____________ů",
  "formatIconTooltip": "Ř_Format Input_____ů",
  "setCoordFormat": "Ř_Set Coordinate Format String_________ů",
  "prefixNumbers": "Ř_Add '+/-' prefix to positive and negative numbers________________ů",
  "cancelBtn": "Ř_Cancel___ů",
  "applyBtn": "Ř_Apply___ů",
  "comfirmInputNotation": "Ř_Confirm Input Notation________ů",
  "notationsMatch": "Ř_notations match your input please confirm which you would like to use______________________ů:",
  "missingLayerNameMessage": "Ř_You must enter a valid layer name before you can publish__________________ů",
  "parseCoordinatesError": "Ř_Unable to parse coordinates. Please check your input_________________ů.",
  "DD": "Ř_DD__ů",
  "DDM": "Ř_DDM__ů",
  "DMS": "Ř_DMS__ů",
  "DDRev": "Ř_DDRev___ů",
  "DDMRev": "Ř_DDMRev___ů",
  "DMSRev": "Ř_DMSRev___ů",
  "USNG": "Ř_USNG__ů",
  "MGRS": "Ř_MGRS__ů",
  "UTM_H": "Ř_UTM (H)___ů",
  "UTM": "Ř_UTM__ů",
  "GARS": "Ř_GARS__ů",
  "GEOREF": "Ř_GEOREF___ů",
  "DDLatLongNotation": "Ř_Decimal Degrees - Latitude/Longitude____________ů",
  "DDLongLatNotation": "Ř_Decimal Degrees  - Longitude/Latitude____________ů",
  "DDMLatLongNotation": "Ř_Degrees Decimal Minutes - Latitude/Longitude______________ů",
  "DDMLongLatNotation": "Ř_Degrees Decimal Minutes - Longitude/Latitude______________ů",
  "DMSLatLongNotation": "Ř_Degrees Minutes Seconds - Latitude/Longitude______________ů",
  "DMSLongLatNotation": "Ř_Degrees Minutes Seconds - Longitude/Latitude______________ů",
  "GARSNotation": "Ř_GARS__ů",
  "GEOREFNotation": "Ř_GEOREF___ů",
  "MGRSNotation": "Ř_MGRS__ů",
  "USNGNotation": "Ř_USNG__ů",
  "UTMBandNotation": "Ř_UTM - Band Letter______ů",
  "UTMHemNotation": "Ř_UTM - Hemisphere (N/S)________ů"
});