define({
  "_widgetLabel": "Š_Emergency Response Guide________č",
  "ergMainPageTitle": "Š_Based on the Emergency Response Guidebook 2016_______________č",
  "coordInputLabelStart": "Š_Spill Location (DD)_______č",
  "coordInputLabel": "Š_Spill Location_____č",
  "addPointToolTip": "Š_Add Spill Location______č",
  "drawPointToolTip": "Š_Click to add spill location_________č",
  "material": "Š_Material___č",
  "materialPlaceholder": "Š_Start typing to search for a material____________č",
  "table3Message": "Š_The material you have selected requires additional information if you are dealing with a large spill.\n\nPlease ensure you have the correct values selected for wind speed and transport container____________________________________________________________č.",
  "table2Message": "Š_The material you have selected may produces a large amount of Toxic Inhalation Hazard gases when spilled in water.\n\nYou may want to consider using the following material(s):\n\n_______________________________________________________č",
  "spillSize": "Š_Spill Size____č",
  "small": "Š_Small___č",
  "large": "Š_Large___č",
  "fireLabel": "Š_Show Fire Isolation Zone________č",
  "weatherLabel": "Š_Current Weather at Spill Location___________č",
  "weatherIntialText": "Š_<br />Updated once a spill location has been idenitified__________________č",
  "temperature": "Š_Temperature____č",
  "wind": "Š_Wind__č",
  "c": "Š_C_č",
  "f": "Š_F_č",
  "weatherErrorMessage": "Š_Weather info not obtained. Update Wind Speed and Time of Spill values manually________________________č",
  "windDirection": "Š_Wind Direction (blowing to)_________č",
  "timeOfSpill": "Š_Time of Spill_____č",
  "day": "Š_Day__č",
  "night": "Š_Night___č",
  "windSpeed": "Š_Wind Speed____č",
  "low": "Š_Low__č",
  "moderate": "Š_Moderate___č",
  "high": "Š_High__č",
  "transportContainer": "Š_Transport Container_______č",
  "rail": "Š_Rail tank car_____č",
  "semi": "Š_Highway tank truck or trailer__________č",
  "mton": "Š_Multiple ton cylinders________č",
  "ston": "Š_Multiple small cylinders or single ton cylinder_______________č",
  "ag": "Š_Agricultural nurse tank________č",
  "msm": "Š_Multiple small cylinders________č",
  "bleveLabel": "Š_Show BLEVE Isolation Zone_________č",
  "capacity": "Š_Container Capacity (litres)_________č",
  "bleveMessage": "Š_For the material you have selected an additional evacuation distance can be shown for BLEVE.\n\nTo enable this, set the Show BLEVE Isolation Zone toggle to on and select the appropiate container capacity______________________________________________________________č.",
  "noPAZoneMessage": "Š_There are no Protective Action distances for this material. Only the Initial Isolation and evacuation zones has been calculated_______________________________________č",
  "settingsTitle": "Š_Settings___č",
  "spillLocationLabel": "Š_Spill Location_____č",
  "spillLocationButtonLabel": "Š_Configure Spill Location Settings___________č",
  "IISettingsLabel": "Š_Initial Isolation Zone________č",
  "IIButtonLabel": "Š_Configure Initial Isolation Settings____________č",
  "PASettingsLabel": "Š_Protective Action Zone________č",
  "PAButtonLabel": "Š_Configure Protective Action Settings____________č",
  "downwindSettingsLabel": "Š_Down Wind Zone_____č",
  "downwindButtonLabel": "Š_Configure Down Wind Settings_________č",
  "fireSettingsLabel": "Š_Fire Isolation Zone_______č",
  "fireButtonLabel": "Š_Configure Fire Isolation Settings___________č",
  "bleveSettingsLabel": "Š_BLEVE Isolation Zone_______č",
  "bleveButtonLabel": "Š_Configure BLEVE Settings________č",
  "outlineStyle": "Š_Outline Style_____č",
  "dash": "Š_Dash__č",
  "dashdot": "Š_Dash Dot___č",
  "dashdotdot": "Š_Dash Dot Dot_____č",
  "dot": "Š_Dot__č",
  "longdash": "Š_Long Dash____č",
  "longdashdot": "Š_Long Dash Dot_____č",
  "null": "Š_Null__č",
  "shortdash": "Š_Short Dash____č",
  "shortdashdot": "Š_Short Dash Dot_____č",
  "shortdashdotdot": "Š_Short Dash Dot Dot______č",
  "shortdot": "Š_Short Dot____č",
  "solid": "Š_Solid___č",
  "fillStyle": "Š_Fill Style____č",
  "backward": "Š_Backward___č",
  "cross": "Š_Cross___č",
  "diagonal": "Š_Diagonal___č",
  "forward": "Š_Forward___č",
  "horizontal": "Š_Horizontal____č",
  "vertical": "Š_Vertical___č",
  "resultsTitle": "Š_Results___č",
  "publishERGBtn": "Š_Publish___č",
  "ERGLayerName": "Š_Published ERG Layer Name________č",
  "invalidERGLayerName": "Š_Layer name must only contain alpha-numeric characters and underscores______________________č",
  "missingERGLayerName": "Š_You must enter a name for the ERG___________č",
  "publishingFailedLayerExists": "Š_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________č.",
  "checkService": "Š_Check Service: {0}______č",
  "createService": "Š_Create Service: {0}_______č",
  "unableToCreate": "Š_Unable to create: {0}_______č",
  "addToDefinition": "Š_Add to definition: {0}________č",
  "successfullyPublished": "Š_Successfully published web layer{0}Manage the web layer__________________č",
  "userRole": "Š_Unable to create service because user does not have permissions____________________č",
  "transparency": "Š_Transparency_____č",
  "outline": "Š_Outline___č",
  "fill": "Š_Fill (Color only applies when style set to solid)________________č",
  "createERGBtn": "Š_Create Zones_____č",
  "clearERGBtn": "Š_Clear___č",
  "labelFormat": "Š_Label Format_____č",
  "helpIconTooltip": "Š_The threshold between small and large spill sizes are:\nLiquids - 55 gallons (208 liters)\nSolids - 60 pounds (300 kilograms)_______________________________________č",
  "cellWidth": "Š_Cell Width (x)_____č",
  "cellHeight": "Š_Cell Height (y)______č",
  "invalidNumberMessage": "Š_The value entered is not valid__________č",
  "invalidRangeMessage": "Š_Value must be greater than 0_________č",
  "gridAngleInvalidRangeMessage": "Š_Value must be between -89.9 and 89.9____________č",
  "formatIconTooltip": "Š_Format Input_____č",
  "setCoordFormat": "Š_Set Coordinate Format String_________č",
  "prefixNumbers": "Š_Add '+/-' prefix to positive and negative numbers________________č",
  "cancelBtn": "Š_Cancel___č",
  "applyBtn": "Š_Apply___č",
  "comfirmInputNotation": "Š_Confirm Input Notation________č",
  "notationsMatch": "Š_notations match your input please confirm which you would like to use______________________č:",
  "missingLayerNameMessage": "Š_You must enter a valid layer name before you can publish__________________č",
  "parseCoordinatesError": "Š_Unable to parse coordinates. Please check your input_________________č.",
  "DD": "Š_DD__č",
  "DDM": "Š_DDM__č",
  "DMS": "Š_DMS__č",
  "DDRev": "Š_DDRev___č",
  "DDMRev": "Š_DDMRev___č",
  "DMSRev": "Š_DMSRev___č",
  "USNG": "Š_USNG__č",
  "MGRS": "Š_MGRS__č",
  "UTM_H": "Š_UTM (H)___č",
  "UTM": "Š_UTM__č",
  "GARS": "Š_GARS__č",
  "GEOREF": "Š_GEOREF___č",
  "DDLatLongNotation": "Š_Decimal Degrees - Latitude/Longitude____________č",
  "DDLongLatNotation": "Š_Decimal Degrees  - Longitude/Latitude____________č",
  "DDMLatLongNotation": "Š_Degrees Decimal Minutes - Latitude/Longitude______________č",
  "DDMLongLatNotation": "Š_Degrees Decimal Minutes - Longitude/Latitude______________č",
  "DMSLatLongNotation": "Š_Degrees Minutes Seconds - Latitude/Longitude______________č",
  "DMSLongLatNotation": "Š_Degrees Minutes Seconds - Longitude/Latitude______________č",
  "GARSNotation": "Š_GARS__č",
  "GEOREFNotation": "Š_GEOREF___č",
  "MGRSNotation": "Š_MGRS__č",
  "USNGNotation": "Š_USNG__č",
  "UTMBandNotation": "Š_UTM - Band Letter______č",
  "UTMHemNotation": "Š_UTM - Hemisphere (N/S)________č"
});