define({
  "_widgetLabel": "Å_Emergency Response Guide________ö",
  "ergMainPageTitle": "Å_Based on the Emergency Response Guidebook 2016_______________ö",
  "coordInputLabelStart": "Å_Spill Location (DD)_______ö",
  "coordInputLabel": "Å_Spill Location_____ö",
  "addPointToolTip": "Å_Add Spill Location______ö",
  "drawPointToolTip": "Å_Click to add spill location_________ö",
  "material": "Å_Material___ö",
  "materialPlaceholder": "Å_Start typing to search for a material____________ö",
  "table3Message": "Å_The material you have selected requires additional information if you are dealing with a large spill.\n\nPlease ensure you have the correct values selected for wind speed and transport container____________________________________________________________ö.",
  "table2Message": "Å_The material you have selected may produces a large amount of Toxic Inhalation Hazard gases when spilled in water.\n\nYou may want to consider using the following material(s):\n\n_______________________________________________________ö",
  "spillSize": "Å_Spill Size____ö",
  "small": "Å_Small___ö",
  "large": "Å_Large___ö",
  "fireLabel": "Å_Show Fire Isolation Zone________ö",
  "weatherLabel": "Å_Current Weather at Spill Location___________ö",
  "weatherIntialText": "Å_<br />Updated once a spill location has been idenitified__________________ö",
  "temperature": "Å_Temperature____ö",
  "wind": "Å_Wind__ö",
  "c": "Å_C_ö",
  "f": "Å_F_ö",
  "weatherErrorMessage": "Å_Weather info not obtained. Update Wind Speed and Time of Spill values manually________________________ö",
  "windDirection": "Å_Wind Direction (blowing to)_________ö",
  "timeOfSpill": "Å_Time of Spill_____ö",
  "day": "Å_Day__ö",
  "night": "Å_Night___ö",
  "windSpeed": "Å_Wind Speed____ö",
  "low": "Å_Low__ö",
  "moderate": "Å_Moderate___ö",
  "high": "Å_High__ö",
  "transportContainer": "Å_Transport Container_______ö",
  "rail": "Å_Rail tank car_____ö",
  "semi": "Å_Highway tank truck or trailer__________ö",
  "mton": "Å_Multiple ton cylinders________ö",
  "ston": "Å_Multiple small cylinders or single ton cylinder_______________ö",
  "ag": "Å_Agricultural nurse tank________ö",
  "msm": "Å_Multiple small cylinders________ö",
  "bleveLabel": "Å_Show BLEVE Isolation Zone_________ö",
  "capacity": "Å_Container Capacity (litres)_________ö",
  "bleveMessage": "Å_For the material you have selected an additional evacuation distance can be shown for BLEVE.\n\nTo enable this, set the Show BLEVE Isolation Zone toggle to on and select the appropiate container capacity______________________________________________________________ö.",
  "noPAZoneMessage": "Å_There are no Protective Action distances for this material. Only the Initial Isolation and evacuation zones has been calculated_______________________________________ö",
  "settingsTitle": "Å_Settings___ö",
  "spillLocationLabel": "Å_Spill Location_____ö",
  "spillLocationButtonLabel": "Å_Configure Spill Location Settings___________ö",
  "IISettingsLabel": "Å_Initial Isolation Zone________ö",
  "IIButtonLabel": "Å_Configure Initial Isolation Settings____________ö",
  "PASettingsLabel": "Å_Protective Action Zone________ö",
  "PAButtonLabel": "Å_Configure Protective Action Settings____________ö",
  "downwindSettingsLabel": "Å_Down Wind Zone_____ö",
  "downwindButtonLabel": "Å_Configure Down Wind Settings_________ö",
  "fireSettingsLabel": "Å_Fire Isolation Zone_______ö",
  "fireButtonLabel": "Å_Configure Fire Isolation Settings___________ö",
  "bleveSettingsLabel": "Å_BLEVE Isolation Zone_______ö",
  "bleveButtonLabel": "Å_Configure BLEVE Settings________ö",
  "outlineStyle": "Å_Outline Style_____ö",
  "dash": "Å_Dash__ö",
  "dashdot": "Å_Dash Dot___ö",
  "dashdotdot": "Å_Dash Dot Dot_____ö",
  "dot": "Å_Dot__ö",
  "longdash": "Å_Long Dash____ö",
  "longdashdot": "Å_Long Dash Dot_____ö",
  "null": "Å_Null__ö",
  "shortdash": "Å_Short Dash____ö",
  "shortdashdot": "Å_Short Dash Dot_____ö",
  "shortdashdotdot": "Å_Short Dash Dot Dot______ö",
  "shortdot": "Å_Short Dot____ö",
  "solid": "Å_Solid___ö",
  "fillStyle": "Å_Fill Style____ö",
  "backward": "Å_Backward___ö",
  "cross": "Å_Cross___ö",
  "diagonal": "Å_Diagonal___ö",
  "forward": "Å_Forward___ö",
  "horizontal": "Å_Horizontal____ö",
  "vertical": "Å_Vertical___ö",
  "resultsTitle": "Å_Results___ö",
  "publishERGBtn": "Å_Publish___ö",
  "ERGLayerName": "Å_Published ERG Layer Name________ö",
  "invalidERGLayerName": "Å_Layer name must only contain alpha-numeric characters and underscores______________________ö",
  "missingERGLayerName": "Å_You must enter a name for the ERG___________ö",
  "publishingFailedLayerExists": "Å_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________ö.",
  "checkService": "Å_Check Service: {0}______ö",
  "createService": "Å_Create Service: {0}_______ö",
  "unableToCreate": "Å_Unable to create: {0}_______ö",
  "addToDefinition": "Å_Add to definition: {0}________ö",
  "successfullyPublished": "Å_Successfully published web layer{0}Manage the web layer__________________ö",
  "userRole": "Å_Unable to create service because user does not have permissions____________________ö",
  "transparency": "Å_Transparency_____ö",
  "outline": "Å_Outline___ö",
  "fill": "Å_Fill (Color only applies when style set to solid)________________ö",
  "createERGBtn": "Å_Create Zones_____ö",
  "clearERGBtn": "Å_Clear___ö",
  "labelFormat": "Å_Label Format_____ö",
  "helpIconTooltip": "Å_The threshold between small and large spill sizes are:\nLiquids - 55 gallons (208 liters)\nSolids - 60 pounds (300 kilograms)_______________________________________ö",
  "cellWidth": "Å_Cell Width (x)_____ö",
  "cellHeight": "Å_Cell Height (y)______ö",
  "invalidNumberMessage": "Å_The value entered is not valid__________ö",
  "invalidRangeMessage": "Å_Value must be greater than 0_________ö",
  "gridAngleInvalidRangeMessage": "Å_Value must be between -89.9 and 89.9____________ö",
  "formatIconTooltip": "Å_Format Input_____ö",
  "setCoordFormat": "Å_Set Coordinate Format String_________ö",
  "prefixNumbers": "Å_Add '+/-' prefix to positive and negative numbers________________ö",
  "cancelBtn": "Å_Cancel___ö",
  "applyBtn": "Å_Apply___ö",
  "comfirmInputNotation": "Å_Confirm Input Notation________ö",
  "notationsMatch": "Å_notations match your input please confirm which you would like to use______________________ö:",
  "missingLayerNameMessage": "Å_You must enter a valid layer name before you can publish__________________ö",
  "parseCoordinatesError": "Å_Unable to parse coordinates. Please check your input_________________ö.",
  "DD": "Å_DD__ö",
  "DDM": "Å_DDM__ö",
  "DMS": "Å_DMS__ö",
  "DDRev": "Å_DDRev___ö",
  "DDMRev": "Å_DDMRev___ö",
  "DMSRev": "Å_DMSRev___ö",
  "USNG": "Å_USNG__ö",
  "MGRS": "Å_MGRS__ö",
  "UTM_H": "Å_UTM (H)___ö",
  "UTM": "Å_UTM__ö",
  "GARS": "Å_GARS__ö",
  "GEOREF": "Å_GEOREF___ö",
  "DDLatLongNotation": "Å_Decimal Degrees - Latitude/Longitude____________ö",
  "DDLongLatNotation": "Å_Decimal Degrees  - Longitude/Latitude____________ö",
  "DDMLatLongNotation": "Å_Degrees Decimal Minutes - Latitude/Longitude______________ö",
  "DDMLongLatNotation": "Å_Degrees Decimal Minutes - Longitude/Latitude______________ö",
  "DMSLatLongNotation": "Å_Degrees Minutes Seconds - Latitude/Longitude______________ö",
  "DMSLongLatNotation": "Å_Degrees Minutes Seconds - Longitude/Latitude______________ö",
  "GARSNotation": "Å_GARS__ö",
  "GEOREFNotation": "Å_GEOREF___ö",
  "MGRSNotation": "Å_MGRS__ö",
  "USNGNotation": "Å_USNG__ö",
  "UTMBandNotation": "Å_UTM - Band Letter______ö",
  "UTMHemNotation": "Å_UTM - Hemisphere (N/S)________ö"
});