define({
  "symbolologyTabLabel": "須_Configure Symbology_______鷗",
  "facilitiesDescription": "須_Facility Layers______鷗",
  "demographicsDescription": "須_Demographics Layer______鷗",
  "settingsTitle": "須_Settings___鷗",
  "spillLocationLabel": "須_Spill Location_____鷗",
  "spillLocationButtonLabel": "須_Configure Spill Location Settings___________鷗",
  "IISettingsLabel": "須_Initial Isolation Zone________鷗",
  "IIButtonLabel": "須_Configure Initial Isolation Settings____________鷗",
  "PASettingsLabel": "須_Protective Action Zone________鷗",
  "PAButtonLabel": "須_Configure Protective Action Settings____________鷗",
  "downwindSettingsLabel": "須_Down Wind Zone_____鷗",
  "downwindButtonLabel": "須_Configure Down Wind Settings_________鷗",
  "fireSettingsLabel": "須_Fire Isolation Zone_______鷗",
  "fireButtonLabel": "須_Configure Fire Isolation Settings___________鷗",
  "bleveSettingsLabel": "須_BLEVE Isolation Zone_______鷗",
  "bleveButtonLabel": "須_Configure BLEVE Settings________鷗",
  "transparency": "須_Transparency_____鷗",
  "outline": "須_Outline___鷗",
  "fill": "須_Fill (Color only applies when style set to solid)________________鷗",
  "outlineStyle": "須_Outline Style_____鷗",
  "dash": "須_Dash__鷗",
  "dashdot": "須_Dash Dot___鷗",
  "dashdotdot": "須_Dash Dot Dot_____鷗",
  "dot": "須_Dot__鷗",
  "longdash": "須_Long Dash____鷗",
  "longdashdot": "須_Long Dash Dot_____鷗",
  "null": "須_Null__鷗",
  "shortdash": "須_Short Dash____鷗",
  "shortdashdot": "須_Short Dash Dot_____鷗",
  "shortdashdotdot": "須_Short Dash Dot Dot______鷗",
  "shortdot": "須_Short Dot____鷗",
  "solid": "須_Solid___鷗",
  "fillStyle": "須_Fill Style____鷗",
  "backward": "須_Backward___鷗",
  "cross": "須_Cross___鷗",
  "diagonal": "須_Diagonal___鷗",
  "forward": "須_Forward___鷗",
  "horizontal": "須_Horizontal____鷗",
  "vertical": "須_Vertical___鷗"
});