define({
  "symbolologyTabLabel": "试_Configure Symbology_______验",
  "facilitiesDescription": "试_Facility Layers______验",
  "demographicsDescription": "试_Demographics Layer______验",
  "settingsTitle": "试_Settings___验",
  "spillLocationLabel": "试_Spill Location_____验",
  "spillLocationButtonLabel": "试_Configure Spill Location Settings___________验",
  "IISettingsLabel": "试_Initial Isolation Zone________验",
  "IIButtonLabel": "试_Configure Initial Isolation Settings____________验",
  "PASettingsLabel": "试_Protective Action Zone________验",
  "PAButtonLabel": "试_Configure Protective Action Settings____________验",
  "downwindSettingsLabel": "试_Down Wind Zone_____验",
  "downwindButtonLabel": "试_Configure Down Wind Settings_________验",
  "fireSettingsLabel": "试_Fire Isolation Zone_______验",
  "fireButtonLabel": "试_Configure Fire Isolation Settings___________验",
  "bleveSettingsLabel": "试_BLEVE Isolation Zone_______验",
  "bleveButtonLabel": "试_Configure BLEVE Settings________验",
  "transparency": "试_Transparency_____验",
  "outline": "试_Outline___验",
  "fill": "试_Fill (Color only applies when style set to solid)________________验",
  "outlineStyle": "试_Outline Style_____验",
  "dash": "试_Dash__验",
  "dashdot": "试_Dash Dot___验",
  "dashdotdot": "试_Dash Dot Dot_____验",
  "dot": "试_Dot__验",
  "longdash": "试_Long Dash____验",
  "longdashdot": "试_Long Dash Dot_____验",
  "null": "试_Null__验",
  "shortdash": "试_Short Dash____验",
  "shortdashdot": "试_Short Dash Dot_____验",
  "shortdashdotdot": "试_Short Dash Dot Dot______验",
  "shortdot": "试_Short Dot____验",
  "solid": "试_Solid___验",
  "fillStyle": "试_Fill Style____验",
  "backward": "试_Backward___验",
  "cross": "试_Cross___验",
  "diagonal": "试_Diagonal___验",
  "forward": "试_Forward___验",
  "horizontal": "试_Horizontal____验",
  "vertical": "试_Vertical___验"
});