define({
  "_widgetLabel": "ø_Emergency Response Guide________å",
  "ergMainPageTitle": "ø_Based on the Emergency Response Guidebook 2016_______________å",
  "coordInputLabelStart": "ø_Spill Location (DD)_______å",
  "coordInputLabel": "ø_Spill Location_____å",
  "addPointToolTip": "ø_Add Spill Location______å",
  "drawPointToolTip": "ø_Click to add spill location_________å",
  "material": "ø_Material___å",
  "materialPlaceholder": "ø_Start typing to search for a material____________å",
  "table3Message": "ø_The material you have selected requires additional information if you are dealing with a large spill.\n\nPlease ensure you have the correct values selected for wind speed and transport container____________________________________________________________å.",
  "table2Message": "ø_The material you have selected may produces a large amount of Toxic Inhalation Hazard gases when spilled in water.\n\nYou may want to consider using the following material(s):\n\n_______________________________________________________å",
  "spillSize": "ø_Spill Size____å",
  "small": "ø_Small___å",
  "large": "ø_Large___å",
  "fireLabel": "ø_Show Fire Isolation Zone________å",
  "weatherLabel": "ø_Current Weather at Spill Location___________å",
  "weatherIntialText": "ø_<br />Updated once a spill location has been idenitified__________________å",
  "temperature": "ø_Temperature____å",
  "wind": "ø_Wind__å",
  "c": "ø_C_å",
  "f": "ø_F_å",
  "weatherErrorMessage": "ø_Weather info not obtained. Update Wind Speed and Time of Spill values manually________________________å",
  "windDirection": "ø_Wind Direction (blowing to)_________å",
  "timeOfSpill": "ø_Time of Spill_____å",
  "day": "ø_Day__å",
  "night": "ø_Night___å",
  "windSpeed": "ø_Wind Speed____å",
  "low": "ø_Low__å",
  "moderate": "ø_Moderate___å",
  "high": "ø_High__å",
  "transportContainer": "ø_Transport Container_______å",
  "rail": "ø_Rail tank car_____å",
  "semi": "ø_Highway tank truck or trailer__________å",
  "mton": "ø_Multiple ton cylinders________å",
  "ston": "ø_Multiple small cylinders or single ton cylinder_______________å",
  "ag": "ø_Agricultural nurse tank________å",
  "msm": "ø_Multiple small cylinders________å",
  "bleveLabel": "ø_Show BLEVE Isolation Zone_________å",
  "capacity": "ø_Container Capacity (litres)_________å",
  "bleveMessage": "ø_For the material you have selected an additional evacuation distance can be shown for BLEVE.\n\nTo enable this, set the Show BLEVE Isolation Zone toggle to on and select the appropiate container capacity______________________________________________________________å.",
  "noPAZoneMessage": "ø_There are no Protective Action distances for this material. Only the Initial Isolation and evacuation zones has been calculated_______________________________________å",
  "settingsTitle": "ø_Settings___å",
  "spillLocationLabel": "ø_Spill Location_____å",
  "spillLocationButtonLabel": "ø_Configure Spill Location Settings___________å",
  "IISettingsLabel": "ø_Initial Isolation Zone________å",
  "IIButtonLabel": "ø_Configure Initial Isolation Settings____________å",
  "PASettingsLabel": "ø_Protective Action Zone________å",
  "PAButtonLabel": "ø_Configure Protective Action Settings____________å",
  "downwindSettingsLabel": "ø_Down Wind Zone_____å",
  "downwindButtonLabel": "ø_Configure Down Wind Settings_________å",
  "fireSettingsLabel": "ø_Fire Isolation Zone_______å",
  "fireButtonLabel": "ø_Configure Fire Isolation Settings___________å",
  "bleveSettingsLabel": "ø_BLEVE Isolation Zone_______å",
  "bleveButtonLabel": "ø_Configure BLEVE Settings________å",
  "outlineStyle": "ø_Outline Style_____å",
  "dash": "ø_Dash__å",
  "dashdot": "ø_Dash Dot___å",
  "dashdotdot": "ø_Dash Dot Dot_____å",
  "dot": "ø_Dot__å",
  "longdash": "ø_Long Dash____å",
  "longdashdot": "ø_Long Dash Dot_____å",
  "null": "ø_Null__å",
  "shortdash": "ø_Short Dash____å",
  "shortdashdot": "ø_Short Dash Dot_____å",
  "shortdashdotdot": "ø_Short Dash Dot Dot______å",
  "shortdot": "ø_Short Dot____å",
  "solid": "ø_Solid___å",
  "fillStyle": "ø_Fill Style____å",
  "backward": "ø_Backward___å",
  "cross": "ø_Cross___å",
  "diagonal": "ø_Diagonal___å",
  "forward": "ø_Forward___å",
  "horizontal": "ø_Horizontal____å",
  "vertical": "ø_Vertical___å",
  "resultsTitle": "ø_Results___å",
  "publishERGBtn": "ø_Publish___å",
  "ERGLayerName": "ø_Published ERG Layer Name________å",
  "invalidERGLayerName": "ø_Layer name must only contain alpha-numeric characters and underscores______________________å",
  "missingERGLayerName": "ø_You must enter a name for the ERG___________å",
  "publishingFailedLayerExists": "ø_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________å.",
  "checkService": "ø_Check Service: {0}______å",
  "createService": "ø_Create Service: {0}_______å",
  "unableToCreate": "ø_Unable to create: {0}_______å",
  "addToDefinition": "ø_Add to definition: {0}________å",
  "successfullyPublished": "ø_Successfully published web layer{0}Manage the web layer__________________å",
  "userRole": "ø_Unable to create service because user does not have permissions____________________å",
  "transparency": "ø_Transparency_____å",
  "outline": "ø_Outline___å",
  "fill": "ø_Fill (Color only applies when style set to solid)________________å",
  "createERGBtn": "ø_Create Zones_____å",
  "clearERGBtn": "ø_Clear___å",
  "labelFormat": "ø_Label Format_____å",
  "helpIconTooltip": "ø_The threshold between small and large spill sizes are:\nLiquids - 55 gallons (208 liters)\nSolids - 60 pounds (300 kilograms)_______________________________________å",
  "cellWidth": "ø_Cell Width (x)_____å",
  "cellHeight": "ø_Cell Height (y)______å",
  "invalidNumberMessage": "ø_The value entered is not valid__________å",
  "invalidRangeMessage": "ø_Value must be greater than 0_________å",
  "gridAngleInvalidRangeMessage": "ø_Value must be between -89.9 and 89.9____________å",
  "formatIconTooltip": "ø_Format Input_____å",
  "setCoordFormat": "ø_Set Coordinate Format String_________å",
  "prefixNumbers": "ø_Add '+/-' prefix to positive and negative numbers________________å",
  "cancelBtn": "ø_Cancel___å",
  "applyBtn": "ø_Apply___å",
  "comfirmInputNotation": "ø_Confirm Input Notation________å",
  "notationsMatch": "ø_notations match your input please confirm which you would like to use______________________å:",
  "missingLayerNameMessage": "ø_You must enter a valid layer name before you can publish__________________å",
  "parseCoordinatesError": "ø_Unable to parse coordinates. Please check your input_________________å.",
  "DD": "ø_DD__å",
  "DDM": "ø_DDM__å",
  "DMS": "ø_DMS__å",
  "DDRev": "ø_DDRev___å",
  "DDMRev": "ø_DDMRev___å",
  "DMSRev": "ø_DMSRev___å",
  "USNG": "ø_USNG__å",
  "MGRS": "ø_MGRS__å",
  "UTM_H": "ø_UTM (H)___å",
  "UTM": "ø_UTM__å",
  "GARS": "ø_GARS__å",
  "GEOREF": "ø_GEOREF___å",
  "DDLatLongNotation": "ø_Decimal Degrees - Latitude/Longitude____________å",
  "DDLongLatNotation": "ø_Decimal Degrees  - Longitude/Latitude____________å",
  "DDMLatLongNotation": "ø_Degrees Decimal Minutes - Latitude/Longitude______________å",
  "DDMLongLatNotation": "ø_Degrees Decimal Minutes - Longitude/Latitude______________å",
  "DMSLatLongNotation": "ø_Degrees Minutes Seconds - Latitude/Longitude______________å",
  "DMSLongLatNotation": "ø_Degrees Minutes Seconds - Longitude/Latitude______________å",
  "GARSNotation": "ø_GARS__å",
  "GEOREFNotation": "ø_GEOREF___å",
  "MGRSNotation": "ø_MGRS__å",
  "USNGNotation": "ø_USNG__å",
  "UTMBandNotation": "ø_UTM - Band Letter______å",
  "UTMHemNotation": "ø_UTM - Hemisphere (N/S)________å"
});