define({
  "symbolologyTabLabel": "é_Configure Symbology_______È",
  "facilitiesDescription": "é_Facility Layers______È",
  "demographicsDescription": "é_Demographics Layer______È",
  "settingsTitle": "é_Settings___È",
  "spillLocationLabel": "é_Spill Location_____È",
  "spillLocationButtonLabel": "é_Configure Spill Location Settings___________È",
  "IISettingsLabel": "é_Initial Isolation Zone________È",
  "IIButtonLabel": "é_Configure Initial Isolation Settings____________È",
  "PASettingsLabel": "é_Protective Action Zone________È",
  "PAButtonLabel": "é_Configure Protective Action Settings____________È",
  "downwindSettingsLabel": "é_Down Wind Zone_____È",
  "downwindButtonLabel": "é_Configure Down Wind Settings_________È",
  "fireSettingsLabel": "é_Fire Isolation Zone_______È",
  "fireButtonLabel": "é_Configure Fire Isolation Settings___________È",
  "bleveSettingsLabel": "é_BLEVE Isolation Zone_______È",
  "bleveButtonLabel": "é_Configure BLEVE Settings________È",
  "transparency": "é_Transparency_____È",
  "outline": "é_Outline___È",
  "fill": "é_Fill (Color only applies when style set to solid)________________È",
  "outlineStyle": "é_Outline Style_____È",
  "dash": "é_Dash__È",
  "dashdot": "é_Dash Dot___È",
  "dashdotdot": "é_Dash Dot Dot_____È",
  "dot": "é_Dot__È",
  "longdash": "é_Long Dash____È",
  "longdashdot": "é_Long Dash Dot_____È",
  "null": "é_Null__È",
  "shortdash": "é_Short Dash____È",
  "shortdashdot": "é_Short Dash Dot_____È",
  "shortdashdotdot": "é_Short Dash Dot Dot______È",
  "shortdot": "é_Short Dot____È",
  "solid": "é_Solid___È",
  "fillStyle": "é_Fill Style____È",
  "backward": "é_Backward___È",
  "cross": "é_Cross___È",
  "diagonal": "é_Diagonal___È",
  "forward": "é_Forward___È",
  "horizontal": "é_Horizontal____È",
  "vertical": "é_Vertical___È"
});