define({
  "_widgetLabel": "ķ_Emergency Response Guide________ū",
  "ergMainPageTitle": "ķ_Based on the Emergency Response Guidebook 2016_______________ū",
  "coordInputLabelStart": "ķ_Spill Location (DD)_______ū",
  "coordInputLabel": "ķ_Spill Location_____ū",
  "addPointToolTip": "ķ_Add Spill Location______ū",
  "drawPointToolTip": "ķ_Click to add spill location_________ū",
  "material": "ķ_Material___ū",
  "materialPlaceholder": "ķ_Start typing to search for a material____________ū",
  "table3Message": "ķ_The material you have selected requires additional information if you are dealing with a large spill.\n\nPlease ensure you have the correct values selected for wind speed and transport container____________________________________________________________ū.",
  "table2Message": "ķ_The material you have selected may produces a large amount of Toxic Inhalation Hazard gases when spilled in water.\n\nYou may want to consider using the following material(s):\n\n_______________________________________________________ū",
  "spillSize": "ķ_Spill Size____ū",
  "small": "ķ_Small___ū",
  "large": "ķ_Large___ū",
  "fireLabel": "ķ_Show Fire Isolation Zone________ū",
  "weatherLabel": "ķ_Current Weather at Spill Location___________ū",
  "weatherIntialText": "ķ_<br />Updated once a spill location has been idenitified__________________ū",
  "temperature": "ķ_Temperature____ū",
  "wind": "ķ_Wind__ū",
  "c": "ķ_C_ū",
  "f": "ķ_F_ū",
  "weatherErrorMessage": "ķ_Weather info not obtained. Update Wind Speed and Time of Spill values manually________________________ū",
  "windDirection": "ķ_Wind Direction (blowing to)_________ū",
  "timeOfSpill": "ķ_Time of Spill_____ū",
  "day": "ķ_Day__ū",
  "night": "ķ_Night___ū",
  "windSpeed": "ķ_Wind Speed____ū",
  "low": "ķ_Low__ū",
  "moderate": "ķ_Moderate___ū",
  "high": "ķ_High__ū",
  "transportContainer": "ķ_Transport Container_______ū",
  "rail": "ķ_Rail tank car_____ū",
  "semi": "ķ_Highway tank truck or trailer__________ū",
  "mton": "ķ_Multiple ton cylinders________ū",
  "ston": "ķ_Multiple small cylinders or single ton cylinder_______________ū",
  "ag": "ķ_Agricultural nurse tank________ū",
  "msm": "ķ_Multiple small cylinders________ū",
  "bleveLabel": "ķ_Show BLEVE Isolation Zone_________ū",
  "capacity": "ķ_Container Capacity (litres)_________ū",
  "bleveMessage": "ķ_For the material you have selected an additional evacuation distance can be shown for BLEVE.\n\nTo enable this, set the Show BLEVE Isolation Zone toggle to on and select the appropiate container capacity______________________________________________________________ū.",
  "noPAZoneMessage": "ķ_There are no Protective Action distances for this material. Only the Initial Isolation and evacuation zones has been calculated_______________________________________ū",
  "settingsTitle": "ķ_Settings___ū",
  "spillLocationLabel": "ķ_Spill Location_____ū",
  "spillLocationButtonLabel": "ķ_Configure Spill Location Settings___________ū",
  "IISettingsLabel": "ķ_Initial Isolation Zone________ū",
  "IIButtonLabel": "ķ_Configure Initial Isolation Settings____________ū",
  "PASettingsLabel": "ķ_Protective Action Zone________ū",
  "PAButtonLabel": "ķ_Configure Protective Action Settings____________ū",
  "downwindSettingsLabel": "ķ_Down Wind Zone_____ū",
  "downwindButtonLabel": "ķ_Configure Down Wind Settings_________ū",
  "fireSettingsLabel": "ķ_Fire Isolation Zone_______ū",
  "fireButtonLabel": "ķ_Configure Fire Isolation Settings___________ū",
  "bleveSettingsLabel": "ķ_BLEVE Isolation Zone_______ū",
  "bleveButtonLabel": "ķ_Configure BLEVE Settings________ū",
  "outlineStyle": "ķ_Outline Style_____ū",
  "dash": "ķ_Dash__ū",
  "dashdot": "ķ_Dash Dot___ū",
  "dashdotdot": "ķ_Dash Dot Dot_____ū",
  "dot": "ķ_Dot__ū",
  "longdash": "ķ_Long Dash____ū",
  "longdashdot": "ķ_Long Dash Dot_____ū",
  "null": "ķ_Null__ū",
  "shortdash": "ķ_Short Dash____ū",
  "shortdashdot": "ķ_Short Dash Dot_____ū",
  "shortdashdotdot": "ķ_Short Dash Dot Dot______ū",
  "shortdot": "ķ_Short Dot____ū",
  "solid": "ķ_Solid___ū",
  "fillStyle": "ķ_Fill Style____ū",
  "backward": "ķ_Backward___ū",
  "cross": "ķ_Cross___ū",
  "diagonal": "ķ_Diagonal___ū",
  "forward": "ķ_Forward___ū",
  "horizontal": "ķ_Horizontal____ū",
  "vertical": "ķ_Vertical___ū",
  "resultsTitle": "ķ_Results___ū",
  "publishERGBtn": "ķ_Publish___ū",
  "ERGLayerName": "ķ_Published ERG Layer Name________ū",
  "invalidERGLayerName": "ķ_Layer name must only contain alpha-numeric characters and underscores______________________ū",
  "missingERGLayerName": "ķ_You must enter a name for the ERG___________ū",
  "publishingFailedLayerExists": "ķ_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________ū.",
  "checkService": "ķ_Check Service: {0}______ū",
  "createService": "ķ_Create Service: {0}_______ū",
  "unableToCreate": "ķ_Unable to create: {0}_______ū",
  "addToDefinition": "ķ_Add to definition: {0}________ū",
  "successfullyPublished": "ķ_Successfully published web layer{0}Manage the web layer__________________ū",
  "userRole": "ķ_Unable to create service because user does not have permissions____________________ū",
  "transparency": "ķ_Transparency_____ū",
  "outline": "ķ_Outline___ū",
  "fill": "ķ_Fill (Color only applies when style set to solid)________________ū",
  "createERGBtn": "ķ_Create Zones_____ū",
  "clearERGBtn": "ķ_Clear___ū",
  "labelFormat": "ķ_Label Format_____ū",
  "helpIconTooltip": "ķ_The threshold between small and large spill sizes are:\nLiquids - 55 gallons (208 liters)\nSolids - 60 pounds (300 kilograms)_______________________________________ū",
  "cellWidth": "ķ_Cell Width (x)_____ū",
  "cellHeight": "ķ_Cell Height (y)______ū",
  "invalidNumberMessage": "ķ_The value entered is not valid__________ū",
  "invalidRangeMessage": "ķ_Value must be greater than 0_________ū",
  "gridAngleInvalidRangeMessage": "ķ_Value must be between -89.9 and 89.9____________ū",
  "formatIconTooltip": "ķ_Format Input_____ū",
  "setCoordFormat": "ķ_Set Coordinate Format String_________ū",
  "prefixNumbers": "ķ_Add '+/-' prefix to positive and negative numbers________________ū",
  "cancelBtn": "ķ_Cancel___ū",
  "applyBtn": "ķ_Apply___ū",
  "comfirmInputNotation": "ķ_Confirm Input Notation________ū",
  "notationsMatch": "ķ_notations match your input please confirm which you would like to use______________________ū:",
  "missingLayerNameMessage": "ķ_You must enter a valid layer name before you can publish__________________ū",
  "parseCoordinatesError": "ķ_Unable to parse coordinates. Please check your input_________________ū.",
  "DD": "ķ_DD__ū",
  "DDM": "ķ_DDM__ū",
  "DMS": "ķ_DMS__ū",
  "DDRev": "ķ_DDRev___ū",
  "DDMRev": "ķ_DDMRev___ū",
  "DMSRev": "ķ_DMSRev___ū",
  "USNG": "ķ_USNG__ū",
  "MGRS": "ķ_MGRS__ū",
  "UTM_H": "ķ_UTM (H)___ū",
  "UTM": "ķ_UTM__ū",
  "GARS": "ķ_GARS__ū",
  "GEOREF": "ķ_GEOREF___ū",
  "DDLatLongNotation": "ķ_Decimal Degrees - Latitude/Longitude____________ū",
  "DDLongLatNotation": "ķ_Decimal Degrees  - Longitude/Latitude____________ū",
  "DDMLatLongNotation": "ķ_Degrees Decimal Minutes - Latitude/Longitude______________ū",
  "DDMLongLatNotation": "ķ_Degrees Decimal Minutes - Longitude/Latitude______________ū",
  "DMSLatLongNotation": "ķ_Degrees Minutes Seconds - Latitude/Longitude______________ū",
  "DMSLongLatNotation": "ķ_Degrees Minutes Seconds - Longitude/Latitude______________ū",
  "GARSNotation": "ķ_GARS__ū",
  "GEOREFNotation": "ķ_GEOREF___ū",
  "MGRSNotation": "ķ_MGRS__ū",
  "USNGNotation": "ķ_USNG__ū",
  "UTMBandNotation": "ķ_UTM - Band Letter______ū",
  "UTMHemNotation": "ķ_UTM - Hemisphere (N/S)________ū"
});