define({
  "_widgetLabel": "Š_Emergency Response Guide________ä",
  "ergMainPageTitle": "Š_Based on the Emergency Response Guidebook 2016_______________ä",
  "coordInputLabelStart": "Š_Spill Location (DD)_______ä",
  "coordInputLabel": "Š_Spill Location_____ä",
  "addPointToolTip": "Š_Add Spill Location______ä",
  "drawPointToolTip": "Š_Click to add spill location_________ä",
  "material": "Š_Material___ä",
  "materialPlaceholder": "Š_Start typing to search for a material____________ä",
  "table3Message": "Š_The material you have selected requires additional information if you are dealing with a large spill.\n\nPlease ensure you have the correct values selected for wind speed and transport container____________________________________________________________ä.",
  "table2Message": "Š_The material you have selected may produces a large amount of Toxic Inhalation Hazard gases when spilled in water.\n\nYou may want to consider using the following material(s):\n\n_______________________________________________________ä",
  "spillSize": "Š_Spill Size____ä",
  "small": "Š_Small___ä",
  "large": "Š_Large___ä",
  "fireLabel": "Š_Show Fire Isolation Zone________ä",
  "weatherLabel": "Š_Current Weather at Spill Location___________ä",
  "weatherIntialText": "Š_<br />Updated once a spill location has been idenitified__________________ä",
  "temperature": "Š_Temperature____ä",
  "wind": "Š_Wind__ä",
  "c": "Š_C_ä",
  "f": "Š_F_ä",
  "weatherErrorMessage": "Š_Weather info not obtained. Update Wind Speed and Time of Spill values manually________________________ä",
  "windDirection": "Š_Wind Direction (blowing to)_________ä",
  "timeOfSpill": "Š_Time of Spill_____ä",
  "day": "Š_Day__ä",
  "night": "Š_Night___ä",
  "windSpeed": "Š_Wind Speed____ä",
  "low": "Š_Low__ä",
  "moderate": "Š_Moderate___ä",
  "high": "Š_High__ä",
  "transportContainer": "Š_Transport Container_______ä",
  "rail": "Š_Rail tank car_____ä",
  "semi": "Š_Highway tank truck or trailer__________ä",
  "mton": "Š_Multiple ton cylinders________ä",
  "ston": "Š_Multiple small cylinders or single ton cylinder_______________ä",
  "ag": "Š_Agricultural nurse tank________ä",
  "msm": "Š_Multiple small cylinders________ä",
  "bleveLabel": "Š_Show BLEVE Isolation Zone_________ä",
  "capacity": "Š_Container Capacity (litres)_________ä",
  "bleveMessage": "Š_For the material you have selected an additional evacuation distance can be shown for BLEVE.\n\nTo enable this, set the Show BLEVE Isolation Zone toggle to on and select the appropiate container capacity______________________________________________________________ä.",
  "noPAZoneMessage": "Š_There are no Protective Action distances for this material. Only the Initial Isolation and evacuation zones has been calculated_______________________________________ä",
  "settingsTitle": "Š_Settings___ä",
  "spillLocationLabel": "Š_Spill Location_____ä",
  "spillLocationButtonLabel": "Š_Configure Spill Location Settings___________ä",
  "IISettingsLabel": "Š_Initial Isolation Zone________ä",
  "IIButtonLabel": "Š_Configure Initial Isolation Settings____________ä",
  "PASettingsLabel": "Š_Protective Action Zone________ä",
  "PAButtonLabel": "Š_Configure Protective Action Settings____________ä",
  "downwindSettingsLabel": "Š_Down Wind Zone_____ä",
  "downwindButtonLabel": "Š_Configure Down Wind Settings_________ä",
  "fireSettingsLabel": "Š_Fire Isolation Zone_______ä",
  "fireButtonLabel": "Š_Configure Fire Isolation Settings___________ä",
  "bleveSettingsLabel": "Š_BLEVE Isolation Zone_______ä",
  "bleveButtonLabel": "Š_Configure BLEVE Settings________ä",
  "outlineStyle": "Š_Outline Style_____ä",
  "dash": "Š_Dash__ä",
  "dashdot": "Š_Dash Dot___ä",
  "dashdotdot": "Š_Dash Dot Dot_____ä",
  "dot": "Š_Dot__ä",
  "longdash": "Š_Long Dash____ä",
  "longdashdot": "Š_Long Dash Dot_____ä",
  "null": "Š_Null__ä",
  "shortdash": "Š_Short Dash____ä",
  "shortdashdot": "Š_Short Dash Dot_____ä",
  "shortdashdotdot": "Š_Short Dash Dot Dot______ä",
  "shortdot": "Š_Short Dot____ä",
  "solid": "Š_Solid___ä",
  "fillStyle": "Š_Fill Style____ä",
  "backward": "Š_Backward___ä",
  "cross": "Š_Cross___ä",
  "diagonal": "Š_Diagonal___ä",
  "forward": "Š_Forward___ä",
  "horizontal": "Š_Horizontal____ä",
  "vertical": "Š_Vertical___ä",
  "resultsTitle": "Š_Results___ä",
  "publishERGBtn": "Š_Publish___ä",
  "ERGLayerName": "Š_Published ERG Layer Name________ä",
  "invalidERGLayerName": "Š_Layer name must only contain alpha-numeric characters and underscores______________________ä",
  "missingERGLayerName": "Š_You must enter a name for the ERG___________ä",
  "publishingFailedLayerExists": "Š_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________ä.",
  "checkService": "Š_Check Service: {0}______ä",
  "createService": "Š_Create Service: {0}_______ä",
  "unableToCreate": "Š_Unable to create: {0}_______ä",
  "addToDefinition": "Š_Add to definition: {0}________ä",
  "successfullyPublished": "Š_Successfully published web layer{0}Manage the web layer__________________ä",
  "userRole": "Š_Unable to create service because user does not have permissions____________________ä",
  "transparency": "Š_Transparency_____ä",
  "outline": "Š_Outline___ä",
  "fill": "Š_Fill (Color only applies when style set to solid)________________ä",
  "createERGBtn": "Š_Create Zones_____ä",
  "clearERGBtn": "Š_Clear___ä",
  "labelFormat": "Š_Label Format_____ä",
  "helpIconTooltip": "Š_The threshold between small and large spill sizes are:\nLiquids - 55 gallons (208 liters)\nSolids - 60 pounds (300 kilograms)_______________________________________ä",
  "cellWidth": "Š_Cell Width (x)_____ä",
  "cellHeight": "Š_Cell Height (y)______ä",
  "invalidNumberMessage": "Š_The value entered is not valid__________ä",
  "invalidRangeMessage": "Š_Value must be greater than 0_________ä",
  "gridAngleInvalidRangeMessage": "Š_Value must be between -89.9 and 89.9____________ä",
  "formatIconTooltip": "Š_Format Input_____ä",
  "setCoordFormat": "Š_Set Coordinate Format String_________ä",
  "prefixNumbers": "Š_Add '+/-' prefix to positive and negative numbers________________ä",
  "cancelBtn": "Š_Cancel___ä",
  "applyBtn": "Š_Apply___ä",
  "comfirmInputNotation": "Š_Confirm Input Notation________ä",
  "notationsMatch": "Š_notations match your input please confirm which you would like to use______________________ä:",
  "missingLayerNameMessage": "Š_You must enter a valid layer name before you can publish__________________ä",
  "parseCoordinatesError": "Š_Unable to parse coordinates. Please check your input_________________ä.",
  "DD": "Š_DD__ä",
  "DDM": "Š_DDM__ä",
  "DMS": "Š_DMS__ä",
  "DDRev": "Š_DDRev___ä",
  "DDMRev": "Š_DDMRev___ä",
  "DMSRev": "Š_DMSRev___ä",
  "USNG": "Š_USNG__ä",
  "MGRS": "Š_MGRS__ä",
  "UTM_H": "Š_UTM (H)___ä",
  "UTM": "Š_UTM__ä",
  "GARS": "Š_GARS__ä",
  "GEOREF": "Š_GEOREF___ä",
  "DDLatLongNotation": "Š_Decimal Degrees - Latitude/Longitude____________ä",
  "DDLongLatNotation": "Š_Decimal Degrees  - Longitude/Latitude____________ä",
  "DDMLatLongNotation": "Š_Degrees Decimal Minutes - Latitude/Longitude______________ä",
  "DDMLongLatNotation": "Š_Degrees Decimal Minutes - Longitude/Latitude______________ä",
  "DMSLatLongNotation": "Š_Degrees Minutes Seconds - Latitude/Longitude______________ä",
  "DMSLongLatNotation": "Š_Degrees Minutes Seconds - Longitude/Latitude______________ä",
  "GARSNotation": "Š_GARS__ä",
  "GEOREFNotation": "Š_GEOREF___ä",
  "MGRSNotation": "Š_MGRS__ä",
  "USNGNotation": "Š_USNG__ä",
  "UTMBandNotation": "Š_UTM - Band Letter______ä",
  "UTMHemNotation": "Š_UTM - Hemisphere (N/S)________ä"
});