define({
  "_widgetLabel": "ä_Emergency Response Guide________Ü",
  "ergMainPageTitle": "ä_Based on the Emergency Response Guidebook 2016_______________Ü",
  "coordInputLabelStart": "ä_Spill Location (DD)_______Ü",
  "coordInputLabel": "ä_Spill Location_____Ü",
  "addPointToolTip": "ä_Add Spill Location______Ü",
  "drawPointToolTip": "ä_Click to add spill location_________Ü",
  "material": "ä_Material___Ü",
  "materialPlaceholder": "ä_Start typing to search for a material____________Ü",
  "table3Message": "ä_The material you have selected requires additional information if you are dealing with a large spill.\n\nPlease ensure you have the correct values selected for wind speed and transport container____________________________________________________________Ü.",
  "table2Message": "ä_The material you have selected may produces a large amount of Toxic Inhalation Hazard gases when spilled in water.\n\nYou may want to consider using the following material(s):\n\n_______________________________________________________Ü",
  "spillSize": "ä_Spill Size____Ü",
  "small": "ä_Small___Ü",
  "large": "ä_Large___Ü",
  "fireLabel": "ä_Show Fire Isolation Zone________Ü",
  "weatherLabel": "ä_Current Weather at Spill Location___________Ü",
  "weatherIntialText": "ä_<br />Updated once a spill location has been idenitified__________________Ü",
  "temperature": "ä_Temperature____Ü",
  "wind": "ä_Wind__Ü",
  "c": "ä_C_Ü",
  "f": "ä_F_Ü",
  "weatherErrorMessage": "ä_Weather info not obtained. Update Wind Speed and Time of Spill values manually________________________Ü",
  "windDirection": "ä_Wind Direction (blowing to)_________Ü",
  "timeOfSpill": "ä_Time of Spill_____Ü",
  "day": "ä_Day__Ü",
  "night": "ä_Night___Ü",
  "windSpeed": "ä_Wind Speed____Ü",
  "low": "ä_Low__Ü",
  "moderate": "ä_Moderate___Ü",
  "high": "ä_High__Ü",
  "transportContainer": "ä_Transport Container_______Ü",
  "rail": "ä_Rail tank car_____Ü",
  "semi": "ä_Highway tank truck or trailer__________Ü",
  "mton": "ä_Multiple ton cylinders________Ü",
  "ston": "ä_Multiple small cylinders or single ton cylinder_______________Ü",
  "ag": "ä_Agricultural nurse tank________Ü",
  "msm": "ä_Multiple small cylinders________Ü",
  "bleveLabel": "ä_Show BLEVE Isolation Zone_________Ü",
  "capacity": "ä_Container Capacity (litres)_________Ü",
  "bleveMessage": "ä_For the material you have selected an additional evacuation distance can be shown for BLEVE.\n\nTo enable this, set the Show BLEVE Isolation Zone toggle to on and select the appropiate container capacity______________________________________________________________Ü.",
  "noPAZoneMessage": "ä_There are no Protective Action distances for this material. Only the Initial Isolation and evacuation zones has been calculated_______________________________________Ü",
  "settingsTitle": "ä_Settings___Ü",
  "spillLocationLabel": "ä_Spill Location_____Ü",
  "spillLocationButtonLabel": "ä_Configure Spill Location Settings___________Ü",
  "IISettingsLabel": "ä_Initial Isolation Zone________Ü",
  "IIButtonLabel": "ä_Configure Initial Isolation Settings____________Ü",
  "PASettingsLabel": "ä_Protective Action Zone________Ü",
  "PAButtonLabel": "ä_Configure Protective Action Settings____________Ü",
  "downwindSettingsLabel": "ä_Down Wind Zone_____Ü",
  "downwindButtonLabel": "ä_Configure Down Wind Settings_________Ü",
  "fireSettingsLabel": "ä_Fire Isolation Zone_______Ü",
  "fireButtonLabel": "ä_Configure Fire Isolation Settings___________Ü",
  "bleveSettingsLabel": "ä_BLEVE Isolation Zone_______Ü",
  "bleveButtonLabel": "ä_Configure BLEVE Settings________Ü",
  "outlineStyle": "ä_Outline Style_____Ü",
  "dash": "ä_Dash__Ü",
  "dashdot": "ä_Dash Dot___Ü",
  "dashdotdot": "ä_Dash Dot Dot_____Ü",
  "dot": "ä_Dot__Ü",
  "longdash": "ä_Long Dash____Ü",
  "longdashdot": "ä_Long Dash Dot_____Ü",
  "null": "ä_Null__Ü",
  "shortdash": "ä_Short Dash____Ü",
  "shortdashdot": "ä_Short Dash Dot_____Ü",
  "shortdashdotdot": "ä_Short Dash Dot Dot______Ü",
  "shortdot": "ä_Short Dot____Ü",
  "solid": "ä_Solid___Ü",
  "fillStyle": "ä_Fill Style____Ü",
  "backward": "ä_Backward___Ü",
  "cross": "ä_Cross___Ü",
  "diagonal": "ä_Diagonal___Ü",
  "forward": "ä_Forward___Ü",
  "horizontal": "ä_Horizontal____Ü",
  "vertical": "ä_Vertical___Ü",
  "resultsTitle": "ä_Results___Ü",
  "publishERGBtn": "ä_Publish___Ü",
  "ERGLayerName": "ä_Published ERG Layer Name________Ü",
  "invalidERGLayerName": "ä_Layer name must only contain alpha-numeric characters and underscores______________________Ü",
  "missingERGLayerName": "ä_You must enter a name for the ERG___________Ü",
  "publishingFailedLayerExists": "ä_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________Ü.",
  "checkService": "ä_Check Service: {0}______Ü",
  "createService": "ä_Create Service: {0}_______Ü",
  "unableToCreate": "ä_Unable to create: {0}_______Ü",
  "addToDefinition": "ä_Add to definition: {0}________Ü",
  "successfullyPublished": "ä_Successfully published web layer{0}Manage the web layer__________________Ü",
  "userRole": "ä_Unable to create service because user does not have permissions____________________Ü",
  "transparency": "ä_Transparency_____Ü",
  "outline": "ä_Outline___Ü",
  "fill": "ä_Fill (Color only applies when style set to solid)________________Ü",
  "createERGBtn": "ä_Create Zones_____Ü",
  "clearERGBtn": "ä_Clear___Ü",
  "labelFormat": "ä_Label Format_____Ü",
  "helpIconTooltip": "ä_The threshold between small and large spill sizes are:\nLiquids - 55 gallons (208 liters)\nSolids - 60 pounds (300 kilograms)_______________________________________Ü",
  "cellWidth": "ä_Cell Width (x)_____Ü",
  "cellHeight": "ä_Cell Height (y)______Ü",
  "invalidNumberMessage": "ä_The value entered is not valid__________Ü",
  "invalidRangeMessage": "ä_Value must be greater than 0_________Ü",
  "gridAngleInvalidRangeMessage": "ä_Value must be between -89.9 and 89.9____________Ü",
  "formatIconTooltip": "ä_Format Input_____Ü",
  "setCoordFormat": "ä_Set Coordinate Format String_________Ü",
  "prefixNumbers": "ä_Add '+/-' prefix to positive and negative numbers________________Ü",
  "cancelBtn": "ä_Cancel___Ü",
  "applyBtn": "ä_Apply___Ü",
  "comfirmInputNotation": "ä_Confirm Input Notation________Ü",
  "notationsMatch": "ä_notations match your input please confirm which you would like to use______________________Ü:",
  "missingLayerNameMessage": "ä_You must enter a valid layer name before you can publish__________________Ü",
  "parseCoordinatesError": "ä_Unable to parse coordinates. Please check your input_________________Ü.",
  "DD": "ä_DD__Ü",
  "DDM": "ä_DDM__Ü",
  "DMS": "ä_DMS__Ü",
  "DDRev": "ä_DDRev___Ü",
  "DDMRev": "ä_DDMRev___Ü",
  "DMSRev": "ä_DMSRev___Ü",
  "USNG": "ä_USNG__Ü",
  "MGRS": "ä_MGRS__Ü",
  "UTM_H": "ä_UTM (H)___Ü",
  "UTM": "ä_UTM__Ü",
  "GARS": "ä_GARS__Ü",
  "GEOREF": "ä_GEOREF___Ü",
  "DDLatLongNotation": "ä_Decimal Degrees - Latitude/Longitude____________Ü",
  "DDLongLatNotation": "ä_Decimal Degrees  - Longitude/Latitude____________Ü",
  "DDMLatLongNotation": "ä_Degrees Decimal Minutes - Latitude/Longitude______________Ü",
  "DDMLongLatNotation": "ä_Degrees Decimal Minutes - Longitude/Latitude______________Ü",
  "DMSLatLongNotation": "ä_Degrees Minutes Seconds - Latitude/Longitude______________Ü",
  "DMSLongLatNotation": "ä_Degrees Minutes Seconds - Longitude/Latitude______________Ü",
  "GARSNotation": "ä_GARS__Ü",
  "GEOREFNotation": "ä_GEOREF___Ü",
  "MGRSNotation": "ä_MGRS__Ü",
  "USNGNotation": "ä_USNG__Ü",
  "UTMBandNotation": "ä_UTM - Band Letter______Ü",
  "UTMHemNotation": "ä_UTM - Hemisphere (N/S)________Ü"
});