define({
  "symbolologyTabLabel": "Š_Configure Symbology_______ä",
  "facilitiesDescription": "Š_Facility Layers______ä",
  "demographicsDescription": "Š_Demographics Layer______ä",
  "settingsTitle": "Š_Settings___ä",
  "spillLocationLabel": "Š_Spill Location_____ä",
  "spillLocationButtonLabel": "Š_Configure Spill Location Settings___________ä",
  "IISettingsLabel": "Š_Initial Isolation Zone________ä",
  "IIButtonLabel": "Š_Configure Initial Isolation Settings____________ä",
  "PASettingsLabel": "Š_Protective Action Zone________ä",
  "PAButtonLabel": "Š_Configure Protective Action Settings____________ä",
  "downwindSettingsLabel": "Š_Down Wind Zone_____ä",
  "downwindButtonLabel": "Š_Configure Down Wind Settings_________ä",
  "fireSettingsLabel": "Š_Fire Isolation Zone_______ä",
  "fireButtonLabel": "Š_Configure Fire Isolation Settings___________ä",
  "bleveSettingsLabel": "Š_BLEVE Isolation Zone_______ä",
  "bleveButtonLabel": "Š_Configure BLEVE Settings________ä",
  "transparency": "Š_Transparency_____ä",
  "outline": "Š_Outline___ä",
  "fill": "Š_Fill (Color only applies when style set to solid)________________ä",
  "outlineStyle": "Š_Outline Style_____ä",
  "dash": "Š_Dash__ä",
  "dashdot": "Š_Dash Dot___ä",
  "dashdotdot": "Š_Dash Dot Dot_____ä",
  "dot": "Š_Dot__ä",
  "longdash": "Š_Long Dash____ä",
  "longdashdot": "Š_Long Dash Dot_____ä",
  "null": "Š_Null__ä",
  "shortdash": "Š_Short Dash____ä",
  "shortdashdot": "Š_Short Dash Dot_____ä",
  "shortdashdotdot": "Š_Short Dash Dot Dot______ä",
  "shortdot": "Š_Short Dot____ä",
  "solid": "Š_Solid___ä",
  "fillStyle": "Š_Fill Style____ä",
  "backward": "Š_Backward___ä",
  "cross": "Š_Cross___ä",
  "diagonal": "Š_Diagonal___ä",
  "forward": "Š_Forward___ä",
  "horizontal": "Š_Horizontal____ä",
  "vertical": "Š_Vertical___ä"
});