define({
  "symbolologyTabLabel": "한_Configure Symbology_______빠",
  "facilitiesDescription": "한_Facility Layers______빠",
  "demographicsDescription": "한_Demographics Layer______빠",
  "settingsTitle": "한_Settings___빠",
  "spillLocationLabel": "한_Spill Location_____빠",
  "spillLocationButtonLabel": "한_Configure Spill Location Settings___________빠",
  "IISettingsLabel": "한_Initial Isolation Zone________빠",
  "IIButtonLabel": "한_Configure Initial Isolation Settings____________빠",
  "PASettingsLabel": "한_Protective Action Zone________빠",
  "PAButtonLabel": "한_Configure Protective Action Settings____________빠",
  "downwindSettingsLabel": "한_Down Wind Zone_____빠",
  "downwindButtonLabel": "한_Configure Down Wind Settings_________빠",
  "fireSettingsLabel": "한_Fire Isolation Zone_______빠",
  "fireButtonLabel": "한_Configure Fire Isolation Settings___________빠",
  "bleveSettingsLabel": "한_BLEVE Isolation Zone_______빠",
  "bleveButtonLabel": "한_Configure BLEVE Settings________빠",
  "transparency": "한_Transparency_____빠",
  "outline": "한_Outline___빠",
  "fill": "한_Fill (Color only applies when style set to solid)________________빠",
  "outlineStyle": "한_Outline Style_____빠",
  "dash": "한_Dash__빠",
  "dashdot": "한_Dash Dot___빠",
  "dashdotdot": "한_Dash Dot Dot_____빠",
  "dot": "한_Dot__빠",
  "longdash": "한_Long Dash____빠",
  "longdashdot": "한_Long Dash Dot_____빠",
  "null": "한_Null__빠",
  "shortdash": "한_Short Dash____빠",
  "shortdashdot": "한_Short Dash Dot_____빠",
  "shortdashdotdot": "한_Short Dash Dot Dot______빠",
  "shortdot": "한_Short Dot____빠",
  "solid": "한_Solid___빠",
  "fillStyle": "한_Fill Style____빠",
  "backward": "한_Backward___빠",
  "cross": "한_Cross___빠",
  "diagonal": "한_Diagonal___빠",
  "forward": "한_Forward___빠",
  "horizontal": "한_Horizontal____빠",
  "vertical": "한_Vertical___빠"
});