define({
  "symbolologyTabLabel": "å_Configure Symbology_______ø",
  "facilitiesDescription": "å_Facility Layers______ø",
  "demographicsDescription": "å_Demographics Layer______ø",
  "settingsTitle": "å_Settings___ø",
  "spillLocationLabel": "å_Spill Location_____ø",
  "spillLocationButtonLabel": "å_Configure Spill Location Settings___________ø",
  "IISettingsLabel": "å_Initial Isolation Zone________ø",
  "IIButtonLabel": "å_Configure Initial Isolation Settings____________ø",
  "PASettingsLabel": "å_Protective Action Zone________ø",
  "PAButtonLabel": "å_Configure Protective Action Settings____________ø",
  "downwindSettingsLabel": "å_Down Wind Zone_____ø",
  "downwindButtonLabel": "å_Configure Down Wind Settings_________ø",
  "fireSettingsLabel": "å_Fire Isolation Zone_______ø",
  "fireButtonLabel": "å_Configure Fire Isolation Settings___________ø",
  "bleveSettingsLabel": "å_BLEVE Isolation Zone_______ø",
  "bleveButtonLabel": "å_Configure BLEVE Settings________ø",
  "transparency": "å_Transparency_____ø",
  "outline": "å_Outline___ø",
  "fill": "å_Fill (Color only applies when style set to solid)________________ø",
  "outlineStyle": "å_Outline Style_____ø",
  "dash": "å_Dash__ø",
  "dashdot": "å_Dash Dot___ø",
  "dashdotdot": "å_Dash Dot Dot_____ø",
  "dot": "å_Dot__ø",
  "longdash": "å_Long Dash____ø",
  "longdashdot": "å_Long Dash Dot_____ø",
  "null": "å_Null__ø",
  "shortdash": "å_Short Dash____ø",
  "shortdashdot": "å_Short Dash Dot_____ø",
  "shortdashdotdot": "å_Short Dash Dot Dot______ø",
  "shortdot": "å_Short Dot____ø",
  "solid": "å_Solid___ø",
  "fillStyle": "å_Fill Style____ø",
  "backward": "å_Backward___ø",
  "cross": "å_Cross___ø",
  "diagonal": "å_Diagonal___ø",
  "forward": "å_Forward___ø",
  "horizontal": "å_Horizontal____ø",
  "vertical": "å_Vertical___ø"
});