define({
  "_widgetLabel": "á_Emergency Response Guide________Ó",
  "ergMainPageTitle": "á_Based on the Emergency Response Guidebook 2016_______________Ó",
  "coordInputLabelStart": "á_Spill Location (DD)_______Ó",
  "coordInputLabel": "á_Spill Location_____Ó",
  "addPointToolTip": "á_Add Spill Location______Ó",
  "drawPointToolTip": "á_Click to add spill location_________Ó",
  "material": "á_Material___Ó",
  "materialPlaceholder": "á_Start typing to search for a material____________Ó",
  "table3Message": "á_The material you have selected requires additional information if you are dealing with a large spill.\n\nPlease ensure you have the correct values selected for wind speed and transport container____________________________________________________________Ó.",
  "table2Message": "á_The material you have selected may produces a large amount of Toxic Inhalation Hazard gases when spilled in water.\n\nYou may want to consider using the following material(s):\n\n_______________________________________________________Ó",
  "spillSize": "á_Spill Size____Ó",
  "small": "á_Small___Ó",
  "large": "á_Large___Ó",
  "fireLabel": "á_Show Fire Isolation Zone________Ó",
  "weatherLabel": "á_Current Weather at Spill Location___________Ó",
  "weatherIntialText": "á_<br />Updated once a spill location has been idenitified__________________Ó",
  "temperature": "á_Temperature____Ó",
  "wind": "á_Wind__Ó",
  "c": "á_C_Ó",
  "f": "á_F_Ó",
  "weatherErrorMessage": "á_Weather info not obtained. Update Wind Speed and Time of Spill values manually________________________Ó",
  "windDirection": "á_Wind Direction (blowing to)_________Ó",
  "timeOfSpill": "á_Time of Spill_____Ó",
  "day": "á_Day__Ó",
  "night": "á_Night___Ó",
  "windSpeed": "á_Wind Speed____Ó",
  "low": "á_Low__Ó",
  "moderate": "á_Moderate___Ó",
  "high": "á_High__Ó",
  "transportContainer": "á_Transport Container_______Ó",
  "rail": "á_Rail tank car_____Ó",
  "semi": "á_Highway tank truck or trailer__________Ó",
  "mton": "á_Multiple ton cylinders________Ó",
  "ston": "á_Multiple small cylinders or single ton cylinder_______________Ó",
  "ag": "á_Agricultural nurse tank________Ó",
  "msm": "á_Multiple small cylinders________Ó",
  "bleveLabel": "á_Show BLEVE Isolation Zone_________Ó",
  "capacity": "á_Container Capacity (litres)_________Ó",
  "bleveMessage": "á_For the material you have selected an additional evacuation distance can be shown for BLEVE.\n\nTo enable this, set the Show BLEVE Isolation Zone toggle to on and select the appropiate container capacity______________________________________________________________Ó.",
  "noPAZoneMessage": "á_There are no Protective Action distances for this material. Only the Initial Isolation and evacuation zones has been calculated_______________________________________Ó",
  "settingsTitle": "á_Settings___Ó",
  "spillLocationLabel": "á_Spill Location_____Ó",
  "spillLocationButtonLabel": "á_Configure Spill Location Settings___________Ó",
  "IISettingsLabel": "á_Initial Isolation Zone________Ó",
  "IIButtonLabel": "á_Configure Initial Isolation Settings____________Ó",
  "PASettingsLabel": "á_Protective Action Zone________Ó",
  "PAButtonLabel": "á_Configure Protective Action Settings____________Ó",
  "downwindSettingsLabel": "á_Down Wind Zone_____Ó",
  "downwindButtonLabel": "á_Configure Down Wind Settings_________Ó",
  "fireSettingsLabel": "á_Fire Isolation Zone_______Ó",
  "fireButtonLabel": "á_Configure Fire Isolation Settings___________Ó",
  "bleveSettingsLabel": "á_BLEVE Isolation Zone_______Ó",
  "bleveButtonLabel": "á_Configure BLEVE Settings________Ó",
  "outlineStyle": "á_Outline Style_____Ó",
  "dash": "á_Dash__Ó",
  "dashdot": "á_Dash Dot___Ó",
  "dashdotdot": "á_Dash Dot Dot_____Ó",
  "dot": "á_Dot__Ó",
  "longdash": "á_Long Dash____Ó",
  "longdashdot": "á_Long Dash Dot_____Ó",
  "null": "á_Null__Ó",
  "shortdash": "á_Short Dash____Ó",
  "shortdashdot": "á_Short Dash Dot_____Ó",
  "shortdashdotdot": "á_Short Dash Dot Dot______Ó",
  "shortdot": "á_Short Dot____Ó",
  "solid": "á_Solid___Ó",
  "fillStyle": "á_Fill Style____Ó",
  "backward": "á_Backward___Ó",
  "cross": "á_Cross___Ó",
  "diagonal": "á_Diagonal___Ó",
  "forward": "á_Forward___Ó",
  "horizontal": "á_Horizontal____Ó",
  "vertical": "á_Vertical___Ó",
  "resultsTitle": "á_Results___Ó",
  "publishERGBtn": "á_Publish___Ó",
  "ERGLayerName": "á_Published ERG Layer Name________Ó",
  "invalidERGLayerName": "á_Layer name must only contain alpha-numeric characters and underscores______________________Ó",
  "missingERGLayerName": "á_You must enter a name for the ERG___________Ó",
  "publishingFailedLayerExists": "á_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________Ó.",
  "checkService": "á_Check Service: {0}______Ó",
  "createService": "á_Create Service: {0}_______Ó",
  "unableToCreate": "á_Unable to create: {0}_______Ó",
  "addToDefinition": "á_Add to definition: {0}________Ó",
  "successfullyPublished": "á_Successfully published web layer{0}Manage the web layer__________________Ó",
  "userRole": "á_Unable to create service because user does not have permissions____________________Ó",
  "transparency": "á_Transparency_____Ó",
  "outline": "á_Outline___Ó",
  "fill": "á_Fill (Color only applies when style set to solid)________________Ó",
  "createERGBtn": "á_Create Zones_____Ó",
  "clearERGBtn": "á_Clear___Ó",
  "labelFormat": "á_Label Format_____Ó",
  "helpIconTooltip": "á_The threshold between small and large spill sizes are:\nLiquids - 55 gallons (208 liters)\nSolids - 60 pounds (300 kilograms)_______________________________________Ó",
  "cellWidth": "á_Cell Width (x)_____Ó",
  "cellHeight": "á_Cell Height (y)______Ó",
  "invalidNumberMessage": "á_The value entered is not valid__________Ó",
  "invalidRangeMessage": "á_Value must be greater than 0_________Ó",
  "gridAngleInvalidRangeMessage": "á_Value must be between -89.9 and 89.9____________Ó",
  "formatIconTooltip": "á_Format Input_____Ó",
  "setCoordFormat": "á_Set Coordinate Format String_________Ó",
  "prefixNumbers": "á_Add '+/-' prefix to positive and negative numbers________________Ó",
  "cancelBtn": "á_Cancel___Ó",
  "applyBtn": "á_Apply___Ó",
  "comfirmInputNotation": "á_Confirm Input Notation________Ó",
  "notationsMatch": "á_notations match your input please confirm which you would like to use______________________Ó:",
  "missingLayerNameMessage": "á_You must enter a valid layer name before you can publish__________________Ó",
  "parseCoordinatesError": "á_Unable to parse coordinates. Please check your input_________________Ó.",
  "DD": "á_DD__Ó",
  "DDM": "á_DDM__Ó",
  "DMS": "á_DMS__Ó",
  "DDRev": "á_DDRev___Ó",
  "DDMRev": "á_DDMRev___Ó",
  "DMSRev": "á_DMSRev___Ó",
  "USNG": "á_USNG__Ó",
  "MGRS": "á_MGRS__Ó",
  "UTM_H": "á_UTM (H)___Ó",
  "UTM": "á_UTM__Ó",
  "GARS": "á_GARS__Ó",
  "GEOREF": "á_GEOREF___Ó",
  "DDLatLongNotation": "á_Decimal Degrees - Latitude/Longitude____________Ó",
  "DDLongLatNotation": "á_Decimal Degrees  - Longitude/Latitude____________Ó",
  "DDMLatLongNotation": "á_Degrees Decimal Minutes - Latitude/Longitude______________Ó",
  "DDMLongLatNotation": "á_Degrees Decimal Minutes - Longitude/Latitude______________Ó",
  "DMSLatLongNotation": "á_Degrees Minutes Seconds - Latitude/Longitude______________Ó",
  "DMSLongLatNotation": "á_Degrees Minutes Seconds - Longitude/Latitude______________Ó",
  "GARSNotation": "á_GARS__Ó",
  "GEOREFNotation": "á_GEOREF___Ó",
  "MGRSNotation": "á_MGRS__Ó",
  "USNGNotation": "á_USNG__Ó",
  "UTMBandNotation": "á_UTM - Band Letter______Ó",
  "UTMHemNotation": "á_UTM - Hemisphere (N/S)________Ó"
});