define({
  "symbolologyTabLabel": "ä_Configure Symbology_______Ü",
  "facilitiesDescription": "ä_Facility Layers______Ü",
  "demographicsDescription": "ä_Demographics Layer______Ü",
  "settingsTitle": "ä_Settings___Ü",
  "spillLocationLabel": "ä_Spill Location_____Ü",
  "spillLocationButtonLabel": "ä_Configure Spill Location Settings___________Ü",
  "IISettingsLabel": "ä_Initial Isolation Zone________Ü",
  "IIButtonLabel": "ä_Configure Initial Isolation Settings____________Ü",
  "PASettingsLabel": "ä_Protective Action Zone________Ü",
  "PAButtonLabel": "ä_Configure Protective Action Settings____________Ü",
  "downwindSettingsLabel": "ä_Down Wind Zone_____Ü",
  "downwindButtonLabel": "ä_Configure Down Wind Settings_________Ü",
  "fireSettingsLabel": "ä_Fire Isolation Zone_______Ü",
  "fireButtonLabel": "ä_Configure Fire Isolation Settings___________Ü",
  "bleveSettingsLabel": "ä_BLEVE Isolation Zone_______Ü",
  "bleveButtonLabel": "ä_Configure BLEVE Settings________Ü",
  "transparency": "ä_Transparency_____Ü",
  "outline": "ä_Outline___Ü",
  "fill": "ä_Fill (Color only applies when style set to solid)________________Ü",
  "outlineStyle": "ä_Outline Style_____Ü",
  "dash": "ä_Dash__Ü",
  "dashdot": "ä_Dash Dot___Ü",
  "dashdotdot": "ä_Dash Dot Dot_____Ü",
  "dot": "ä_Dot__Ü",
  "longdash": "ä_Long Dash____Ü",
  "longdashdot": "ä_Long Dash Dot_____Ü",
  "null": "ä_Null__Ü",
  "shortdash": "ä_Short Dash____Ü",
  "shortdashdot": "ä_Short Dash Dot_____Ü",
  "shortdashdotdot": "ä_Short Dash Dot Dot______Ü",
  "shortdot": "ä_Short Dot____Ü",
  "solid": "ä_Solid___Ü",
  "fillStyle": "ä_Fill Style____Ü",
  "backward": "ä_Backward___Ü",
  "cross": "ä_Cross___Ü",
  "diagonal": "ä_Diagonal___Ü",
  "forward": "ä_Forward___Ü",
  "horizontal": "ä_Horizontal____Ü",
  "vertical": "ä_Vertical___Ü"
});