define({
  "_widgetLabel": "試_Emergency Response Guide________驗",
  "ergMainPageTitle": "試_Based on the Emergency Response Guidebook 2016_______________驗",
  "coordInputLabelStart": "試_Spill Location (DD)_______驗",
  "coordInputLabel": "試_Spill Location_____驗",
  "addPointToolTip": "試_Add Spill Location______驗",
  "drawPointToolTip": "試_Click to add spill location_________驗",
  "material": "試_Material___驗",
  "materialPlaceholder": "試_Start typing to search for a material____________驗",
  "table3Message": "試_The material you have selected requires additional information if you are dealing with a large spill.\n\nPlease ensure you have the correct values selected for wind speed and transport container____________________________________________________________驗.",
  "table2Message": "試_The material you have selected may produces a large amount of Toxic Inhalation Hazard gases when spilled in water.\n\nYou may want to consider using the following material(s):\n\n_______________________________________________________驗",
  "spillSize": "試_Spill Size____驗",
  "small": "試_Small___驗",
  "large": "試_Large___驗",
  "fireLabel": "試_Show Fire Isolation Zone________驗",
  "weatherLabel": "試_Current Weather at Spill Location___________驗",
  "weatherIntialText": "試_<br />Updated once a spill location has been idenitified__________________驗",
  "temperature": "試_Temperature____驗",
  "wind": "試_Wind__驗",
  "c": "試_C_驗",
  "f": "試_F_驗",
  "weatherErrorMessage": "試_Weather info not obtained. Update Wind Speed and Time of Spill values manually________________________驗",
  "windDirection": "試_Wind Direction (blowing to)_________驗",
  "timeOfSpill": "試_Time of Spill_____驗",
  "day": "試_Day__驗",
  "night": "試_Night___驗",
  "windSpeed": "試_Wind Speed____驗",
  "low": "試_Low__驗",
  "moderate": "試_Moderate___驗",
  "high": "試_High__驗",
  "transportContainer": "試_Transport Container_______驗",
  "rail": "試_Rail tank car_____驗",
  "semi": "試_Highway tank truck or trailer__________驗",
  "mton": "試_Multiple ton cylinders________驗",
  "ston": "試_Multiple small cylinders or single ton cylinder_______________驗",
  "ag": "試_Agricultural nurse tank________驗",
  "msm": "試_Multiple small cylinders________驗",
  "bleveLabel": "試_Show BLEVE Isolation Zone_________驗",
  "capacity": "試_Container Capacity (litres)_________驗",
  "bleveMessage": "試_For the material you have selected an additional evacuation distance can be shown for BLEVE.\n\nTo enable this, set the Show BLEVE Isolation Zone toggle to on and select the appropiate container capacity______________________________________________________________驗.",
  "noPAZoneMessage": "試_There are no Protective Action distances for this material. Only the Initial Isolation and evacuation zones has been calculated_______________________________________驗",
  "settingsTitle": "試_Settings___驗",
  "spillLocationLabel": "試_Spill Location_____驗",
  "spillLocationButtonLabel": "試_Configure Spill Location Settings___________驗",
  "IISettingsLabel": "試_Initial Isolation Zone________驗",
  "IIButtonLabel": "試_Configure Initial Isolation Settings____________驗",
  "PASettingsLabel": "試_Protective Action Zone________驗",
  "PAButtonLabel": "試_Configure Protective Action Settings____________驗",
  "downwindSettingsLabel": "試_Down Wind Zone_____驗",
  "downwindButtonLabel": "試_Configure Down Wind Settings_________驗",
  "fireSettingsLabel": "試_Fire Isolation Zone_______驗",
  "fireButtonLabel": "試_Configure Fire Isolation Settings___________驗",
  "bleveSettingsLabel": "試_BLEVE Isolation Zone_______驗",
  "bleveButtonLabel": "試_Configure BLEVE Settings________驗",
  "outlineStyle": "試_Outline Style_____驗",
  "dash": "試_Dash__驗",
  "dashdot": "試_Dash Dot___驗",
  "dashdotdot": "試_Dash Dot Dot_____驗",
  "dot": "試_Dot__驗",
  "longdash": "試_Long Dash____驗",
  "longdashdot": "試_Long Dash Dot_____驗",
  "null": "試_Null__驗",
  "shortdash": "試_Short Dash____驗",
  "shortdashdot": "試_Short Dash Dot_____驗",
  "shortdashdotdot": "試_Short Dash Dot Dot______驗",
  "shortdot": "試_Short Dot____驗",
  "solid": "試_Solid___驗",
  "fillStyle": "試_Fill Style____驗",
  "backward": "試_Backward___驗",
  "cross": "試_Cross___驗",
  "diagonal": "試_Diagonal___驗",
  "forward": "試_Forward___驗",
  "horizontal": "試_Horizontal____驗",
  "vertical": "試_Vertical___驗",
  "resultsTitle": "試_Results___驗",
  "publishERGBtn": "試_Publish___驗",
  "ERGLayerName": "試_Published ERG Layer Name________驗",
  "invalidERGLayerName": "試_Layer name must only contain alpha-numeric characters and underscores______________________驗",
  "missingERGLayerName": "試_You must enter a name for the ERG___________驗",
  "publishingFailedLayerExists": "試_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________驗.",
  "checkService": "試_Check Service: {0}______驗",
  "createService": "試_Create Service: {0}_______驗",
  "unableToCreate": "試_Unable to create: {0}_______驗",
  "addToDefinition": "試_Add to definition: {0}________驗",
  "successfullyPublished": "試_Successfully published web layer{0}Manage the web layer__________________驗",
  "userRole": "試_Unable to create service because user does not have permissions____________________驗",
  "transparency": "試_Transparency_____驗",
  "outline": "試_Outline___驗",
  "fill": "試_Fill (Color only applies when style set to solid)________________驗",
  "createERGBtn": "試_Create Zones_____驗",
  "clearERGBtn": "試_Clear___驗",
  "labelFormat": "試_Label Format_____驗",
  "helpIconTooltip": "試_The threshold between small and large spill sizes are:\nLiquids - 55 gallons (208 liters)\nSolids - 60 pounds (300 kilograms)_______________________________________驗",
  "cellWidth": "試_Cell Width (x)_____驗",
  "cellHeight": "試_Cell Height (y)______驗",
  "invalidNumberMessage": "試_The value entered is not valid__________驗",
  "invalidRangeMessage": "試_Value must be greater than 0_________驗",
  "gridAngleInvalidRangeMessage": "試_Value must be between -89.9 and 89.9____________驗",
  "formatIconTooltip": "試_Format Input_____驗",
  "setCoordFormat": "試_Set Coordinate Format String_________驗",
  "prefixNumbers": "試_Add '+/-' prefix to positive and negative numbers________________驗",
  "cancelBtn": "試_Cancel___驗",
  "applyBtn": "試_Apply___驗",
  "comfirmInputNotation": "試_Confirm Input Notation________驗",
  "notationsMatch": "試_notations match your input please confirm which you would like to use______________________驗:",
  "missingLayerNameMessage": "試_You must enter a valid layer name before you can publish__________________驗",
  "parseCoordinatesError": "試_Unable to parse coordinates. Please check your input_________________驗.",
  "DD": "試_DD__驗",
  "DDM": "試_DDM__驗",
  "DMS": "試_DMS__驗",
  "DDRev": "試_DDRev___驗",
  "DDMRev": "試_DDMRev___驗",
  "DMSRev": "試_DMSRev___驗",
  "USNG": "試_USNG__驗",
  "MGRS": "試_MGRS__驗",
  "UTM_H": "試_UTM (H)___驗",
  "UTM": "試_UTM__驗",
  "GARS": "試_GARS__驗",
  "GEOREF": "試_GEOREF___驗",
  "DDLatLongNotation": "試_Decimal Degrees - Latitude/Longitude____________驗",
  "DDLongLatNotation": "試_Decimal Degrees  - Longitude/Latitude____________驗",
  "DDMLatLongNotation": "試_Degrees Decimal Minutes - Latitude/Longitude______________驗",
  "DDMLongLatNotation": "試_Degrees Decimal Minutes - Longitude/Latitude______________驗",
  "DMSLatLongNotation": "試_Degrees Minutes Seconds - Latitude/Longitude______________驗",
  "DMSLongLatNotation": "試_Degrees Minutes Seconds - Longitude/Latitude______________驗",
  "GARSNotation": "試_GARS__驗",
  "GEOREFNotation": "試_GEOREF___驗",
  "MGRSNotation": "試_MGRS__驗",
  "USNGNotation": "試_USNG__驗",
  "UTMBandNotation": "試_UTM - Band Letter______驗",
  "UTMHemNotation": "試_UTM - Hemisphere (N/S)________驗"
});