define({
  "_widgetLabel": "Ă_Emergency Response Guide________ș",
  "ergMainPageTitle": "Ă_Based on the Emergency Response Guidebook 2016_______________ș",
  "coordInputLabelStart": "Ă_Spill Location (DD)_______ș",
  "coordInputLabel": "Ă_Spill Location_____ș",
  "addPointToolTip": "Ă_Add Spill Location______ș",
  "drawPointToolTip": "Ă_Click to add spill location_________ș",
  "material": "Ă_Material___ș",
  "materialPlaceholder": "Ă_Start typing to search for a material____________ș",
  "table3Message": "Ă_The material you have selected requires additional information if you are dealing with a large spill.\n\nPlease ensure you have the correct values selected for wind speed and transport container____________________________________________________________ș.",
  "table2Message": "Ă_The material you have selected may produces a large amount of Toxic Inhalation Hazard gases when spilled in water.\n\nYou may want to consider using the following material(s):\n\n_______________________________________________________ș",
  "spillSize": "Ă_Spill Size____ș",
  "small": "Ă_Small___ș",
  "large": "Ă_Large___ș",
  "fireLabel": "Ă_Show Fire Isolation Zone________ș",
  "weatherLabel": "Ă_Current Weather at Spill Location___________ș",
  "weatherIntialText": "Ă_<br />Updated once a spill location has been idenitified__________________ș",
  "temperature": "Ă_Temperature____ș",
  "wind": "Ă_Wind__ș",
  "c": "Ă_C_ș",
  "f": "Ă_F_ș",
  "weatherErrorMessage": "Ă_Weather info not obtained. Update Wind Speed and Time of Spill values manually________________________ș",
  "windDirection": "Ă_Wind Direction (blowing to)_________ș",
  "timeOfSpill": "Ă_Time of Spill_____ș",
  "day": "Ă_Day__ș",
  "night": "Ă_Night___ș",
  "windSpeed": "Ă_Wind Speed____ș",
  "low": "Ă_Low__ș",
  "moderate": "Ă_Moderate___ș",
  "high": "Ă_High__ș",
  "transportContainer": "Ă_Transport Container_______ș",
  "rail": "Ă_Rail tank car_____ș",
  "semi": "Ă_Highway tank truck or trailer__________ș",
  "mton": "Ă_Multiple ton cylinders________ș",
  "ston": "Ă_Multiple small cylinders or single ton cylinder_______________ș",
  "ag": "Ă_Agricultural nurse tank________ș",
  "msm": "Ă_Multiple small cylinders________ș",
  "bleveLabel": "Ă_Show BLEVE Isolation Zone_________ș",
  "capacity": "Ă_Container Capacity (litres)_________ș",
  "bleveMessage": "Ă_For the material you have selected an additional evacuation distance can be shown for BLEVE.\n\nTo enable this, set the Show BLEVE Isolation Zone toggle to on and select the appropiate container capacity______________________________________________________________ș.",
  "noPAZoneMessage": "Ă_There are no Protective Action distances for this material. Only the Initial Isolation and evacuation zones has been calculated_______________________________________ș",
  "settingsTitle": "Ă_Settings___ș",
  "spillLocationLabel": "Ă_Spill Location_____ș",
  "spillLocationButtonLabel": "Ă_Configure Spill Location Settings___________ș",
  "IISettingsLabel": "Ă_Initial Isolation Zone________ș",
  "IIButtonLabel": "Ă_Configure Initial Isolation Settings____________ș",
  "PASettingsLabel": "Ă_Protective Action Zone________ș",
  "PAButtonLabel": "Ă_Configure Protective Action Settings____________ș",
  "downwindSettingsLabel": "Ă_Down Wind Zone_____ș",
  "downwindButtonLabel": "Ă_Configure Down Wind Settings_________ș",
  "fireSettingsLabel": "Ă_Fire Isolation Zone_______ș",
  "fireButtonLabel": "Ă_Configure Fire Isolation Settings___________ș",
  "bleveSettingsLabel": "Ă_BLEVE Isolation Zone_______ș",
  "bleveButtonLabel": "Ă_Configure BLEVE Settings________ș",
  "outlineStyle": "Ă_Outline Style_____ș",
  "dash": "Ă_Dash__ș",
  "dashdot": "Ă_Dash Dot___ș",
  "dashdotdot": "Ă_Dash Dot Dot_____ș",
  "dot": "Ă_Dot__ș",
  "longdash": "Ă_Long Dash____ș",
  "longdashdot": "Ă_Long Dash Dot_____ș",
  "null": "Ă_Null__ș",
  "shortdash": "Ă_Short Dash____ș",
  "shortdashdot": "Ă_Short Dash Dot_____ș",
  "shortdashdotdot": "Ă_Short Dash Dot Dot______ș",
  "shortdot": "Ă_Short Dot____ș",
  "solid": "Ă_Solid___ș",
  "fillStyle": "Ă_Fill Style____ș",
  "backward": "Ă_Backward___ș",
  "cross": "Ă_Cross___ș",
  "diagonal": "Ă_Diagonal___ș",
  "forward": "Ă_Forward___ș",
  "horizontal": "Ă_Horizontal____ș",
  "vertical": "Ă_Vertical___ș",
  "resultsTitle": "Ă_Results___ș",
  "publishERGBtn": "Ă_Publish___ș",
  "ERGLayerName": "Ă_Published ERG Layer Name________ș",
  "invalidERGLayerName": "Ă_Layer name must only contain alpha-numeric characters and underscores______________________ș",
  "missingERGLayerName": "Ă_You must enter a name for the ERG___________ș",
  "publishingFailedLayerExists": "Ă_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________ș.",
  "checkService": "Ă_Check Service: {0}______ș",
  "createService": "Ă_Create Service: {0}_______ș",
  "unableToCreate": "Ă_Unable to create: {0}_______ș",
  "addToDefinition": "Ă_Add to definition: {0}________ș",
  "successfullyPublished": "Ă_Successfully published web layer{0}Manage the web layer__________________ș",
  "userRole": "Ă_Unable to create service because user does not have permissions____________________ș",
  "transparency": "Ă_Transparency_____ș",
  "outline": "Ă_Outline___ș",
  "fill": "Ă_Fill (Color only applies when style set to solid)________________ș",
  "createERGBtn": "Ă_Create Zones_____ș",
  "clearERGBtn": "Ă_Clear___ș",
  "labelFormat": "Ă_Label Format_____ș",
  "helpIconTooltip": "Ă_The threshold between small and large spill sizes are:\nLiquids - 55 gallons (208 liters)\nSolids - 60 pounds (300 kilograms)_______________________________________ș",
  "cellWidth": "Ă_Cell Width (x)_____ș",
  "cellHeight": "Ă_Cell Height (y)______ș",
  "invalidNumberMessage": "Ă_The value entered is not valid__________ș",
  "invalidRangeMessage": "Ă_Value must be greater than 0_________ș",
  "gridAngleInvalidRangeMessage": "Ă_Value must be between -89.9 and 89.9____________ș",
  "formatIconTooltip": "Ă_Format Input_____ș",
  "setCoordFormat": "Ă_Set Coordinate Format String_________ș",
  "prefixNumbers": "Ă_Add '+/-' prefix to positive and negative numbers________________ș",
  "cancelBtn": "Ă_Cancel___ș",
  "applyBtn": "Ă_Apply___ș",
  "comfirmInputNotation": "Ă_Confirm Input Notation________ș",
  "notationsMatch": "Ă_notations match your input please confirm which you would like to use______________________ș:",
  "missingLayerNameMessage": "Ă_You must enter a valid layer name before you can publish__________________ș",
  "parseCoordinatesError": "Ă_Unable to parse coordinates. Please check your input_________________ș.",
  "DD": "Ă_DD__ș",
  "DDM": "Ă_DDM__ș",
  "DMS": "Ă_DMS__ș",
  "DDRev": "Ă_DDRev___ș",
  "DDMRev": "Ă_DDMRev___ș",
  "DMSRev": "Ă_DMSRev___ș",
  "USNG": "Ă_USNG__ș",
  "MGRS": "Ă_MGRS__ș",
  "UTM_H": "Ă_UTM (H)___ș",
  "UTM": "Ă_UTM__ș",
  "GARS": "Ă_GARS__ș",
  "GEOREF": "Ă_GEOREF___ș",
  "DDLatLongNotation": "Ă_Decimal Degrees - Latitude/Longitude____________ș",
  "DDLongLatNotation": "Ă_Decimal Degrees  - Longitude/Latitude____________ș",
  "DDMLatLongNotation": "Ă_Degrees Decimal Minutes - Latitude/Longitude______________ș",
  "DDMLongLatNotation": "Ă_Degrees Decimal Minutes - Longitude/Latitude______________ș",
  "DMSLatLongNotation": "Ă_Degrees Minutes Seconds - Latitude/Longitude______________ș",
  "DMSLongLatNotation": "Ă_Degrees Minutes Seconds - Longitude/Latitude______________ș",
  "GARSNotation": "Ă_GARS__ș",
  "GEOREFNotation": "Ă_GEOREF___ș",
  "MGRSNotation": "Ă_MGRS__ș",
  "USNGNotation": "Ă_USNG__ș",
  "UTMBandNotation": "Ă_UTM - Band Letter______ș",
  "UTMHemNotation": "Ă_UTM - Hemisphere (N/S)________ș"
});