define({
  "symbolologyTabLabel": "Č_Configure Symbology_______ž",
  "facilitiesDescription": "Č_Facility Layers______ž",
  "demographicsDescription": "Č_Demographics Layer______ž",
  "settingsTitle": "Č_Settings___ž",
  "spillLocationLabel": "Č_Spill Location_____ž",
  "spillLocationButtonLabel": "Č_Configure Spill Location Settings___________ž",
  "IISettingsLabel": "Č_Initial Isolation Zone________ž",
  "IIButtonLabel": "Č_Configure Initial Isolation Settings____________ž",
  "PASettingsLabel": "Č_Protective Action Zone________ž",
  "PAButtonLabel": "Č_Configure Protective Action Settings____________ž",
  "downwindSettingsLabel": "Č_Down Wind Zone_____ž",
  "downwindButtonLabel": "Č_Configure Down Wind Settings_________ž",
  "fireSettingsLabel": "Č_Fire Isolation Zone_______ž",
  "fireButtonLabel": "Č_Configure Fire Isolation Settings___________ž",
  "bleveSettingsLabel": "Č_BLEVE Isolation Zone_______ž",
  "bleveButtonLabel": "Č_Configure BLEVE Settings________ž",
  "transparency": "Č_Transparency_____ž",
  "outline": "Č_Outline___ž",
  "fill": "Č_Fill (Color only applies when style set to solid)________________ž",
  "outlineStyle": "Č_Outline Style_____ž",
  "dash": "Č_Dash__ž",
  "dashdot": "Č_Dash Dot___ž",
  "dashdotdot": "Č_Dash Dot Dot_____ž",
  "dot": "Č_Dot__ž",
  "longdash": "Č_Long Dash____ž",
  "longdashdot": "Č_Long Dash Dot_____ž",
  "null": "Č_Null__ž",
  "shortdash": "Č_Short Dash____ž",
  "shortdashdot": "Č_Short Dash Dot_____ž",
  "shortdashdotdot": "Č_Short Dash Dot Dot______ž",
  "shortdot": "Č_Short Dot____ž",
  "solid": "Č_Solid___ž",
  "fillStyle": "Č_Fill Style____ž",
  "backward": "Č_Backward___ž",
  "cross": "Č_Cross___ž",
  "diagonal": "Č_Diagonal___ž",
  "forward": "Č_Forward___ž",
  "horizontal": "Č_Horizontal____ž",
  "vertical": "Č_Vertical___ž"
});