define({
  "_widgetLabel": "Č_Emergency Response Guide________ž",
  "ergMainPageTitle": "Č_Based on the Emergency Response Guidebook 2016_______________ž",
  "coordInputLabelStart": "Č_Spill Location (DD)_______ž",
  "coordInputLabel": "Č_Spill Location_____ž",
  "addPointToolTip": "Č_Add Spill Location______ž",
  "drawPointToolTip": "Č_Click to add spill location_________ž",
  "material": "Č_Material___ž",
  "materialPlaceholder": "Č_Start typing to search for a material____________ž",
  "table3Message": "Č_The material you have selected requires additional information if you are dealing with a large spill.\n\nPlease ensure you have the correct values selected for wind speed and transport container____________________________________________________________ž.",
  "table2Message": "Č_The material you have selected may produces a large amount of Toxic Inhalation Hazard gases when spilled in water.\n\nYou may want to consider using the following material(s):\n\n_______________________________________________________ž",
  "spillSize": "Č_Spill Size____ž",
  "small": "Č_Small___ž",
  "large": "Č_Large___ž",
  "fireLabel": "Č_Show Fire Isolation Zone________ž",
  "weatherLabel": "Č_Current Weather at Spill Location___________ž",
  "weatherIntialText": "Č_<br />Updated once a spill location has been idenitified__________________ž",
  "temperature": "Č_Temperature____ž",
  "wind": "Č_Wind__ž",
  "c": "Č_C_ž",
  "f": "Č_F_ž",
  "weatherErrorMessage": "Č_Weather info not obtained. Update Wind Speed and Time of Spill values manually________________________ž",
  "windDirection": "Č_Wind Direction (blowing to)_________ž",
  "timeOfSpill": "Č_Time of Spill_____ž",
  "day": "Č_Day__ž",
  "night": "Č_Night___ž",
  "windSpeed": "Č_Wind Speed____ž",
  "low": "Č_Low__ž",
  "moderate": "Č_Moderate___ž",
  "high": "Č_High__ž",
  "transportContainer": "Č_Transport Container_______ž",
  "rail": "Č_Rail tank car_____ž",
  "semi": "Č_Highway tank truck or trailer__________ž",
  "mton": "Č_Multiple ton cylinders________ž",
  "ston": "Č_Multiple small cylinders or single ton cylinder_______________ž",
  "ag": "Č_Agricultural nurse tank________ž",
  "msm": "Č_Multiple small cylinders________ž",
  "bleveLabel": "Č_Show BLEVE Isolation Zone_________ž",
  "capacity": "Č_Container Capacity (litres)_________ž",
  "bleveMessage": "Č_For the material you have selected an additional evacuation distance can be shown for BLEVE.\n\nTo enable this, set the Show BLEVE Isolation Zone toggle to on and select the appropiate container capacity______________________________________________________________ž.",
  "noPAZoneMessage": "Č_There are no Protective Action distances for this material. Only the Initial Isolation and evacuation zones has been calculated_______________________________________ž",
  "settingsTitle": "Č_Settings___ž",
  "spillLocationLabel": "Č_Spill Location_____ž",
  "spillLocationButtonLabel": "Č_Configure Spill Location Settings___________ž",
  "IISettingsLabel": "Č_Initial Isolation Zone________ž",
  "IIButtonLabel": "Č_Configure Initial Isolation Settings____________ž",
  "PASettingsLabel": "Č_Protective Action Zone________ž",
  "PAButtonLabel": "Č_Configure Protective Action Settings____________ž",
  "downwindSettingsLabel": "Č_Down Wind Zone_____ž",
  "downwindButtonLabel": "Č_Configure Down Wind Settings_________ž",
  "fireSettingsLabel": "Č_Fire Isolation Zone_______ž",
  "fireButtonLabel": "Č_Configure Fire Isolation Settings___________ž",
  "bleveSettingsLabel": "Č_BLEVE Isolation Zone_______ž",
  "bleveButtonLabel": "Č_Configure BLEVE Settings________ž",
  "outlineStyle": "Č_Outline Style_____ž",
  "dash": "Č_Dash__ž",
  "dashdot": "Č_Dash Dot___ž",
  "dashdotdot": "Č_Dash Dot Dot_____ž",
  "dot": "Č_Dot__ž",
  "longdash": "Č_Long Dash____ž",
  "longdashdot": "Č_Long Dash Dot_____ž",
  "null": "Č_Null__ž",
  "shortdash": "Č_Short Dash____ž",
  "shortdashdot": "Č_Short Dash Dot_____ž",
  "shortdashdotdot": "Č_Short Dash Dot Dot______ž",
  "shortdot": "Č_Short Dot____ž",
  "solid": "Č_Solid___ž",
  "fillStyle": "Č_Fill Style____ž",
  "backward": "Č_Backward___ž",
  "cross": "Č_Cross___ž",
  "diagonal": "Č_Diagonal___ž",
  "forward": "Č_Forward___ž",
  "horizontal": "Č_Horizontal____ž",
  "vertical": "Č_Vertical___ž",
  "resultsTitle": "Č_Results___ž",
  "publishERGBtn": "Č_Publish___ž",
  "ERGLayerName": "Č_Published ERG Layer Name________ž",
  "invalidERGLayerName": "Č_Layer name must only contain alpha-numeric characters and underscores______________________ž",
  "missingERGLayerName": "Č_You must enter a name for the ERG___________ž",
  "publishingFailedLayerExists": "Č_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________ž.",
  "checkService": "Č_Check Service: {0}______ž",
  "createService": "Č_Create Service: {0}_______ž",
  "unableToCreate": "Č_Unable to create: {0}_______ž",
  "addToDefinition": "Č_Add to definition: {0}________ž",
  "successfullyPublished": "Č_Successfully published web layer{0}Manage the web layer__________________ž",
  "userRole": "Č_Unable to create service because user does not have permissions____________________ž",
  "transparency": "Č_Transparency_____ž",
  "outline": "Č_Outline___ž",
  "fill": "Č_Fill (Color only applies when style set to solid)________________ž",
  "createERGBtn": "Č_Create Zones_____ž",
  "clearERGBtn": "Č_Clear___ž",
  "labelFormat": "Č_Label Format_____ž",
  "helpIconTooltip": "Č_The threshold between small and large spill sizes are:\nLiquids - 55 gallons (208 liters)\nSolids - 60 pounds (300 kilograms)_______________________________________ž",
  "cellWidth": "Č_Cell Width (x)_____ž",
  "cellHeight": "Č_Cell Height (y)______ž",
  "invalidNumberMessage": "Č_The value entered is not valid__________ž",
  "invalidRangeMessage": "Č_Value must be greater than 0_________ž",
  "gridAngleInvalidRangeMessage": "Č_Value must be between -89.9 and 89.9____________ž",
  "formatIconTooltip": "Č_Format Input_____ž",
  "setCoordFormat": "Č_Set Coordinate Format String_________ž",
  "prefixNumbers": "Č_Add '+/-' prefix to positive and negative numbers________________ž",
  "cancelBtn": "Č_Cancel___ž",
  "applyBtn": "Č_Apply___ž",
  "comfirmInputNotation": "Č_Confirm Input Notation________ž",
  "notationsMatch": "Č_notations match your input please confirm which you would like to use______________________ž:",
  "missingLayerNameMessage": "Č_You must enter a valid layer name before you can publish__________________ž",
  "parseCoordinatesError": "Č_Unable to parse coordinates. Please check your input_________________ž.",
  "DD": "Č_DD__ž",
  "DDM": "Č_DDM__ž",
  "DMS": "Č_DMS__ž",
  "DDRev": "Č_DDRev___ž",
  "DDMRev": "Č_DDMRev___ž",
  "DMSRev": "Č_DMSRev___ž",
  "USNG": "Č_USNG__ž",
  "MGRS": "Č_MGRS__ž",
  "UTM_H": "Č_UTM (H)___ž",
  "UTM": "Č_UTM__ž",
  "GARS": "Č_GARS__ž",
  "GEOREF": "Č_GEOREF___ž",
  "DDLatLongNotation": "Č_Decimal Degrees - Latitude/Longitude____________ž",
  "DDLongLatNotation": "Č_Decimal Degrees  - Longitude/Latitude____________ž",
  "DDMLatLongNotation": "Č_Degrees Decimal Minutes - Latitude/Longitude______________ž",
  "DDMLongLatNotation": "Č_Degrees Decimal Minutes - Longitude/Latitude______________ž",
  "DMSLatLongNotation": "Č_Degrees Minutes Seconds - Latitude/Longitude______________ž",
  "DMSLongLatNotation": "Č_Degrees Minutes Seconds - Longitude/Latitude______________ž",
  "GARSNotation": "Č_GARS__ž",
  "GEOREFNotation": "Č_GEOREF___ž",
  "MGRSNotation": "Č_MGRS__ž",
  "USNGNotation": "Č_USNG__ž",
  "UTMBandNotation": "Č_UTM - Band Letter______ž",
  "UTMHemNotation": "Č_UTM - Hemisphere (N/S)________ž"
});