define({
  "_widgetLabel": "é_Emergency Response Guide________È",
  "ergMainPageTitle": "é_Based on the Emergency Response Guidebook 2016_______________È",
  "coordInputLabelStart": "é_Spill Location (DD)_______È",
  "coordInputLabel": "é_Spill Location_____È",
  "addPointToolTip": "é_Add Spill Location______È",
  "drawPointToolTip": "é_Click to add spill location_________È",
  "material": "é_Material___È",
  "materialPlaceholder": "é_Start typing to search for a material____________È",
  "table3Message": "é_The material you have selected requires additional information if you are dealing with a large spill.\n\nPlease ensure you have the correct values selected for wind speed and transport container____________________________________________________________È.",
  "table2Message": "é_The material you have selected may produces a large amount of Toxic Inhalation Hazard gases when spilled in water.\n\nYou may want to consider using the following material(s):\n\n_______________________________________________________È",
  "spillSize": "é_Spill Size____È",
  "small": "é_Small___È",
  "large": "é_Large___È",
  "fireLabel": "é_Show Fire Isolation Zone________È",
  "weatherLabel": "é_Current Weather at Spill Location___________È",
  "weatherIntialText": "é_<br />Updated once a spill location has been idenitified__________________È",
  "temperature": "é_Temperature____È",
  "wind": "é_Wind__È",
  "c": "é_C_È",
  "f": "é_F_È",
  "weatherErrorMessage": "é_Weather info not obtained. Update Wind Speed and Time of Spill values manually________________________È",
  "windDirection": "é_Wind Direction (blowing to)_________È",
  "timeOfSpill": "é_Time of Spill_____È",
  "day": "é_Day__È",
  "night": "é_Night___È",
  "windSpeed": "é_Wind Speed____È",
  "low": "é_Low__È",
  "moderate": "é_Moderate___È",
  "high": "é_High__È",
  "transportContainer": "é_Transport Container_______È",
  "rail": "é_Rail tank car_____È",
  "semi": "é_Highway tank truck or trailer__________È",
  "mton": "é_Multiple ton cylinders________È",
  "ston": "é_Multiple small cylinders or single ton cylinder_______________È",
  "ag": "é_Agricultural nurse tank________È",
  "msm": "é_Multiple small cylinders________È",
  "bleveLabel": "é_Show BLEVE Isolation Zone_________È",
  "capacity": "é_Container Capacity (litres)_________È",
  "bleveMessage": "é_For the material you have selected an additional evacuation distance can be shown for BLEVE.\n\nTo enable this, set the Show BLEVE Isolation Zone toggle to on and select the appropiate container capacity______________________________________________________________È.",
  "noPAZoneMessage": "é_There are no Protective Action distances for this material. Only the Initial Isolation and evacuation zones has been calculated_______________________________________È",
  "settingsTitle": "é_Settings___È",
  "spillLocationLabel": "é_Spill Location_____È",
  "spillLocationButtonLabel": "é_Configure Spill Location Settings___________È",
  "IISettingsLabel": "é_Initial Isolation Zone________È",
  "IIButtonLabel": "é_Configure Initial Isolation Settings____________È",
  "PASettingsLabel": "é_Protective Action Zone________È",
  "PAButtonLabel": "é_Configure Protective Action Settings____________È",
  "downwindSettingsLabel": "é_Down Wind Zone_____È",
  "downwindButtonLabel": "é_Configure Down Wind Settings_________È",
  "fireSettingsLabel": "é_Fire Isolation Zone_______È",
  "fireButtonLabel": "é_Configure Fire Isolation Settings___________È",
  "bleveSettingsLabel": "é_BLEVE Isolation Zone_______È",
  "bleveButtonLabel": "é_Configure BLEVE Settings________È",
  "outlineStyle": "é_Outline Style_____È",
  "dash": "é_Dash__È",
  "dashdot": "é_Dash Dot___È",
  "dashdotdot": "é_Dash Dot Dot_____È",
  "dot": "é_Dot__È",
  "longdash": "é_Long Dash____È",
  "longdashdot": "é_Long Dash Dot_____È",
  "null": "é_Null__È",
  "shortdash": "é_Short Dash____È",
  "shortdashdot": "é_Short Dash Dot_____È",
  "shortdashdotdot": "é_Short Dash Dot Dot______È",
  "shortdot": "é_Short Dot____È",
  "solid": "é_Solid___È",
  "fillStyle": "é_Fill Style____È",
  "backward": "é_Backward___È",
  "cross": "é_Cross___È",
  "diagonal": "é_Diagonal___È",
  "forward": "é_Forward___È",
  "horizontal": "é_Horizontal____È",
  "vertical": "é_Vertical___È",
  "resultsTitle": "é_Results___È",
  "publishERGBtn": "é_Publish___È",
  "ERGLayerName": "é_Published ERG Layer Name________È",
  "invalidERGLayerName": "é_Layer name must only contain alpha-numeric characters and underscores______________________È",
  "missingERGLayerName": "é_You must enter a name for the ERG___________È",
  "publishingFailedLayerExists": "é_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________È.",
  "checkService": "é_Check Service: {0}______È",
  "createService": "é_Create Service: {0}_______È",
  "unableToCreate": "é_Unable to create: {0}_______È",
  "addToDefinition": "é_Add to definition: {0}________È",
  "successfullyPublished": "é_Successfully published web layer{0}Manage the web layer__________________È",
  "userRole": "é_Unable to create service because user does not have permissions____________________È",
  "transparency": "é_Transparency_____È",
  "outline": "é_Outline___È",
  "fill": "é_Fill (Color only applies when style set to solid)________________È",
  "createERGBtn": "é_Create Zones_____È",
  "clearERGBtn": "é_Clear___È",
  "labelFormat": "é_Label Format_____È",
  "helpIconTooltip": "é_The threshold between small and large spill sizes are:\nLiquids - 55 gallons (208 liters)\nSolids - 60 pounds (300 kilograms)_______________________________________È",
  "cellWidth": "é_Cell Width (x)_____È",
  "cellHeight": "é_Cell Height (y)______È",
  "invalidNumberMessage": "é_The value entered is not valid__________È",
  "invalidRangeMessage": "é_Value must be greater than 0_________È",
  "gridAngleInvalidRangeMessage": "é_Value must be between -89.9 and 89.9____________È",
  "formatIconTooltip": "é_Format Input_____È",
  "setCoordFormat": "é_Set Coordinate Format String_________È",
  "prefixNumbers": "é_Add '+/-' prefix to positive and negative numbers________________È",
  "cancelBtn": "é_Cancel___È",
  "applyBtn": "é_Apply___È",
  "comfirmInputNotation": "é_Confirm Input Notation________È",
  "notationsMatch": "é_notations match your input please confirm which you would like to use______________________È:",
  "missingLayerNameMessage": "é_You must enter a valid layer name before you can publish__________________È",
  "parseCoordinatesError": "é_Unable to parse coordinates. Please check your input_________________È.",
  "DD": "é_DD__È",
  "DDM": "é_DDM__È",
  "DMS": "é_DMS__È",
  "DDRev": "é_DDRev___È",
  "DDMRev": "é_DDMRev___È",
  "DMSRev": "é_DMSRev___È",
  "USNG": "é_USNG__È",
  "MGRS": "é_MGRS__È",
  "UTM_H": "é_UTM (H)___È",
  "UTM": "é_UTM__È",
  "GARS": "é_GARS__È",
  "GEOREF": "é_GEOREF___È",
  "DDLatLongNotation": "é_Decimal Degrees - Latitude/Longitude____________È",
  "DDLongLatNotation": "é_Decimal Degrees  - Longitude/Latitude____________È",
  "DDMLatLongNotation": "é_Degrees Decimal Minutes - Latitude/Longitude______________È",
  "DDMLongLatNotation": "é_Degrees Decimal Minutes - Longitude/Latitude______________È",
  "DMSLatLongNotation": "é_Degrees Minutes Seconds - Latitude/Longitude______________È",
  "DMSLongLatNotation": "é_Degrees Minutes Seconds - Longitude/Latitude______________È",
  "GARSNotation": "é_GARS__È",
  "GEOREFNotation": "é_GEOREF___È",
  "MGRSNotation": "é_MGRS__È",
  "USNGNotation": "é_USNG__È",
  "UTMBandNotation": "é_UTM - Band Letter______È",
  "UTMHemNotation": "é_UTM - Hemisphere (N/S)________È"
});