define({
  "symbolologyTabLabel": "आ_Configure Symbology_______ज",
  "facilitiesDescription": "आ_Facility Layers______ज",
  "demographicsDescription": "आ_Demographics Layer______ज",
  "settingsTitle": "आ_Settings___ज",
  "spillLocationLabel": "आ_Spill Location_____ज",
  "spillLocationButtonLabel": "आ_Configure Spill Location Settings___________ज",
  "IISettingsLabel": "आ_Initial Isolation Zone________ज",
  "IIButtonLabel": "आ_Configure Initial Isolation Settings____________ज",
  "PASettingsLabel": "आ_Protective Action Zone________ज",
  "PAButtonLabel": "आ_Configure Protective Action Settings____________ज",
  "downwindSettingsLabel": "आ_Down Wind Zone_____ज",
  "downwindButtonLabel": "आ_Configure Down Wind Settings_________ज",
  "fireSettingsLabel": "आ_Fire Isolation Zone_______ज",
  "fireButtonLabel": "आ_Configure Fire Isolation Settings___________ज",
  "bleveSettingsLabel": "आ_BLEVE Isolation Zone_______ज",
  "bleveButtonLabel": "आ_Configure BLEVE Settings________ज",
  "transparency": "आ_Transparency_____ज",
  "outline": "आ_Outline___ज",
  "fill": "आ_Fill (Color only applies when style set to solid)________________ज",
  "outlineStyle": "आ_Outline Style_____ज",
  "dash": "आ_Dash__ज",
  "dashdot": "आ_Dash Dot___ज",
  "dashdotdot": "आ_Dash Dot Dot_____ज",
  "dot": "आ_Dot__ज",
  "longdash": "आ_Long Dash____ज",
  "longdashdot": "आ_Long Dash Dot_____ज",
  "null": "आ_Null__ज",
  "shortdash": "आ_Short Dash____ज",
  "shortdashdot": "आ_Short Dash Dot_____ज",
  "shortdashdotdot": "आ_Short Dash Dot Dot______ज",
  "shortdot": "आ_Short Dot____ज",
  "solid": "आ_Solid___ज",
  "fillStyle": "आ_Fill Style____ज",
  "backward": "आ_Backward___ज",
  "cross": "आ_Cross___ज",
  "diagonal": "आ_Diagonal___ज",
  "forward": "आ_Forward___ज",
  "horizontal": "आ_Horizontal____ज",
  "vertical": "आ_Vertical___ज"
});