define({
  "_widgetLabel": "بيت_Emergency Response Guide________لاحقة",
  "ergMainPageTitle": "بيت_Based on the Emergency Response Guidebook 2016_______________لاحقة",
  "coordInputLabelStart": "بيت_Spill Location (DD)_______لاحقة",
  "coordInputLabel": "بيت_Spill Location_____لاحقة",
  "addPointToolTip": "بيت_Add Spill Location______لاحقة",
  "drawPointToolTip": "بيت_Click to add spill location_________لاحقة",
  "material": "بيت_Material___لاحقة",
  "materialPlaceholder": "بيت_Start typing to search for a material____________لاحقة",
  "table3Message": "بيت_The material you have selected requires additional information if you are dealing with a large spill.\n\nPlease ensure you have the correct values selected for wind speed and transport container____________________________________________________________لاحقة.",
  "table2Message": "بيت_The material you have selected may produces a large amount of Toxic Inhalation Hazard gases when spilled in water.\n\nYou may want to consider using the following material(s):\n\n_______________________________________________________لاحقة",
  "spillSize": "بيت_Spill Size____لاحقة",
  "small": "بيت_Small___لاحقة",
  "large": "بيت_Large___لاحقة",
  "fireLabel": "بيت_Show Fire Isolation Zone________لاحقة",
  "weatherLabel": "بيت_Current Weather at Spill Location___________لاحقة",
  "weatherIntialText": "بيت_<br />Updated once a spill location has been idenitified__________________لاحقة",
  "temperature": "بيت_Temperature____لاحقة",
  "wind": "بيت_Wind__لاحقة",
  "c": "بيت_C_لاحقة",
  "f": "بيت_F_لاحقة",
  "weatherErrorMessage": "بيت_Weather info not obtained. Update Wind Speed and Time of Spill values manually________________________لاحقة",
  "windDirection": "بيت_Wind Direction (blowing to)_________لاحقة",
  "timeOfSpill": "بيت_Time of Spill_____لاحقة",
  "day": "بيت_Day__لاحقة",
  "night": "بيت_Night___لاحقة",
  "windSpeed": "بيت_Wind Speed____لاحقة",
  "low": "بيت_Low__لاحقة",
  "moderate": "بيت_Moderate___لاحقة",
  "high": "بيت_High__لاحقة",
  "transportContainer": "بيت_Transport Container_______لاحقة",
  "rail": "بيت_Rail tank car_____لاحقة",
  "semi": "بيت_Highway tank truck or trailer__________لاحقة",
  "mton": "بيت_Multiple ton cylinders________لاحقة",
  "ston": "بيت_Multiple small cylinders or single ton cylinder_______________لاحقة",
  "ag": "بيت_Agricultural nurse tank________لاحقة",
  "msm": "بيت_Multiple small cylinders________لاحقة",
  "bleveLabel": "بيت_Show BLEVE Isolation Zone_________لاحقة",
  "capacity": "بيت_Container Capacity (litres)_________لاحقة",
  "bleveMessage": "بيت_For the material you have selected an additional evacuation distance can be shown for BLEVE.\n\nTo enable this, set the Show BLEVE Isolation Zone toggle to on and select the appropiate container capacity______________________________________________________________لاحقة.",
  "noPAZoneMessage": "بيت_There are no Protective Action distances for this material. Only the Initial Isolation and evacuation zones has been calculated_______________________________________لاحقة",
  "settingsTitle": "بيت_Settings___لاحقة",
  "spillLocationLabel": "بيت_Spill Location_____لاحقة",
  "spillLocationButtonLabel": "بيت_Configure Spill Location Settings___________لاحقة",
  "IISettingsLabel": "بيت_Initial Isolation Zone________لاحقة",
  "IIButtonLabel": "بيت_Configure Initial Isolation Settings____________لاحقة",
  "PASettingsLabel": "بيت_Protective Action Zone________لاحقة",
  "PAButtonLabel": "بيت_Configure Protective Action Settings____________لاحقة",
  "downwindSettingsLabel": "بيت_Down Wind Zone_____لاحقة",
  "downwindButtonLabel": "بيت_Configure Down Wind Settings_________لاحقة",
  "fireSettingsLabel": "بيت_Fire Isolation Zone_______لاحقة",
  "fireButtonLabel": "بيت_Configure Fire Isolation Settings___________لاحقة",
  "bleveSettingsLabel": "بيت_BLEVE Isolation Zone_______لاحقة",
  "bleveButtonLabel": "بيت_Configure BLEVE Settings________لاحقة",
  "outlineStyle": "بيت_Outline Style_____لاحقة",
  "dash": "بيت_Dash__لاحقة",
  "dashdot": "بيت_Dash Dot___لاحقة",
  "dashdotdot": "بيت_Dash Dot Dot_____لاحقة",
  "dot": "بيت_Dot__لاحقة",
  "longdash": "بيت_Long Dash____لاحقة",
  "longdashdot": "بيت_Long Dash Dot_____لاحقة",
  "null": "بيت_Null__لاحقة",
  "shortdash": "بيت_Short Dash____لاحقة",
  "shortdashdot": "بيت_Short Dash Dot_____لاحقة",
  "shortdashdotdot": "بيت_Short Dash Dot Dot______لاحقة",
  "shortdot": "بيت_Short Dot____لاحقة",
  "solid": "بيت_Solid___لاحقة",
  "fillStyle": "بيت_Fill Style____لاحقة",
  "backward": "بيت_Backward___لاحقة",
  "cross": "بيت_Cross___لاحقة",
  "diagonal": "بيت_Diagonal___لاحقة",
  "forward": "بيت_Forward___لاحقة",
  "horizontal": "بيت_Horizontal____لاحقة",
  "vertical": "بيت_Vertical___لاحقة",
  "resultsTitle": "بيت_Results___لاحقة",
  "publishERGBtn": "بيت_Publish___لاحقة",
  "ERGLayerName": "بيت_Published ERG Layer Name________لاحقة",
  "invalidERGLayerName": "بيت_Layer name must only contain alpha-numeric characters and underscores______________________لاحقة",
  "missingERGLayerName": "بيت_You must enter a name for the ERG___________لاحقة",
  "publishingFailedLayerExists": "بيت_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________لاحقة.",
  "checkService": "بيت_Check Service: {0}______لاحقة",
  "createService": "بيت_Create Service: {0}_______لاحقة",
  "unableToCreate": "بيت_Unable to create: {0}_______لاحقة",
  "addToDefinition": "بيت_Add to definition: {0}________لاحقة",
  "successfullyPublished": "بيت_Successfully published web layer{0}Manage the web layer__________________لاحقة",
  "userRole": "بيت_Unable to create service because user does not have permissions____________________لاحقة",
  "transparency": "بيت_Transparency_____لاحقة",
  "outline": "بيت_Outline___لاحقة",
  "fill": "بيت_Fill (Color only applies when style set to solid)________________لاحقة",
  "createERGBtn": "بيت_Create Zones_____لاحقة",
  "clearERGBtn": "بيت_Clear___لاحقة",
  "labelFormat": "بيت_Label Format_____لاحقة",
  "helpIconTooltip": "بيت_The threshold between small and large spill sizes are:\nLiquids - 55 gallons (208 liters)\nSolids - 60 pounds (300 kilograms)_______________________________________لاحقة",
  "cellWidth": "بيت_Cell Width (x)_____لاحقة",
  "cellHeight": "بيت_Cell Height (y)______لاحقة",
  "invalidNumberMessage": "بيت_The value entered is not valid__________لاحقة",
  "invalidRangeMessage": "بيت_Value must be greater than 0_________لاحقة",
  "gridAngleInvalidRangeMessage": "بيت_Value must be between -89.9 and 89.9____________لاحقة",
  "formatIconTooltip": "بيت_Format Input_____لاحقة",
  "setCoordFormat": "بيت_Set Coordinate Format String_________لاحقة",
  "prefixNumbers": "بيت_Add '+/-' prefix to positive and negative numbers________________لاحقة",
  "cancelBtn": "بيت_Cancel___لاحقة",
  "applyBtn": "بيت_Apply___لاحقة",
  "comfirmInputNotation": "بيت_Confirm Input Notation________لاحقة",
  "notationsMatch": "بيت_notations match your input please confirm which you would like to use______________________لاحقة:",
  "missingLayerNameMessage": "بيت_You must enter a valid layer name before you can publish__________________لاحقة",
  "parseCoordinatesError": "بيت_Unable to parse coordinates. Please check your input_________________لاحقة.",
  "DD": "بيت_DD__لاحقة",
  "DDM": "بيت_DDM__لاحقة",
  "DMS": "بيت_DMS__لاحقة",
  "DDRev": "بيت_DDRev___لاحقة",
  "DDMRev": "بيت_DDMRev___لاحقة",
  "DMSRev": "بيت_DMSRev___لاحقة",
  "USNG": "بيت_USNG__لاحقة",
  "MGRS": "بيت_MGRS__لاحقة",
  "UTM_H": "بيت_UTM (H)___لاحقة",
  "UTM": "بيت_UTM__لاحقة",
  "GARS": "بيت_GARS__لاحقة",
  "GEOREF": "بيت_GEOREF___لاحقة",
  "DDLatLongNotation": "بيت_Decimal Degrees - Latitude/Longitude____________لاحقة",
  "DDLongLatNotation": "بيت_Decimal Degrees  - Longitude/Latitude____________لاحقة",
  "DDMLatLongNotation": "بيت_Degrees Decimal Minutes - Latitude/Longitude______________لاحقة",
  "DDMLongLatNotation": "بيت_Degrees Decimal Minutes - Longitude/Latitude______________لاحقة",
  "DMSLatLongNotation": "بيت_Degrees Minutes Seconds - Latitude/Longitude______________لاحقة",
  "DMSLongLatNotation": "بيت_Degrees Minutes Seconds - Longitude/Latitude______________لاحقة",
  "GARSNotation": "بيت_GARS__لاحقة",
  "GEOREFNotation": "بيت_GEOREF___لاحقة",
  "MGRSNotation": "بيت_MGRS__لاحقة",
  "USNGNotation": "بيت_USNG__لاحقة",
  "UTMBandNotation": "بيت_UTM - Band Letter______لاحقة",
  "UTMHemNotation": "بيت_UTM - Hemisphere (N/S)________لاحقة"
});